<?php /** module/Admin/view/interpreters-office/admin/users/form.phtml */

/*
 *  module/Admin/view/interpreters-office/admin/user/form.phtml
 *  view script for rendering users add|edit form
 */
$this->headTitle($this->title);
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;
$formAction = strstr($this->title, 'add') ? $this->url('users/add')
    : $this->url('users/edit', ['id' => $this->id ]);
$form = $this->form;
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
     'attributes' => ['value' => 'save','class'=>'btn btn-success btn-lg'],
])->setAttribute('method', 'post')->setAttribute('action', $formAction)
   ->setAttribute('class', 'form-horizontal')    ;
?>
<div class="center-block" style="max-width:800px"><!-- wrapper -->
<h2><?php echo $this->title ?></h2>
<?php
$form->prepare();
$fieldset = $this->form->get('user')->get('person');
echo $this->form()->openTag($form);
 // text inputs
foreach (['lastname','firstname','middlename','email','officePhone','mobilePhone'] as $elementName) :
    $element = $fieldset->get($elementName);?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>            
    </div>
</div>
<?php endforeach; 
$hat = $fieldset->get('hat');
?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $hat->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formElement($hat),$this->formElementErrors($hat) ?>            
    </div>
</div>
<?php $role = $this->form->get("user")->get('role'); ?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $role->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formElement($role),$this->formElementErrors($role) ?>            
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9" style="margin-top:.5em">
    <?php
    $csrf = $form->get('csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    echo $this->formHidden($fieldset->get('id'));    
    echo $this->formSubmit($form->get('submit'));
?></div> 	    
</div>

<?php 
echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
