<?php /** module/Admin/view/interpreters-office/admin/users/form.phtml */

/*
 *  module/Admin/view/interpreters-office/admin/user/form.phtml
 *  view script for rendering users add|edit form
 */
$this->headTitle($this->title);
?>
<div class="center-block" style="max-width:800px"><!-- wrapper -->
<h2><?php echo $this->title ?></h2>
<?php // echo $this->url('users/edit',['id'=> 3]);?>
<?php if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div></div>
<?php
return;
endif;
$formAction = strstr($this->title, 'add') ? $this->url('users/add')
    : $this->url('users/edit', ['id' => $this->id ]);
$form = $this->form;
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
    'attributes' => ['value' => 'save','class'=>'btn btn-success btn-lg'],
])->setAttribute('method', 'post')->setAttribute('action', $formAction)
   ->setAttribute('class', 'form-horizontal')    ;
?>

<?php
$form->prepare();
$person_fieldset = $this->form->get('user')->get('person');
echo $this->form()->openTag($form);
 // text inputs
foreach (['lastname','firstname','middlename','email','officePhone','mobilePhone'] as $elementName) :
    $element = $person_fieldset->get($elementName);?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>            
    </div>
</div>
<?php endforeach; 
$hat = $person_fieldset->get('hat');
?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $hat->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formElement($hat),$this->formElementErrors($hat) ?>            
    </div>
</div>
<?php
$person_active = $person_fieldset->get('active');?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $person_active->getLabel()?></label>
    <div class="col-sm-9" style="padding-top:.25em"><?php echo $this->formCheckbox($person_active),$this->formElementErrors($person_active) ?>            
    </div>
 </div>
<?php 
$user_fieldset = $this->form->get("user");
$role = $user_fieldset->get('role'); ?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $role->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formElement($role),$this->formElementErrors($role) ?>            
    </div>
</div>
<?php $username = $user_fieldset->get('username');?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $username->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formElement($username),$this->formElementErrors($username) ?>            
    </div>
</div>
<?php 
$user_active = $user_fieldset->get('active');?>
<div class="form-group">
    <label class="control-label col-sm-3">user account enabled</label>
    <div class="col-sm-9" style="padding-top:.25em"><?php echo $this->formCheckbox($user_active),$this->formElementErrors($user_active) ?>            
    </div>
 </div>
<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9" style="margin-top:.5em">
    <?php
    $csrf = $form->get('csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    echo $this->formHidden($person_fieldset->get('id'));    
    echo $this->formHidden($user_fieldset->get('id'));    
    echo $this->formSubmit($form->get('submit'));
?></div> 	    
</div>
<?php 
echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
<script type="text/javascript">
    $(function(){
    	// help enforce logical consistency between user-account "active"
    	// and person "active" properties
        var userActiveElement = $('#user-active');
        var personActiveElement = $('#person-active');
        $('#user-active, #person-active').on("change",function(event){
            if (! personActiveElement.is(":checked")) {
                userActiveElement.prop("checked",false);
            }
            if (userActiveElement.is(":checked")) {
                personActiveElement.prop("checked",true);
            }
            if (event.target.id === 'user-active')  {
            	if (! userActiveElement.is(':checked')  && ! personActiveElement.is(':checked')) {
            		personActiveElement.prop("checked",true);
            		userActiveElement.prop("checked",true);
            	}
            }      
        });
    });
</script>