<h2>form example</h2>
<form style="max-width:900px" class="mx-auto">
    <div class="form-row">
        <div class="col-md-6">
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">password</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputPassword3" placeholder="Password">
                </div>
            </div>
        </div>
    </div>   
</form>
