<h2>form example</h2>
<form style="max-width:900px" class="mx-auto">
    <div class="form-row">
        <div class="col-md-6">
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-3 col-form-label  pr-1">email</label>
                <div class="col-sm-9">
                    <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group row">
                <label for="thing2" class="col-sm-3 col-form-label pr-1">some shit</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="thing2" placeholder="some shit">
                </div>
            </div>
        </div>
    </div>   
</form>
