<?php 

namespace Application\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity  @ORM\Table(name="people",uniqueConstraints={@ORM\UniqueConstraint(name="hat_email_idx",columns={"email","hat_id"})}) 
 * @ORM\InheritanceType("JOINED")
 *
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"person" = "Person", "user"="User"})
 */

// to be added to DiscriminatorMap: "judge" = "Judge"
// Columns that have NOT NULL constraints have to be on the root entity of the single-table inheritance hierarchy.

class Person 
{

	/**
	 * @ORM\Id @ORM\GeneratedValue @ORM\Column(type="smallint",options={"unsigned":true})
	 */
	protected $id;

    /**
     * @ORM\Column(type="string",length=50,nullable=true)
     * @var string
     */
    protected $email;

    /**
     * @ORM\Column(type="string",length=50,nullable=false)
     * @var string
     */
    protected $lastname;
	
    /**
     * @ORM\Column(type="string",length=50,nullable=false)
     * @var string
     */
    protected $firstname;

    /**
     *  everyone must where a hat in this life.
     * 
     *  @ORM\ManyToOne(targetEntity="Hat",fetch="EAGER")
     *  @ORM\JoinColumn(nullable=false)
     *  @var Hat
     */
    protected $hat;

    //----------- generated by Doctrine ------------//
        
    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return Person
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     *
     * @return Person
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     *
     * @return Person
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set hat
     *
     * @param \Application\Entity\Hat $hat
     *
     * @return Person
     */
    public function setHat(\Application\Entity\Hat $hat)
    {
        $this->hat = $hat;

        return $this;
    }

    /**
     * Get hat
     *
     * @return \Application\Entity\Hat
     */
    public function getHat()
    {
        return $this->hat;
    }
}
