<?php  $this->headTitle('admin | search');
$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
$this->headScript()
    ->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.js'))
    ->appendFile($this->basePath('js/search.js'));

$form = $this->form;
?>
<h2 class="text-center"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
<?php if ($this->docket): ?>your docket number is <code><?php echo $this->escapeHtml($this->docket)?></code> <?php endif ?>

<?php echo $this->errorMessage($this->errorMessage,$this->header); ?>
<form name="search-form" class="mx-auto mt-4" style="max-width:850px" action="<?php echo $this->url('search') ?>" method="get">
    <?php
    $messenger = $this->flashMessenger();
    if ($messenger->hasSuccessMessages()) :
        echo $messenger->render('success', ['alert','alert-success',], false);
    endif;
    ?>
<div class="form-group row">
    <label class="col-sm-2 col-form-label text-md-right pr-0" for="docket">docket</label>
    <div class="col-sm-3">
        <?php echo $this->formElement($form->get('docket'))?>
    </div>
    <label class="col-form-label text-md-right pr-0" for="language">language</label>
    <div class="col-sm-3">
        <?php echo $this->formElement($form->get('language'))?>
    </div>
</div>
<!-- -->
<div class="form-group row">
    <div class="col-sm-2 col-form-label text-md-right pr-0">date range</div>
    <label class="col-form-label text-md-right pl-3 pr-0 text-muted" for="date-from">from</label>
    <div class="col-sm-3">
        <?php echo $this->formElement($form->get('date-from'))?>
    </div>
    <label class="col-form-label pr-0 text-muted" for="date-to">to</label>
    <div class="col-sm-3">
        <?php echo $this->formElement($form->get('date-to'))?>
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label text-md-right pr-0" for="judge">judge</label>
    <div class="col-sm-4">
        <?php echo $this->formElement($form->get('judge'))?>
    </div>
    <label class="col-sm-1 col-form-label text-md-right pr-0 pl-1" for="defendant-name">defendant</label>
    <div class="col-sm-3">
        <?php echo $this->formElement($form->get('defendant-name'))?>
    </div>
    <!-- -->
    <button id="btn-submit" class="btn btn-primary col-sm-1">
        <span class="fas fa-search"></span><span class="sr-only">search</span>
    </button>
    <!-- -->
</div>
<div class="form-group row">
    <?php echo $this->formElement($form->get('submit')) ?>
    <div class="p-1 col-sm-5 validation-error offset-sm-2 mt-0 alert alert-warning" style="display:none" id="error_submit">
    </div>
</div>
</form>
<div id="results"><?php if ($this->results): echo $this->render('search/results'); endif;?></div>
