<?php  $this->headTitle('admin | search');
$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
$this->headScript()
    ->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.js'))
    ->appendFile($this->basePath('js/search.js'));

$form = $this->form;
?>
<h2 class="text-center"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
<?php echo $this->errorMessage($this->errorMessage,$this->header); ?>
<form name="search-form" class="mx-auto mt-4 bg-light py-1 px-2" style="max-width:1100px" action="<?php echo $this->url('search') ?>" method="get">
    <div class="form-group row mt-2">
        <label for="docket" class="col-form-label col-auto text-md-right pr-0">
            docket
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('docket'))?>
        </div>
        <label for="language" class="col-form-label  col-sm-1 text-md-right pr-0">
            language
        </label>
        <div class="col-sm-2">
            <?php echo $this->formElement($form->get('language'))?>
        </div>
        <label for="judge" class="col-form-label col-auto text-md-right pr-0">
            judge
        </label>
        <div class="col-sm-3">
            <?php echo $this->formElement($form->get('judge'))?>
        </div>
    </div>
    <div class="form-group row">
        <label for="event_type" class="col-form-label col-auto text-md-right pr-0">
            type
        </label>
        <div class="col-auto">
            <?php echo $this->formElement($form->get('eventType'))?>
        </div>
        <label class="col-form-label col-auto text-md-right pr-0" for="defendant-name">defendant</label>
        <div class="col-auto">
            <?php echo $this->formElement($form->get('defendant-name'))?>
        </div>
        <label class="col-form-label col-auto text-md-right pr-0" for="interpreter">interpreter</label>
        <div class="col-auto">
            <?php echo $this->formElement($form->get('interpreter'))?>
            <?php echo $this->formElement($form->get('interpreter_id'))?>
        </div>
    </div>
    <div class="form-group row mb-0 pb-0">
        <div class="col-form-label col-auto text-md-right pr-0">date range</div>
        <label class="col-form-label text-md-right pl-3 pr-0 text-muted" for="date-from">from</label>
        <div class="col-auto">
            <?php echo $this->formElement($form->get('date-from'))?>
        </div>
        <label class="col-form-label col-auto pr-0 text-muted" for="date-to">to</label>
        <div class="col-auto">
            <?php echo $this->formElement($form->get('date-to'))?>
        </div>
        <label for="order" class="col-form-label col-auto text-md-right pr-0">
            sort by
        </label>
        <div class="col-auto">
            <?php echo $this->formElement($form->get('order'))?>
        </div>
        <button id="btn-submit" class="col-sm-1 btn btn-primary ">
            <span class="fas fa-search"></span><span class="sr-only">search</span>
        </button>
    </div>
    <div class="form-group row pb-0 mb-2"><?php echo $this->formElement($form->get('submit')) ?>
        <div class="py-1 mt-1 col-sm-5 validation-error offset-sm-2 mt-0 alert alert-warning" style="display:none" id="error_submit">
        </div>
    </div>
</form>

<div id="results"><?php if ($this->results): echo $this->render('search/results'); endif;?></div>
