<?php
/** module/InterpretersOffice/view/interpreters-office/defendants/search.phtml */
//exit("\$search is $this->search");
if (! $this->paginator->count()):
    echo "no matching results found";
return;   
endif;
?><ul class="list-group defendant-names" style="font-size:90%"><?php
foreach ($paginator as $deft): 
    ?><li data-id="<?php echo $deft->getId()?>" class="list-group-item align-middle py-1 ">
    <a href="javascript:void(0)">
    <?php
    echo $this->escapeHtml(sprintf('%s, %s', $deft->getLastname(), $deft->getFirstname()));
    ?><!--
    <span title="add this defendant" class="float-right bg-info text-light rounded p-1 fas fa-plus"></span>
      -->
    </a></li>
   <?php
endforeach;
?></ul>
<?php // return;
echo $this->paginationControl(
    $this->paginator,
    'sliding',
    'partials/pagination_control',
    ['route' => 'defendant-search','query'=>['term'=>$this->search]]
);?>