<?php /** module/InterpretersOffice/view/interpreters-office/account/register.phtml */
$this->headScript()  //->appendFile($this->basePath('js/lib/vue.js'))
    ->appendFile($this->basePath('js/register.js'));
$this->headTitle("create your user account");
$form = $this->form;?>

<div class="center-block" style="max-width:700px"><!-- wrapper -->
<h2 class="text-center py-2">account registration</h2>
<div id="success-message" class="alert alert-success" style="display:none"></div>
<?php

$form->prepare();
$user_fieldset = $form->get('user');
$person_fieldset = $user_fieldset->get('person');
$hat = $person_fieldset->get('hat');
$hat->setLabel('job title/description');
echo $this->form()->openTag($form);
?>
<!-- carousel-->
<div id="carousel" class="carousel slide" data-interval="0">
    <div class="carousel-inner">
        <fieldset id="fieldset-personal-data" class="carousel-item active"><legend class="offset-sm-3 py-3">step 1 of 3: contact details</legend>
        <?php
             // text inputs
            $person_fieldset->get('email')->setAttribute('placeholder','your uscourts.gov address');
            foreach (['lastname','middlename','firstname','office_phone','mobile_phone'] as $elementName) :
                $element = $person_fieldset->get($elementName);?>
            <div class="form-group form-row">
                <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
                <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>
                </div>
            </div>
            <?php
            endforeach;
            ?>
        </fieldset>
        <fieldset id="fieldset-password" class="carousel-item"><legend class="offset-sm-3 py-3">step 2 of 3: account details</legend>
            <?php $element = $person_fieldset->get('email'); $element->setOption("placeholder","shit")?>
            <div class="form-group form-row">
                <label class="col-form-label col-sm-3" for="email">email address</label>
                <div class="col-sm-9"><?php  echo $this->formElement($element);?>
                </div>
            </div>
            <div class="form-group form-row">
                <label class="col-form-label col-sm-3">enter password</label>
                <div class="col-sm-9"><?php  echo $this->formPassword($form->get('user')->get('password')),
                    $this->formElementErrors($form->get('user')->get('password'))?>
                </div>
            </div>
            <div class="form-group form-row">
                <label class="col-form-label col-sm-3">confirm password</label>
                <div class="col-sm-9"><?php  echo $this->formPassword($form->get('user')->get('password-confirm')),
                    $this->formElementErrors($form->get('user')->get('password-confirm'))?>
                </div>
            </div>
        </fieldset>
        <fieldset style="min-height:300px" id="fieldset-hat" class="carousel-item"><legend class="offset-sm-3 py-3">step 3 of 3: your job title/department</legend>
            <div class="form-group form-row">
                <label class="col-form-label col-sm-3"><?php echo $hat->getLabel()?></label>
                <div class="col-sm-9"><?php echo $this->formSelect($hat),$this->formElementErrors($hat) ?>
                </div>
            </div>
            <div id="judge-div" class="form-group form-row" style="display:none">
                <div id="judge-help" class="offset-sm-3 pl-1 form-text text-muted">Please select the judge(s) for whom you work and click the <strong>+</strong> button.</div>
                <label class="col-form-label col-sm-3"><?php echo $form->get('user')->get('judge-select')->getLabel() ?></label>
                <div class="col-sm-9">
                    <div class="input-group">
                        <?php echo $this->formSelect($form->get('user')->get('judge-select'))?><button class="btn btn-info fas fa-plus" title="identify the currently selected Judge as one for whom you work" type="button" id="btn-add-judge"><span class="sr-only">select</span></button>
                    </div>
                    <ul id="judges" class="list-group mt-1"></ul>
                </div>
            </div>
        </fieldset>
        <!-- /carousel-->
    </div>
</div>
<div class="form-group form-row">
    <div class="offset-sm-3 col-sm-9">
        <button id="btn-back" class="btn btn-large btn-primary" style="display:none">back</button>
        <button id="btn-next" class="btn btn-large btn-primary">continue</button>
    </div>
    <?php
    echo $this->formHidden($person_fieldset->get('id'));
    echo $this->formHidden($user_fieldset->get('id'));
    $csrf = $form->get('csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    ?>
</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
<div id="modal-add-judge" class="modal" tabindex="-1" role="dialog" aria-labelledby="add-judge-label" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header sr-only" id="add-judge-label">Add judge?</div>
      <div class="modal-body"></div>
      <div class="modal-footer justify-content-center text-center">
        <button id="btn-yes-add-judge" type="button" class="btn btn-success mr-0" data-dismiss="modal">yes</button><!--
        --><button id="btn-no-add-judge" type="button" class="btn btn-secondary ml-1" data-dismiss="modal">no</button>
      </div>
    </div>
  </div>
</div>
<div class="modal" id="modal-duplicate-account" tabindex="-1" role="dialog" aria-labelledby="duplicate-account" aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header" id="duplicate-account">Account already exists</div>
        <div class="modal-body"></div>
        <div class="modal-footer justify-content-center text-center">
            <button id="btn-dismiss" type="button" class="btn btn-secondary ml-1" data-dismiss="modal">OK</button>
        </div>
      </div>
    </div>
</div>
