<?php /** module/InterpretersOffice/view/interpreters-office/account/register.phtml */
$this->headScript()->appendFile($this->basePath('js/register.js'));
$form = $this->form;?>

<div class="center-block" style="max-width:700px"><!-- wrapper -->
<h2 class="text-center mb-3">account registration</h2>
<?php
$form->prepare();
$user_fieldset = $form->get('user');
$person_fieldset = $user_fieldset->get('person');
$hat = $person_fieldset->get('hat');
$hat->setLabel('job title/description');
echo $this->form()->openTag($form);
?>
<!-- carousel-->
<div id="carousel" class="carousel slide" data-interval="0">
    <div class="carousel-inner">
        <fieldset id="fieldset-personal-data" class="carousel-item active"><legend class="offset-sm-3">step 1 of 3: personal data</legend>
        <?php
             // text inputs
            $person_fieldset->get('email')->setAttribute('placeholder','(required)');
            foreach (['lastname','middlename','firstname','email','office_phone','mobile_phone'] as $elementName) :
                $element = $person_fieldset->get($elementName);?>
            <div class="form-group form-row">
                <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
                <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>
                </div>
            </div>
            <?php
            endforeach;
            ?>
        </fieldset>
        <fieldset style="min-height:300px" id="fieldset-hat" class="carousel-item"><legend class="offset-sm-3">step 2 of 3: your job title/department</legend>
            <div class="form-group form-row">
                <label class="col-form-label col-sm-3"><?php echo $hat->getLabel()?></label>
                <div class="col-sm-9"><?php echo $this->formSelect($hat),$this->formElementErrors($hat) ?>
                </div>
            </div>
        </fieldset>
        <fieldset id="fieldset-password" class="carousel-item"><legend class="offset-sm-3">step 3 of 3: set your password</legend>
            <div class="form-group form-row">
                <label class="col-form-label col-sm-3">enter password</label>
                <div class="col-sm-9"><?php  echo $this->formPassword($form->get('user')->get('password')),
                    $this->formElementErrors($form->get('user')->get('password'))?>
                </div>
            </div>
            <div class="form-group form-row">
                <label class="col-form-label col-sm-3">confirm password</label>
                <div class="col-sm-9"><?php  echo $this->formPassword($form->get('user')->get('password-confirm')),
                    $this->formElementErrors($form->get('user')->get('password-confirm'))?>
                </div>
            </div>
        </fieldset>
        <!-- /carousel-->
    </div>
</div>
<div class="form-group form-row">
    <div class="offset-sm-3 col-sm-9"><button id="btn-next" class="btn btn-large btn-primary">next</button></div>
    <?php
    echo $this->formHidden($person_fieldset->get('id'));
    echo $this->formHidden($user_fieldset->get('id'));
    $csrf = $form->get('csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    ?>
</div>
<?php //echo $this->form()->openTag($form);?>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
