<?php /** module/InterpretersOffice/view/interpreters-office/account/request-password.phtml */
$this->headTitle("reset password");
$this->headScript()->appendFile($this->basePath('js/request-password.js'));
?>
<div class="center-block" style="max-width:800px"><!-- wrapper -->
    <h2>reset your password</h2>
    <div class="alert alert-success" style="display:none" >
        If there is a valid user account associated with this address, we will
        send password reset instructions. Please check your inbox.
    </div>
    <p>Please enter the email address for your user account:</p>
    <div class="form-row">
        <div class="col">
            <input id="email" class="form-control" type="text" name="email" value="" placeholder="your email address">
        </div>
        <div class="col">
            <button id="btn-submit" class="btn btn-large btn-primary">request password</button>
        </div>
    </div>
</div>
