<?php /** module/InterpretersOffice/view/interpreters-office/account/request-password.phtml */
use Laminas\Form\Element\Csrf;

$this->headTitle("reset password");
$this->headScript()->appendFile($this->basePath('js/request-password.js'));
?>
<div class="form-row">
    <div class="offset-md-3"><h2 class="my-4 text-primary">reset password</h2></div>
</div>
<div class="form-row">
    <div class="col-7 offset-md-2 alert alert-success px-3 py-2" style="display:none">
        <p>Thank you.</p>
        <p>
            If there is a valid user account associated with this address, we will
            send a message with instructions for resetting the password.
            Please check your inbox.
        </p>
    </div>
    <div class="w-100"></div>
    <div class="col-4 offset-md-2 request-password">
        <input id="email" class="form-control" type="text" name="email" value="" placeholder="your email address">
        <?php echo $this->formElement((new Csrf('csrf'))->setAttribute('id','csrf'));?>
    </div>
    <div class="col-5 request-password"><button id="btn-submit" class="btn btn-large btn-primary ml-0">request password</button>
    </div>
</div>
