<?php /** module/InterpretersOffice/view/interpreters-office/account/request-password.phtml */
use Zend\Form\Element\Csrf;

$this->headTitle("reset password");
$this->headScript()->appendFile($this->basePath('js/request-password.js'));
?>
<div class="form-row">
    <div class="offset-md-3"><h2 class="my-4 text-primary">reset your password</h2></div>
</div>
<div class="form-row">
    <div class="col-4 offset-md-3">
        <input id="email" class="form-control" type="text" name="email" value="" placeholder="your email address">
        <?php echo $this->formElement(new Csrf('csrf'));?>
    </div>
    <div class="col-5"><button id="btn-submit" class="btn btn-large btn-primary ml-0">request password</button>
    </div>
</div>
