<?php
/** module/InterpretersOffice/view/interpreters-office/account/reset-password.phtml */
use Zend\Form\Element\Csrf;

$this->headScript()->appendFile($this->basePath('js/reset-password.js'));
?>
<div class="form-row">
    <div class="offset-md-2"><h2 class="my-4 text-primary">reset password</h2></div>
</div>
<form name="reset-password" id="form-reset-password" action="javascript:void(0)" method="post">


<div class="form-row">
    <div class="offset-md-2"><?php
    if (! $this->result['data']): ?>
        <div class="alert alert-warning">
            <p>
                Error: <?php echo $this->result['error'];   ?>.
            </p>
            <p>
                Please <a href="<?php echo $this->url('account/request-password')?>">request a new password</a> again
                to have the instructions re-sent to your email address.
            </p>
        </div>
        <?php
    else: ?>
    <p>
        Hello, <?php echo $this->escapeHtml("{$this->result['data']['firstname']} {$this->result['data']['lastname']}") ?>.
        You can now reset your password.
    </p>
    </div>
</div>
<div class="form-group form-row">
    <label for="password" class="offset-md-2 col-form-label col-md-3 text-lg-right">new password</label>
    <div class="col-sm-6">
        <input type="text" id="password" name="password" value="" class="form-control">
    </div>
</div>
<div class="form-group form-row">
    <label  for="password-confirm" class="offset-md-2 col-form-label col-md-3 text-lg-right">confirm password</label>
    <div class="col-sm-6">
        <input type="text" id="password-confirm" name="password-confirm" value="" class="form-control">
        <?php echo $this->formElement((new Csrf('csrf'))->setAttribute('id','csrf'));?>
        <input type="hidden" name="token" id="token" value="<?php echo $this->token?>">
    </div>
    <div class="offset-md-5 col-sm-6 pt-3">
        <button type="button" id="btn-submit" class="btn btn-success" name="button">submit</button>
    </div>
</div>
</form>
<!-- <pre><?php echo $this->token; //print_r($this->result); ?></pre> -->
<?php endif; ?>
