<?php /** module/InterpretersOffice/view/interpreters-office/account/verify-email.phtml */
$this->headTitle("verify email address");
use InterpretersOffice\Service\AccountManager;
?>
<h2>email confirmation</h2>
<?php if ($this->error):?>
    <div class="alert alert-warning">
        Sorry, we were unable to validate your account/email address. The error
        message we encountered is: <?php echo $this->error ?>.
    </div><?php
    return;
endif;
if ($this->user):
    $person = $this->user->getPerson();
    $this->form = new \InterpretersOffice\Form\LoginForm()
    // to do: make this a partial or something, so we don't repeat login.phtml
    ?>
    <div class="alert alert-success">
    Welcome, <?php echo $person->getFirstname()," ",$person->getLastName() ?>.
    Your email has been verified and your user account has been activated. You
    are welcome to log in.
    </div>
    <form class="form-inline" style="align-content:center" id="form-login" action="<?php echo $this->url('login') ?>" method="post">
        <div class="form-group">
          <label class="sr-only" for="identity">username or email</label>
                <?php echo $this->formElementErrors($this->form->get('identity'))?>
            <?php echo $this->formElement($this->form->get('identity')); //return; ?>
        </div>
        <div class="form-group pl-1">
          <label class="sr-only" for="password">password</label>
                <?php echo $this->formElementErrors($this->form->get('password')) ?>
                <?php echo $this->formElement($this->form->get('password')); //return; ?>
        </div>
          <button type="submit" class="btn btn-info ml-1">log in</button>
            <?php echo $this->formElement($this->form->get('login_csrf')) ?>
            <?php echo $this->formElementErrors($this->form->get('login_csrf')) ?>
     </form>
<?php endif;
