<?php /** module/InterpretersOffice/view/interpreters-office/account/verify-email.phtml */
$this->headTitle("verify email address");
use InterpretersOffice\Service\AccountManager;
use InterpretersOffice\Form\LoginForm;
?>
<h2>email confirmation</h2>
<?php //echo $this->partial('partials/login.phtml',['form'=>new \InterpretersOffice\Form\LoginForm()]); ?>
<?php if ($this->error):?>
    <div class="alert alert-warning">
        Sorry, we were unable to validate your account/email address. The error
        message we encountered is: <?php echo $this->error ?>.
    </div><?php
    return;
endif;
if ($this->user):
    $person = $this->user->getPerson();
    ?>
    <div class="alert alert-success">
    Thank you, <?php echo $person->getFirstname()," ",$person->getLastName() ?>.
    Your email has been verified and your user account has been activated. You
    are welcome to log in.
    </div>
    <?php echo $this->partial('partials/login.phtml',['form'=>new LoginForm()]);
endif;
