<?php echo"this is " . $this->url() ?>
<div class="center-block" style="max-width:750px">
    <h2><?php echo $this->title ?></h2>
    <p>Use this form to add a new language. Please be careful 
      to avoid inserting a language that is an inexact duplicate, alternate name 
    or spelling, or a superset of another that already exists in your database.</p>
    
<?php
$form->setAttribute('action', $this->url());
$form->add([
	'name'=>'submit',
	'type'=>'Zend\Form\Element\Submit',
	'attributes' => ['value'=>'submit'],
])->setAttribute('method', 'post');

$form->prepare();
echo $this->form()->openTag($form);?>
<div class="form-group"><?php 
$name = $form->get('name');
echo $this->formLabel($name);
echo $this->formElement($name);
echo $this->formElementErrors($name);
?>
</div> 
<div class="form-group">
<?php 
$comments = $form->get('comments');
echo $this->formLabel($comments);
echo $this->formElement($comments);
echo $this->formElementErrors($comments);
?>		
</div>
<div class="form-group">
<?php 
//echo $this->formRow($fieldset->get('middlename')),"<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>
</div>