<?php 
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;

$action = strstr($this->title,'add') ? 'add' : 'edit' ?>

<div class="center-block" style="max-width:750px">
    <h2><?php echo $this->title ?></h2>
<?php if ($action == 'add')  : ?>
    <p>Use this form to add a new language. Please be careful 
      to avoid inserting a language that is an inexact duplicate, alternate name 
    or spelling, or a superset of another that already exists in your database.</p>
<?php endif; 


$form->setAttribute('action', "/admin/languages/$action".($action=='edit' ? "/$this->id":''));
$form->add([
	'name'=>'submit',
	'type'=>'Zend\Form\Element\Submit',
	'attributes' => ['value'=>'submit'],
])->setAttribute('method', 'post');

$form->prepare();
echo $this->form()->openTag($form);?>
<div class="form-group"><?php 
$name = $form->get('name');
echo $this->formLabel($name);
echo $this->formElement($name);
echo $this->formElementErrors($name);
?>
</div> 
<div class="form-group">
<?php 
$comments = $form->get('comments');
echo $this->formLabel($comments);
echo $this->formElement($comments);
echo $this->formElementErrors($comments);
?>		
</div>
<div class="form-group">
<?php 
echo $this->formSubmit($form->get('submit'));
echo $this->formElement($form->get('id'));
echo $this->form()->closeTag();
?>
</div>
</div>