<?php /** module/Admin/view/interpreters-office/admin/users/form.phtml */

/*
 *  module/Admin/view/interpreters-office/admin/user/form.phtml
 *  view script for rendering users add|edit form
 */
$this->headTitle($this->title);
$this->headScript()
->appendFile($this->basePath('js/user-judges.js'))
->appendFile($this->basePath('js/user-form.js'));
?>
<div class="center-block" style="max-width:800px"><!-- wrapper -->
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
<?php if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div></div>
    <?php
    return;
endif;
$formAction = strstr($this->title, 'add') ? $this->url('users/add')
    : $this->url('users/edit', ['id' => $this->id ]);
$form = $this->form;
$form->add([
    'name' => 'submit', 'type' => 'Zend\Form\Element\Submit',
    'attributes' =>
     ['id' => 'btn-submit','value' => 'save','class' => 'btn btn-success btn-lg'],
])->setAttributes(['class' => 'form-horizontal','action' => $formAction]);
$person_fieldset = $this->form->get('user')->get('person');
$role_element = $form->get('user')->get('role');
if ($this->has_related_entities) :
    $person_fieldset->get('hat')->setAttribute('disabled', 'disabled');
    $user = $form->get('user')->getObject();
    if ((string)$user->getRole() == 'submitter') :
        $role_element->setAttribute('disabled', 'disabled');
    endif;
endif;
$has_judges = $form->getObject()->getJudges()->count();
$form->prepare();
echo $this->form()->openTag($form);
 // text inputs
foreach (['lastname','firstname','middlename','email','office_phone','mobile_phone'] as $elementName) :
    $element = $person_fieldset->get($elementName);?>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>
    </div>
</div>
<?php endforeach;
$hat = $person_fieldset->get('hat');
$user_fieldset = $this->form->get("user");
?>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3"><?php echo $hat->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formElement($hat),$this->formElementErrors($hat) ?>
    </div>
</div>
<?php if ($user_fieldset->has('judge-select')) :?>
<div id="judge-div" class="form-group form-row" style="display:none">
    <div id="judge-help" class="offset-sm-3 pl-1 form-text text-muted">select the judge(s) for whom this user works, and click the <strong>+</strong> button.</div>
    <label  for="judges" class="col-form-label col-sm-3">Judge(s)</label>
    <div class="col-sm-9">
        <div class="input-group">
            <?php echo $this->formSelect($form->get('user')->get('judge-select'))?><button class="btn btn-info fas fa-plus" title="identify the currently selected Judge as one for whom you work" type="button" id="btn-add-judge"><span class="sr-only">select</span></button>
        </div>
        <?php $errors = $this->formElementErrors($user_fieldset->get('judges'));
        echo $errors;?>
        <ul id="judges" class="list-group mt-1"><?php if ($has_judges && ! $errors) :
            foreach ($form->getObject()->getJudges() as $judge) :?>
                <ul id="judges" class="list-group mt-1"><li class="list-group-item py-1"><input name="user[judges][]" value="<?php echo $judge->getId()?>" type="hidden"><?php echo $judge ?><button type="button" title="click to remove this judge" class="btn btn-warning btn-sm float-right remove-div">X</button></li></ul>
            <?php endforeach;
                                                endif;?></ul>
    </div>
</div>
<?php endif;
$person_active = $person_fieldset->get('active');?>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3"><?php echo $person_active->getLabel()?></label>
    <div class="col-sm-9 pt-2"><?php echo $this->formCheckbox($person_active),$this->formElementErrors($person_active) ?>
    </div>
 </div>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3"><?php echo $role_element->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formSelect($role_element),$this->formElementErrors($role_element) ?>
    </div>
</div>
<?php $username = $user_fieldset->get('username');?>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3"><?php echo $username->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formElement($username),$this->formElementErrors($username) ?>
    </div>
</div>
<?php
$user_active = $user_fieldset->get('active');?>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3">user account enabled</label>
    <div class="col-sm-9 pt-2" style="padding-top:.25em"><?php echo $this->formCheckbox($user_active),$this->formElementErrors($user_active) ?>
    </div>
 </div>
<div class="form-group form-row">
    <div class="offset-sm-3 col-sm-9" style="margin-top:.5em">
        <div style="display:none" id="error_csrf" class="alert alert-warning validation-error"></div>
    <?php
    $csrf = $form->get('csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    echo $this->formHidden($person_fieldset->get('id'));
    echo $this->formHidden($user_fieldset->get('id'));
    echo $this->formSubmit($form->get('submit'));
    ?></div>
</div>
<?php
echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
