<?PHP /** module/Admin/view/users/index.phtml */
use Zend\Form\Element\Select;
$this->headTitle('admin | users');
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
endif;
if ($messenger->hasErrorMessages()) :
    echo $messenger->render('error', ['alert','alert-warning',], false);
endif;
$judge_element = (new Select(
    'judge',
    ['value_options' => $this->judges,
    'empty_option' => ' ',]
))->setAttributes(['class' => 'custom-select','id' => 'judge', 'style'=>'display:none']);
$this->headLink()
        ->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
$this->headScript()->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'));
?>
<div class="mx-auto" style="max-width:800px">
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
<pre><?php //print_r($this->judges)?></pre>
<p class="border shadow-sm p-3">To edit an existing user account, search the database to find it.<br>
To set up a new account, first search the user database to see whether an account already exists.
    <div class="form-group row">
        <label for="search-by" class="col-sm-2 col-form-label text-sm-right pr-1">user's</label>
        <div class="col-sm-2">
        <select class="custom-select" name="search-by" id="search-by">
            <option value="name" label="name">name</option>
            <option value="email" label="email">email</option>
            <option value="judges" label="judges">judges</option>
        </select>
        </div>
        <div class="col-sm-5 input-group ml-0 pl-0">
            <input id="user" type="text" name="user" placeholder="last name[, first name]" class="form-control">
            <?php echo $this->formElement($judge_element) ?>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button" id="button-search"><span class="fa fa-search"></span> <span class="sr-only">search</span> </button>
            </div>
        </div>
    <div>
    <?php  $this->headScript()->captureStart(); ?>
    $(function(){
        var placeholders = {
            name : "last name[, first name]",
            email : "user's email address",
        };
        $("#search-by").on("change",function(){
            var search_by =$(this).val();
            if ("judges" === search_by) {
                if ($("#user").is(":visible")) {
                    $("#judge, #user").toggle();
                }
            } else {
                $("#user").attr({placeholder: placeholders[search_by]});
                if ($("#judge").is(":visible")) {
                    $("#judge, #user").toggle();
                }
            }
        });
        $("#user").autocomplete({
            source : function(request,response) {
                var search_by = $("#search-by").val().trim();
                $.getJSON(`${window.basePath}/admin/users/autocomplete`,{
                    search_by, term: request.term
                })
                .then((data)=>{
                    response(data);
                })
                .fail(fail);
            },
            minLength: 2,
            select: function( event, ui ) {
                event.preventDefault();
                console.log(ui.item);// to be continued
            },
            focus: function(event,ui) {
                event.preventDefault();
                $(this).val(ui.item.label);
            },
        });
    });
    $('#button-search').on("click",function(e){
        console.warn("hello! time to query");
    });
    <?php  $this->headScript()->captureEnd(); ?>
</div>
