<?PHP /** module/Admin/view/users/index.phtml */
use Zend\Form\Element\Select;
$this->headTitle('admin | users');
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
endif;
if ($messenger->hasErrorMessages()) :
    echo $messenger->render('error', ['alert','alert-warning',], false);
endif;
$judge_element = (new Select(
    'judge',
    ['value_options' => $this->judges,
    'empty_option' => ' ',]
))->setAttributes(['class' => 'custom-select','id' => 'judge']);
?>
<div class="mx-auto" style="max-width:800px">
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
<pre><?php //print_r($this->judges)?></pre>
<p class="border shadow-sm p-3">To edit an existing user account, search the database to find it.<br>
To set up a new account, first search the user database to see whether an account already exists.
    <?php 
    /*To create a new user account, first <a href="<?php echo $this->url('people') ?>">check to see if the 
     person is already in your database.</a></p>*/
    ?>
    <div class="form-group row">
        <label for="user" class="col-sm-3 col-form-label text-sm-right pr-1">user</label>
        <div class="col-sm-7 input-group">
            <input id="user" type="text" name="user" placeholder="last name[, first name] or email address" class="form-control">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button" id="button-search"><span class="fa fa-search"></span> <span class="sr-only">search</span> </button>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <label for="user" class="col-sm-3 col-form-label text-sm-right pr-1">or find user by Judge</label>
        <div class="col-sm-7 input-group">
            <?php echo $this->formElement($judge_element) ?>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button" id="button-search"><span class="fa fa-search"></span> <span class="sr-only">search</span> </button>
            </div>
        </div>
    </div>
</div>
