<?php /**  module/Admin/view/users/view.phtml */?>
<div class="mx-auto px-2 pt-2" style="max-width:800px">
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
<?php if (!$this->entity): ?>
    <div class="alert alert-warning">
        No user with id <?php echo $this->id ?> found in the database.
    </div>
</div>
<?php return; endif;?>
the FUCK? <?php echo $this->layout()->action ?>
    <div class="card mt-4">
        <div class="card-body">
            <h3 class="card-title"></h3>
        </div>
    </div>
</div>
