<?php
/** 
 *  module/Admin/view/interpreters-office/admin/people/form.phtml 
 *  view script for rendering people create|update form
 */ 
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;
$formAction = strstr($this->title,'add') ? $this->url('people/add') 
	:  $this->url('people/edit',['id' => $this->id ]);
$form = $this->form;
$form->add([
	'name'=>'submit',
	'type'=>'Zend\Form\Element\Submit',
	'attributes' => ['value'=>'submit'],
])->setAttribute('method', 'post')->setAttribute('action', $formAction);
?>
<div class="center-block" style="max-width:600px"><!-- wrapper -->
<h2><?php echo $this->title ?></h2>
<?php
$form->prepare();
$fieldset = $form->get('person');
echo $this->form()->openTag($form);?>
<div class="form-group">
<?php
$hat = $fieldset->get('hat');
echo $this->formLabel($hat),$this->formSelect($hat),$this->formElementErrors($hat);
// text inputs
$elements = ['lastname','middlename','firstname','email','officePhone'];
?>
</div>
<div class="form-group">
<?php 
foreach ($elements as $elementName):
    $element = $fieldset->get($elementName);?>
    <div class="form-group">
        <?php echo  $this->formLabel($element),$this->formText($element),$this->formElementErrors($element);?>
    </div>
<?php
endforeach;
$active =  $fieldset->get('active');?>
<div class="form-group">
        <?php echo  $this->formLabel($active),$this->formCheckbox($active),$this->formElementErrors($active);?>
</div>
<div class="form-group">
<?php echo $this->formHidden($form->get('csrf'));  echo $this->formSubmit($form->get('submit'));?>
</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->