<?php
/** 
 *  module/Admin/view/interpreters-office/admin/people/form.phtml 
 *  view script for rendering people create|update form
 */
$this->headTitle($this->title);
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;
$formAction = strstr($this->title,'add') ? $this->url('people/add') 
	:  $this->url('people/edit',['id' => $this->id ]);
$form = $this->form;
$form->add([
	'name'=>'submit',
	'type'=>'Zend\Form\Element\Submit',
	'attributes' => ['value'=>'submit'],
])->setAttribute('method', 'post')
   ->setAttribute('action', $formAction)
    ->setAttribute('class', 'form-horizontal')    ;
?>
<div class="center-block" style="max-width:750px"><!-- wrapper -->
<h2><?php echo $this->title ?></h2>
<?php
$form->prepare();
$fieldset = $form->get('person');
echo $this->form()->openTag($form);?>
<div class="form-group">
<?php
$hat = $fieldset->get('hat');?>
    <div class="form-group">
        <label class="control-label col-sm-3"><?php echo $hat->getLabel()?></label>
        <div class="col-sm-9"><?php echo $this->formSelect($hat),$this->formElementErrors($hat) ?>            
        </div>
    </div>
</div>
<?php
 // text inputs
foreach ( ['lastname','middlename','firstname','email','officePhone','mobilePhone'] as $elementName):
$element = $fieldset->get($elementName);?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>            
    </div>
</div>
<?php
endforeach;
$active =  $fieldset->get('active');?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $active->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formCheckbox($active),$this->formElementErrors($active) ?>            
    </div>
 </div>
<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
   <?php 
    $csrf = $form->get('csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    echo $this->formHidden($fieldset->get('id'));
    echo $this->formSubmit($form->get('submit'));?></div>
</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->