<?php
/** module/Admin/views/interpreters-office/admin/people/index.phtml
 *  viewscript for main people-administration page
 */

$this->headTitle($this->title);
?>
<h2 class="text-center"><?php echo $this->navigation('Zend\Navigation\Admin_Breadcrumbs')->breadcrumbs()?></h2>
<?php
$messenger = $this->flashMessenger()->setAutoEscape(false);
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',]);
endif;

?>
<p>to be continued</p>
