<?php
/** module/Admin/views/interpreters-office/admin/people/index.phtml
 *  viewscript for main people-administration page
 */
use Zend\Form\Element;
$hat_element = (new Element\Select(
    'hat', ['value_options'=> $this->options,
            'empty_option' => ' -- select hat --',]
))->setAttributes(['class'=>'custom-select','id'=>'hat'])
    ->setValue($this->hat ?: '');
$status_element = (new Element\Select(
    'active', ['value_options'=> [1 => 'active',0 => 'inactive',],
    'empty_option' => ' any status ',]
))->setAttributes(['class'=>'custom-select','id'=>'active'])
->setValue($this->status ?: 1);
$this->headScript()
    ->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.js'))
    ->appendFile($this->basePath('js/people-index.js'));
    $this->headLink()
            ->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
$this->headTitle($this->title);
?>
<h2 class="text-center"><?php echo $this->navigation('Zend\Navigation\Admin_Breadcrumbs')->breadcrumbs()?></h2>
<?php
$messenger = $this->flashMessenger()->setAutoEscape(false);
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',]);
endif;
?>
<form id="search-form" class="form-inline shadow-sm border rounded pl-3 py-3 mx-auto mt-4" style="max-width:850px">
    <label class="my-1 mr-2" for="hat">hat</label>
    <?php echo $this->formElement($hat_element); ?>
    <label class="my-1 mx-2" for="status">status</label>
    <?php echo $this->formElement($status_element); ?>
    <label class="my-1 mx-2" for="name">name</label>
    <input type="text" id="name" name="name" class="form-control" value="<?php echo $this->name ? $this->escapeHtml($this->name) : ''?>" placeholder="last name[, first ]">
    <button type="submit" id="btn-search" class="btn btn-primary my-1 ml-1 "><span class="icon fa fa-search"></span> search</button>
</form>
<div class="mx-auto results" style="max-width:850px">

</div>
