<?php
/** module/Admin/views/interpreters-office/admin/people/index.phtml
 *  viewscript for main people-administration page
 */
use Zend\Form\Element;
$defaults = $this->defaults ?: ['hat'=>'','active'=>1,'name'=>'','page'=> 1];
$hat_element = (new Element\Select(
    'hat', ['value_options'=> $this->options,
            'empty_option' => ' -- select hat --',]
))->setAttributes(['class'=>'custom-select','id'=>'hat'])
    ->setValue($defaults['hat']);
$status_element = (new Element\Select(
    'active', ['value_options'=> [1 => 'active',0 => 'inactive',],
    'empty_option' => ' any status ',]
))->setAttributes(['class'=>'custom-select','id'=>'active'])
->setValue($defaults['active']);
$this->headScript()
    ->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.js'))
    ->appendFile($this->basePath('js/lib/vue.min.js'))
    ->appendFile($this->basePath('js/people-index.js'));
    $this->headLink()
            ->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
$this->headTitle($this->title);
?>
<h2 class="text-center"><?php echo $this->navigation('Zend\Navigation\Admin_Breadcrumbs')->breadcrumbs()?></h2>
<?php
$messenger = $this->flashMessenger()->setAutoEscape(false);
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',]);
endif;
?>
<form <?php if ($this->defaults): ?>data-session_defaults="1" <?php endif ?>id="search-form" class="form-inline shadow-sm border rounded pl-3 py-3 mx-auto mt-4" style="max-width:850px">
    <label class="my-1 mr-2" for="hat">hat</label>
    <?php echo $this->formElement($hat_element); ?>
    <label class="my-1 mx-2" for="status">status</label>
    <?php echo $this->formElement($status_element); ?>
    <label class="my-1 mx-2" for="name">name</label>
    <input type="text" id="name" name="name" class="form-control" value="<?php echo $this->escapeHtml($defaults['name']) ?>" placeholder="last name[, first ]">
    <button type="submit" data-page="<?php echo $this->defaults['page'] ?>" id="btn-search" class="btn btn-primary my-1 ml-1 "><span class="icon fa fa-search"></span> search</button>
</form>
<?php /** vue.js learning exercise follows. may not be doing it "right" but here goes */?>
<div id="results" class="mx-auto results" style="max-width:850px">
    <p class="status-message" style="display:none">
        <span v-if="not_found">We found nobody in the database matching the above criteria.</span>
        <span v-else>Displaying {{ from }} through {{ to }} of {{ total }} people found.</span>
    </p>
    <ul class="list-group">
        <li class="list-group-item py-1" v-for="p in people">
          {{ p.lastname }}, {{ p.firstname }}<span v-if="! hat" class="text-muted hat">, {{p.hat}}</span>
          <span  class="text-muted" v-if="active === null && ! p.active">(inactive)</span>
        </li>
    </ul>
<nav id="pagination" aria-label="navigation">
    <ul class="pagination mt-2" >
        <li class="page-item" v-if="pages.firstPageInRange > pages.first"><a class="page-link first" v-bind:href="url + '&page=1'">&lt;&lt;</a></li>
        <li v-if="pages.pageCount > 1" v-for="i in pages.pagesInRange" v-bind:class="['page-item',{active: i == current}]"><a class="page-link" v-bind:href="url + '&page=' + i">{{i}}</a></li>
        <li class="page-item" v-if="pages.lastPageInRange < pages.last"><a class="page-link last" v-bind:href="url + '&page=' + pages.last">&gt;&gt;</a></li>
    </ul>
</nav>
</div>
