
 The following SQL statements will be executed:

     ALTER TABLE event_types CHANGE name name VARCHAR(60) NOT NULL, CHANGE comments comments VARCHAR(150) DEFAULT '' NOT NULL;
     ALTER TABLE event_categories CHANGE category category VARCHAR(20) NOT NULL;
     ALTER TABLE locations CHANGE name name VARCHAR(60) NOT NULL, CHANGE active active TINYINT(1) DEFAULT '1' NOT NULL;
     ALTER TABLE events CHANGE id id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE deleted deleted TINYINT(1) DEFAULT '0' NOT NULL;
     ALTER TABLE defendants_events DROP FOREIGN KEY fk_deft_event;
     ALTER TABLE defendants_events CHANGE event_id event_id SMALLINT UNSIGNED NOT NULL;
     ALTER TABLE defendants_events ADD CONSTRAINT FK_DBDD360771F7E88B FOREIGN KEY (event_id) REFERENCES events (id);
     ALTER TABLE interpreters_events DROP FOREIGN KEY fk_event;
     ALTER TABLE interpreters_events CHANGE event_id event_id SMALLINT UNSIGNED NOT NULL;
     ALTER TABLE interpreters_events ADD CONSTRAINT FK_590E5B0771F7E88B FOREIGN KEY (event_id) REFERENCES events (id);
     ALTER TABLE interpreters_languages DROP FOREIGN KEY FK_E0423968AD59FFB1;
     ALTER TABLE interpreters_languages DROP FOREIGN KEY FK_E04239682558A7A5;
     ALTER TABLE interpreters_languages ADD CONSTRAINT FK_E0423968AD59FFB1 FOREIGN KEY (interpreter_id) REFERENCES interpreters (id);
     DROP INDEX fk_e04239682558a7a5 ON interpreters_languages;
     CREATE INDEX IDX_E04239682558A7A5 ON interpreters_languages (credential_id);
     ALTER TABLE interpreters_languages ADD CONSTRAINT FK_E04239682558A7A5 FOREIGN KEY (credential_id) REFERENCES language_credentials (id);
     ALTER TABLE roles DROP comments;
     ALTER TABLE hats CHANGE is_judges_staff is_judges_staff TINYINT(1) NOT NULL;
     DROP INDEX unique_abbrev ON language_credentials;
     DROP INDEX unique_name ON language_credentials;
     ALTER TABLE language_credentials CHANGE abbreviation abbreviation VARCHAR(15) NOT NULL, CHANGE name name VARCHAR(50) NOT NULL, CHANGE description description VARCHAR(400) NOT NULL;
     ALTER TABLE users DROP INDEX IDX_1483A5E9217BBB47, ADD UNIQUE INDEX UNIQ_1483A5E9217BBB47 (person_id);
     DROP INDEX unique_username ON users;
     ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9D60322AC;
     ALTER TABLE users DROP FOREIGN KEY users_ibfk_1;
     ALTER TABLE users CHANGE password password VARCHAR(255) NOT NULL, CHANGE username username VARCHAR(50) DEFAULT NULL, CHANGE active active TINYINT(1) DEFAULT '0' NOT NULL, CHANGE last_login last_login DATETIME NOT NULL;
     DROP INDEX person_id ON users;
     CREATE UNIQUE INDEX uniq_person_role ON users (person_id, role_id);
     ALTER TABLE users ADD CONSTRAINT FK_1483A5E9D60322AC FOREIGN KEY (role_id) REFERENCES roles (id);
     ALTER TABLE users ADD CONSTRAINT users_ibfk_1 FOREIGN KEY (person_id) REFERENCES people (id);
     ALTER TABLE verification_tokens CHANGE id id VARCHAR(255) NOT NULL, CHANGE token token VARCHAR(255) NOT NULL;
     ALTER TABLE judge_flavors CHANGE flavor flavor VARCHAR(60) NOT NULL, CHANGE weight weight INT NOT NULL;
     ALTER TABLE defendant_names DROP language_hint;
     ALTER TABLE cancellation_reasons CHANGE reason reason VARCHAR(40) NOT NULL;
     ALTER TABLE requests DROP FOREIGN KEY requests_ibfk_8;
     DROP INDEX evt_id ON requests;
     ALTER TABLE requests DROP FOREIGN KEY requests_ibfk_1;
     ALTER TABLE requests DROP FOREIGN KEY requests_ibfk_2;
     ALTER TABLE requests DROP FOREIGN KEY requests_ibfk_3;
     ALTER TABLE requests DROP FOREIGN KEY requests_ibfk_4;
     ALTER TABLE requests DROP FOREIGN KEY requests_ibfk_5;
     ALTER TABLE requests DROP FOREIGN KEY requests_ibfk_6;
     ALTER TABLE requests DROP FOREIGN KEY requests_ibfk_7;
     ALTER TABLE requests DROP FOREIGN KEY requests_ibfk_8;
     ALTER TABLE requests CHANGE id id SMALLINT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE submitter_id submitter_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE modified_by_id modified_by_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE event_id event_id SMALLINT UNSIGNED DEFAULT NULL, CHANGE docket docket VARCHAR(15) DEFAULT '' NOT NULL, CHANGE modified modified DATETIME DEFAULT NULL, CHANGE comments comments VARCHAR(600) DEFAULT '' NOT NULL, CHANGE pending pending TINYINT(1) DEFAULT '1' NOT NULL, CHANGE cancelled cancelled TINYINT(1) DEFAULT '0' NOT NULL;
     ALTER TABLE requests ADD CONSTRAINT FK_7B85D65171F7E88B FOREIGN KEY (event_id) REFERENCES events (id);
     DROP INDEX language_id ON requests;
     CREATE INDEX IDX_7B85D65182F1BAF4 ON requests (language_id);
     DROP INDEX event_type_id ON requests;
     CREATE INDEX IDX_7B85D651401B253C ON requests (event_type_id);
     DROP INDEX judge_id ON requests;
     CREATE INDEX IDX_7B85D651B7D66194 ON requests (judge_id);
     DROP INDEX anonymous_judge_id ON requests;
     CREATE INDEX IDX_7B85D651FF915C63 ON requests (anonymous_judge_id);
     DROP INDEX submitter_id ON requests;
     CREATE INDEX IDX_7B85D651919E5513 ON requests (submitter_id);
     DROP INDEX location_id ON requests;
     CREATE INDEX IDX_7B85D65164D218E ON requests (location_id);
     DROP INDEX modified_by_id ON requests;
     CREATE INDEX IDX_7B85D65199049ECE ON requests (modified_by_id);
     DROP INDEX idx_event_id ON requests;
     CREATE UNIQUE INDEX UNIQ_7B85D65171F7E88B ON requests (event_id);
     ALTER TABLE requests ADD CONSTRAINT requests_ibfk_1 FOREIGN KEY (event_type_id) REFERENCES event_types (id);
     ALTER TABLE requests ADD CONSTRAINT requests_ibfk_2 FOREIGN KEY (location_id) REFERENCES locations (id);
     ALTER TABLE requests ADD CONSTRAINT requests_ibfk_3 FOREIGN KEY (language_id) REFERENCES languages (id);
     ALTER TABLE requests ADD CONSTRAINT requests_ibfk_4 FOREIGN KEY (modified_by_id) REFERENCES users (id);
     ALTER TABLE requests ADD CONSTRAINT requests_ibfk_5 FOREIGN KEY (submitter_id) REFERENCES people (id);
     ALTER TABLE requests ADD CONSTRAINT requests_ibfk_6 FOREIGN KEY (judge_id) REFERENCES judges (id);
     ALTER TABLE requests ADD CONSTRAINT requests_ibfk_7 FOREIGN KEY (anonymous_judge_id) REFERENCES anonymous_judges (id);
     ALTER TABLE requests ADD CONSTRAINT requests_ibfk_8 FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE SET NULL;
     ALTER TABLE defendants_requests DROP FOREIGN KEY defendants_requests_ibfk_2;
     ALTER TABLE defendants_requests DROP FOREIGN KEY defendants_requests_ibfk_1;
     ALTER TABLE defendants_requests CHANGE request_id request_id SMALLINT UNSIGNED NOT NULL;
     ALTER TABLE defendants_requests ADD CONSTRAINT FK_4E73E8D427EB8A5 FOREIGN KEY (request_id) REFERENCES requests (id);
     DROP INDEX defendant_id ON defendants_requests;
     CREATE INDEX IDX_4E73E8D9960FFFB ON defendants_requests (defendant_id);
     ALTER TABLE defendants_requests ADD CONSTRAINT defendants_requests_ibfk_1 FOREIGN KEY (defendant_id) REFERENCES defendant_names (id);
     ALTER TABLE motw DROP FOREIGN KEY motw_ibfk_1;
     ALTER TABLE motw DROP FOREIGN KEY motw_ibfk_2;
     DROP INDEX created_by_id ON motw;
     CREATE INDEX IDX_2EB124B2B03A8386 ON motw (created_by_id);
     DROP INDEX modified_by_id ON motw;
     CREATE INDEX IDX_2EB124B299049ECE ON motw (modified_by_id);
     ALTER TABLE motw ADD CONSTRAINT motw_ibfk_1 FOREIGN KEY (created_by_id) REFERENCES users (id);
     ALTER TABLE motw ADD CONSTRAINT motw_ibfk_2 FOREIGN KEY (modified_by_id) REFERENCES users (id);
     ALTER TABLE task_rotation_members CHANGE rotation_order rotation_order SMALLINT UNSIGNED NOT NULL;
