<?php
/**
 * module/Admin/view/interpreters-office/admin/event-types/index.phtml.
 */
$this->headTitle($this->title);
?>
<div class="center-block mx-auto" style="max-width: 500px">
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert', 'alert-success'], false);
endif;
if (! $this->eventTypes) :?>
    <div class="alert alert-warning alert-dismissable">
        There are no event-types in your database. You should go to <a href="<?php echo $this->url('event-types/add') ?>">/admin/event-types/add</a>
        to starting adding some.
    </div>
</div>
<?php return;
endif; ?>
<ul id="event-types-list" class="list-group" style="max-width:400px">
<?php
    foreach ($this->eventTypes as $entity) : ?>
    <li class="list-group-item py-2">
        <a href="<?php echo $this->url('event-types/edit', ['id' => $entity->getId()]) ?>"><?php echo $this->escapeHtml($entity) ?></a>
    </li>
<?php endforeach ?>
</ul>

<a href="<?php echo $this->url('event-types/add') ?>" role="button" title="add a new event-type" id="btn-add-language" class="btn btn-info mt-1">
<span aria-hidden="true" class="fas fa-plus"></span> new event-type
</a>
</div>
