DROP TABLE users;
CREATE TABLE users (id INTEGER NOT NULL, person_id SMALLINT UNSIGNED NOT NULL, role_id SMALLINT UNSIGNED NOT NULL, password VARCHAR(255) NOT NULL, 
username VARCHAR(50) DEFAULT NULL, active BOOLEAN DEFAULT '0' NOT NULL, last_login DATETIME DEFAULT NULL, created DATETIME NOT NULL, 
PRIMARY KEY(id), CONSTRAINT FK_1483A5E9217BBB47 FOREIGN KEY (person_id) REFERENCES people (id) NOT DEFERRABLE INITIALLY IMMEDIATE, 
CONSTRAINT FK_1483A5E9D60322AC FOREIGN KEY (role_id) REFERENCES roles (id) NOT DEFERRABLE INITIALLY IMMEDIATE);