<?php
/** module/Admin/view/interpreters-office/admin/court-closings/form.phtml */
$form = $this->form;
if ($this->layout()->action == 'add') :
    $action = $this->url('court-closings/add');
else:
    $action = $this->url('court-closings/edit',['id'=>$form->getObject()->getId()]);
    //$this->headScript()->appendFile($this->basePath('js/event-delete.js'));
endif;

$form->setAttribute('class', 'form-event mx-auto')
    ->setAttribute('style', 'max-width:800px')
    ->setAttribute('action',$action)
    ->setAttribute('method', 'post');

$form->prepare();
//<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() </h2>//
?>
<?php echo $this->form()->openTag($form);
    $date = $form->get('date')->getValue();
    if ($date instanceof \DateTime) {
        $form->get('date')->setValue($date->format('d/m/Y'));
    }
    if ($form->get('description_other')->getValue()) {
        $form->get('holiday')->setValue("other");
        $description_display = "block";
    } else {
        $description_display = "none";
    }
?>
<div class="form-group">
    <label for="date">date</label>
    <?php echo $this->formElement($form->get('date'));?>
</div>
<div class="form-group">
    <label for="holiday">holiday/reason for closing</label>
    <?php echo $this->formSelect($form->get('holiday')) ?>
</div>
<div style="display:<?php echo $description_display ?>" class="form-group description_other">
    <label for="description_other"></label>
    <?php echo $this->formElement($form->get('description_other'))?>
    <div id="error_description_other" style="display:none" class="alert alert-warning validation-error"></div>
</div>
<?php
    echo $this->formElement($form->get('id')),
        $this->formElement($form->get('court_closing_csrf'));
    echo $this->form()->closeTag();
?>
