<?php /**  module/Notes/view/notes/partials/notes.phtml  */
/*
renders the MOTW and/or MOTW
*/

$date_obj = new DateTime($this->config['date']);
$format = 'z-index:1000;display:%s;position:absolute;top:%s;left:%s;';
$motd_cfg = $this->config['motd'];
$pos = $motd_cfg['position'];
$size = $motd_cfg['size'];
$display = $this->display_notes && $motd_cfg['visible'] ? 'flex':'none';
$style = sprintf($format,$display,$pos['top'],$pos['left']);
$style .= "width:{$size['width']};height:{$size['height']}";

?>
<div <?php if ($this->motd): printf(' data-id="%d"',$this->motd->getId()); endif;?>id="motd" class="card" style="<?php echo $style;?>" data-date="<?php echo $date_obj->format('Y-m-d')?>">
    <div class="card-header">MOTD: <?php echo $date_obj->format('D d-M-Y')?><button type="button" class="close" data-hide="motd" aria-label="close">
    <span aria-hidden="true">&times;</span>
  </button></div>
    <div class="card-body pt-1" style="overflow:auto"?>
        <?php if ($this->assignments && isset($this->assignments['motd'])):
            ?><div class="border rounded px-2 py-1"><?php
            foreach($this->assignments['motd'] as $task => $assignment):
                echo $this->escapeHtml("$task: ");
                $victim = $this->escapeHtml($assignment['assigned']->getFirstName());
                $default = $this->escapeHtml($assignment['default']->getFirstName());
                if ($victim != $default) : ?>
                    <span style="text-decoration:line-through"><?= $default ?></span>
                    <?php
                endif;
                echo "$victim<br>";
            endforeach;
            ?></div><?php
        endif;
        echo $this->motd ? $this->motd->getContent()
        : '<span class="no-motd font-italic">No MOTD for this date.</span>';
    ?></div>
    <div class="card-footer">
      <a href="<?php
      echo $this->motd ?
        $this->url('notes/edit',['type'=>'motd','id'=> $this->motd->getId(),'date'=>$this->motd->getDate()->format('Y-m-d')])
        :  $this->url('notes/create',['type'=>'motd','date'=> $date_obj->format('Y-m-d')]);
        ?>" class="btn btn-primary btn-sm"><span class="fas fa-edit mr-1"></span>edit</a>
    </div>
</div><?php
$motw_cfg = $this->config['motw'];
$pos = $motw_cfg['position'];
$size = $motw_cfg['size'];
$display = $this->display_notes && $motw_cfg['visible'] ? 'flex':'none';
$style = sprintf($format,$display,$pos['top'],$pos['left']);
$style .= "width:{$size['width']};height:{$size['height']}";
if ($this->motw):
    $monday = $this->motw->getDate();
else :
    $dow = (int)$date_obj->format('N');
    if ($dow != 1) :
        $diff = $dow - 1;
        $monday = new DateTime("{$this->config['date']} - $diff days");
    else :
        $monday = $date_obj;
    endif;
endif;
?>
<div data-date="<?php echo $monday->format('Y-m-d')?>" id="motw" class="card" style="<?php echo $style;?>">
    <div class="card-header">MOTW: <?php echo $monday->format('D d-M-Y') ?><button type="button" class="close" data-hide="motw" aria-label="close">
    <span aria-hidden="true">&times;</span>
  </button></div>
    <div class="card-body pt-1" style="overflow:auto">
    <?php if ($this->assignments && isset($this->assignments['motw'])):
        ?><div class="border rounded px-2 py-1"><?php
        foreach($this->assignments['motw'] as $task => $assignment):
            echo $this->escapeHtml("$task: ");
            $victim = $this->escapeHtml($assignment['assigned']->getFirstName());
            $default = $this->escapeHtml($assignment['default']->getFirstName());
            if ($victim != $default) : ?>
                <span style="text-decoration:line-through"><?= $default ?></span>
                <?php
            endif;
            echo "$victim<br>";
        endforeach;
        ?></div><?php
    endif;
        echo $this->motw ? $this->motw->getContent()
        : '<span class="no-motw font-italic">No MOTW for this date.</span>';
    ?></div>
    <div class="card-footer d-flex align-items-end">
      <a href="<?php  echo $this->motw ?
        $this->url('notes/edit',['type'=>'motw','id'=> $this->motw->getId(),'date'=>$monday->format('Y-m-d')])
        :  $this->url('notes/create',['type'=>'motw','date'=>$monday->format('Y-m-d')]);
        ?>" class="btn btn-primary btn-sm"><span class="fas fa-edit mr-1"></span>edit</a>
    </div>
</div>
