<?php
/**
 *  module/Admin/view/interpreters-office/admin/people/form.phtml
 *  view script for rendering people create|update form
 */
$this->headTitle($this->title);
$this->headScript()->appendFile($this->basePath('js/judge-form.js'));
?>
<div class="center-block mx-auto" style="max-width:700px"><!-- wrapper -->
    <h2 class="my-4"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
<?php
echo $this->errorMessage($this->errorMessage);
if ($this->errorMessage): ?></div><?php return; endif;
$form = $this->form;
$action = $this->layout()->action;
if ($action == 'add') :
    $actionAttrib = $this->url('judges/add');
    $delete_button = false;
else :
    $entity = $form->getObject();
    $actionAttrib = $this->url('judges/edit', ['id' => $entity->getId()]);
    $form->setAttribute('data-judge_name', (string)$entity);
endif;
$form->setAttribute('action', $actionAttrib)
    ->setAttribute('data-redirect_url', $this->url('judges'));
$form->add([
    'name' => 'submit',
    'type' => 'Laminas\Form\Element\Submit',
    'attributes' => ['value' => 'save','class' => 'btn btn-success btn-lg'],
])->setAttribute('method', 'post')->setAttribute('class', 'form-horizontal');
$form->prepare();
$fieldset = $form->get('judge');
echo $this->form()->openTag($form);
$flavor_element = $fieldset->get('flavor');
$flavor = $flavor_element->getValue();
if (is_object($flavor)): $flavor_element->setValue($flavor->getId()); endif;?>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3"><?php echo $flavor_element->getLabel()?></label>
    <div class="col-sm-9"><?php
        if ($this->has_related_entities) :
            $flavor_element->setAttribute('disabled', 'disabled');
        endif;
        echo $this->formSelect($flavor_element),$this->formElementErrors($flavor_element);  ?>
    </div>
</div>
<?php // text inputs
$elements = ['lastname','middlename','firstname','email','office_phone',];
foreach ($elements as $elementName) :
    $element = $fieldset->get($elementName);?>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>
    </div>
</div>
    <?php
endforeach;
$courthouse = $fieldset->get('courthouse');
$courtroom = $fieldset->get('courtroom');?>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3">default location</label>
    <div class="col-sm-9">
        <div class="form-group form-row">
            <label class="col-form-label col-sm-2"><?php echo $courthouse->getLabel()?></label>
            <div class="col-sm-10"><?php echo $this->formSelect($courthouse),$this->formElementErrors($courthouse) ?>
            </div>
        </div>
        <div class="form-group form-row">
            <label class="col-form-label col-sm-2">courtroom</label>
             <div class="col-sm-10"><?php echo $this->formSelect($courtroom),$this->formElementErrors($courtroom) ?>
                <?php echo $this->formHidden($fieldset->get('defaultLocation')) ?>
             </div>
             <div class="offset-2 col-sm-10" style="margin-top: 4px">
                 <button type="button" data-toggle="modal" data-target="#add-location" title="add a new location" id="btn-add-location" class="btn btn-info btn-sm">
                      <span aria-hidden="true" class="fas fa-plus"></span> new location
                </button>
            </div>
        </div>
    </div>
</div>

<?php if (false) : // this is simpler. maybe we'll change our mind back to this.
    $defaultLocation = $fieldset->get('defaultLocation'); ?>
<div class="form-group form-row">
    <label class="control-label col-sm-3"><?php echo $defaultLocation->getLabel()?></label>
    <div class="col-sm-9">
        <div class="input-group">
            <?php echo $this->formSelect($defaultLocation) ?>
            <span class="input-group-btn">
                <button type="button" data-toggle="modal" data-target="#add-location" title="add a new location" id="btn-add-location" class="btn btn-info btn-sm">
                  <span aria-hidden="true" class="fas fa-plus"></span>
                </button>
            </span>
            <?php echo $this->formElementErrors($defaultLocation) ?>
        </div>
    </div>
</div>
<?php endif ?>
<?php
$active = $fieldset->get('active');?>
<div class="form-group form-row" style="margin-top: -15px">
    <label class="form-col-label col-sm-3" style="padding-top:2px"><?php echo $active->getLabel()?></label>
    <div class="col-sm-9 pt-1"><?php echo $this->formCheckbox($active),$this->formElementErrors($active) ?>
    </div>
</div>
<div class="form-group form-row">
    <div class="offset-3 col-sm-9">
    <?php
        echo $this->formHidden($fieldset->get('id'));
        $csrf = $form->get('csrf');
        echo $this->formHidden($csrf), $this->formElementErrors($csrf);
        echo $this->formSubmit($form->get('submit'));
    if ($this->has_related_entities === false) :
        ?><input id="btn-delete" type="button" class="btn btn-lg btn-warning" title="delete this judge from your database" value="delete" id="btn-delete"><?php
    endif;
    ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
<!-- Modal -->
<div class="modal fade" id="add-location" tabindex="-1" role="dialog" aria-labelledby="label-add-location">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="label-add-location">add a courtroom/courthouse</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button id="btn-add-location-submit" type="button" class="btn btn-primary">add location</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">cancel</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    /** @todo move this to its own file(s) */
</script>
