<?php
/**
 * module/Admin/view/interpreters-office/admin/judges/index.phtml
 * view script for judges admin main page
 */
$this->headScript()->appendFile($this->basePath('js/judges-index.js'));
$this->headTitle($this->title);?>
<div class="center-block mx-auto" style="max-width:600px"><!-- wrapper -->
    <h2 class="navigation mb-3 mt-4"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?>
    </h2>
    <div class="form-inline pt-2 mb-1">
         <label class="pr-1" for="judge-filter">inactive judges: </label>
         <select id="judge-filter" class="form-control form-control-sm custom-select">
             <option value="0">hide</option>
             <option value="1">show</option>
        </select>
    </div>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
endif;

if (! $this->judges) : ?>
    <div class="alert alert-warning">There are no judges in your database. Go to <a href="<?php echo $this->url('judges/add')?>">judges/add</a> to start adding some.</div>
</div><!-- /wrapper -->
    <?php
    return;
endif;
?>
<div id="accordion">
<?php
$flavors = array_keys($this->judges);
foreach ($flavors as $flavor) :
    ?>
    <div class="card">
        <div class="card-header" id="heading-<?php echo $flavor ?>">
            <a role="button" class="btn btn-link" data-toggle="collapse" data-target="#<?php echo $flavor ?>" aria-expanded="<?php echo $flavor == $flavors[0] ? "true" : "false"?>" aria-controls="<?php echo $flavor ?>">
                <h2>
                <?php echo $flavor ?>
                </h2>
            </a>
        </div>
        <div id="<?php echo $flavor ?>" class="collapse<?php if ($flavor == $flavors[0]) :
            ?> show<?php
                 endif;?>" aria-labelledby="heading-<?php echo $flavor ?>" data-parent="#accordion">
            <div class="card-body px-auto">
            <table class="table mx-auto" style="max-width:500px">
                <tbody>
                <?php
                foreach ($this->judges[$flavor] as $judge) :
                    $location = '';
                    if ($judge['location']) :
                        $location .= $judge['location'];
                        if ($judge['parent_location']) :
                            $location .= ', '. $judge['parent_location'];
                        endif;
                    endif; ?>
                <tr <?php if (! $judge['active']) :
                    ?> class="inactive"<?php
                    endif;?>>
                    <td><?php
                    $name = sprintf("%s, %s %s", $judge['lastname'], $judge['firstname'], $judge['middlename']);
                    printf('<a data-toggle="tooltip" title="view judge details" href="%s">%s</a>', $this->url('judges/view', ['id' => $judge['id']]), $name);
                    ?></td>
                    <td style="color:#515457" class="pl-0"><?php echo $location ?></td>
                    <td class="text-md-right">
                        <span style="opacity:.75" class="align-self-center fas fa-<?php echo $judge['active'] ? "check text-success" : "times text-danger"?>"></span>
                    </td>
                    <td class="px-0"><a data-toggle="tooltip" title="edit this database record" href="<?php echo $this->url('judges/edit', ['id' => $judge['id']])?>"><span style="opacity:.75" class="align-self-center fas fa-edit"></span></a></td>
                </tr>
                <?php endforeach;?>
                </tbody>
            </table>
        </div>
        </div>
    </div>
    <?php
endforeach;
?>
</div><!-- /accordion -->
<a href="<?php echo $this->url('judges/add') ?>" role="button" title="add a new judge" id="btn-add-judge" class="btn btn-info mt-2">
<span aria-hidden="true" class="fas fa-plus"></span> new judge
</a>
</div><!-- /wrapper -->
