<?php
/**
 * module/Admin/view/interpreters-office/admin/locations/index.phtml
 * view script for displaying locations. work in progress.
 */
$this->headTitle($this->title);
$this->headScript()->appendFile($this->basePath('js/locations-index.js'));
?>
<div class="center-block mx-auto" style="max-width:600px">
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
endif;
?>
<div class="list-group">
<p>Choose a type to display</p>
<ul id="locations-list" class="list-group">
<?php foreach ($this->locationTypes as $t) : ?>
<li class="list-group-item"><span class="badge badge-info"><?php echo $t['total']?></span> <?php
    $url = $this->url('locations/type', ['id' => $t['id']]);
    ?><a href="<?php echo $url?>"><?php echo $this->escapeHtml($t['type']) ?></a>
  </li>
<?php endforeach ?>
</ul>
</div>
