<?php
/** module/Admin/view/email/assignment-confirmation-notice.phtml */

$address = $this->to;
if (!empty($address['name'])):
    $salutation = "Dear {$address['name']}:";
else:
    $salutation = 'Hello,';
endif;
?>
<p><?php echo $salutation ?></p>
<p>
    This is to confirm your assignment as interpreter for the following event:
</p>
<?php
echo $this->partial('interpreters-office/email/partials/event-details.phtml',
    ['entity'=>$this->entity]);
?>
<?php if ($this->notes):?>
<p>Additional notes:</p>
<p style="margin-left:2em"><?php echo $this->notes ?></p>
<?php endif ?>
<p>
    Please feel free to contact us with any questions.
</p>
<p>Very truly yours,</p>

<p>The Interpreters Office</p>
