<?php

$address = $this->to;
if (!empty($address['name'])):
    $salutation = "Dear {$address['name']}:";
else:
    $salutation = 'Hello,';
endif;
?>
<p><?php echo $salutation ?></p>
<p>
    We are writing to see if you are available to accept the following
    interpreting assignment:
</p>
<?php
echo $this->partial('interpreters-office/email/partials/event-details.phtml',
    ['entity'=>$this->entity]);
?>
<p>
    If so, please contact us at your earliest convenience.
</p>
<p>Very truly yours,</p>

<p>The Interpreters Office</p>
