<?php /** module/Admin/view/email/assignment-availability-notice.phtml */

$address = $this->to;
if (!empty($address['name'])):
    $salutation = "Dear {$address['name']}:";
else:
    $salutation = 'Hello,';
endif;
?>
<p><?php echo $salutation ?></p>
<p>
    We are writing to see if you are available to accept the following
    interpreting assignment:
</p>
<?php
echo $this->partial('interpreters-office/email/partials/event-details.phtml',
    ['entity'=>$this->entity, 'escaped'=> $this->escaped]);
?>
<p>
    If so, please contact us at your earliest convenience.
</p>
<?php if ($this->notes):?>
<p>Additional notes:</p>
<p style="margin-left:2em"><?php echo $this->escapeHtml($this->notes) ?></p>
<?php endif ?>
<p>Very truly yours,</p>

<p>The Interpreters Office</p>
