<?php
/** module/Admin/view/email/assignment-confirmation-notice.phtml */

$address = $this->to;
if (!empty($address['name'])):
    $salutation = "Dear {$address['name']}:";
else:
    $salutation = 'Hello,';
endif;
?>
<p><?php echo $salutation ?></p>
<?php if (!$this->entity):?>
<p><?php echo $this->notes ?></p>
<?php else: ?>
<p>
    This is to confirm your assignment as interpreter for the event shown below.
</p>
<?php if ($this->notes):?>
<p>Please note:</p>
<div style="border:1px solid orange;padding:1em"><?php echo $this->notes ?></div>
<?php endif ?>
<?php
echo $this->partial('interpreters-office/email/partials/event-details.phtml',
    ['entity'=>$this->entity, 'escaped' => $this->escaped]);
?>

<?php endif ?>
<p>
    Please feel free to contact us with any questions.
</p>
<p>Very truly yours,</p>

<p>The Interpreters Office</p>
