<?php /** module/Admin/view/email/assignment-availability-notice.phtml */

$address = $this->to;
if (!empty($address['name'])):
    $salutation = "Dear {$address['name']}:";
else:
    $salutation = 'Hello,';
endif;
?>
<p><?php echo $salutation ?></p>
<p>
    We are writing to see if you are available to accept the interpreting assignment shown below.
</p>
<?php if ($this->notes):?>
<p>Please note:</p>
<div style="border:1px solid orange;padding:1em"><?php echo $this->notes ?></div>
<?php endif ?>
<?php
echo $this->partial('interpreters-office/email/partials/event-details.phtml',
    ['entity'=>$this->entity, 'escaped'=> $this->escaped]);
?>
<p>
    If so, please contact us at your earliest convenience.
</p>
<p>Very truly yours,</p>

<p>The Interpreters Office</p>
