<?php
/**
 * View script for email sent to Interpreters Office when Spanish interpreter
 * auto-cancel is triggered in the Requests module. This happens when the
 * request-submitter either (1) cancels outright or (2) reschedules a request
 * across an am/pm boundary or (3) (rarely occuring) changes the language from
 * Spanish to something else.
 *
 * This script is to be used when our configuration has automatic interpreter
 * notification turned OFF.The underlying idea is that in many cases human
 * judgment should decide whether it makes sense to send email to the
 * interpreter.
 */

/* example configuration
{
  "cancel": {
    "in-court.spanish.delete-scheduled-event": true,
    "in-court.spanish.notify-assigned-interpreters": false,
    "out-of-court.spanish.delete-scheduled-event": true,
    "out-of-court.spanish.notify-assigned-interpreters": true,
    "out-of-court.non-spanish.delete-scheduled-event": true,
    "out-of-court.non-spanish.notify-assigned-interpreters": true
  },
  "change-date": {
    "all-events.all-languages.update-scheduled-event": true,
    "all-events.all-languages.remove-interpreters": true,
    "all-events.all-languages.notify-assigned-interpreters": true
  },
  "change-x-am-pm": {
    "all-events.all-languages.update-scheduled-event": true,
    "all-events.all-languages.notify-assigned-interpreters": true,
    "all-events.all-languages.remove-interpreters": true
  },
  "change-within-am-pm": {
    "in-court.spanish.update-scheduled-event": true,
    "in-court.spanish.notify-assigned-interpreters": true,
    "in-court.spanish.remove-interpreters": false,
    "in-court.non-spanish.update-scheduled-event": true,
    "in-court.non-spanish.notify-assigned-interpreters": true,
    "in-court.non-spanish.remove-interpreters": false,
    "out-of-court.spanish.update-scheduled-event": true,
    "out-of-court.spanish.notify-assigned-interpreters": true,
    "out-of-court.spanish.remove-interpreters": false,
    "out-of-court.non-spanish.update-scheduled-event": true,
    "out-of-court.non-spanish.notify-assigned-interpreters": true,
    "out-of-court.non-spanish.remove-interpreters": false
  },
  "change-language": {
    "all-events.all-languages.update-scheduled-event": true,
    "all-events.all-languages.notify-assigned-interpreters": true,
    "all-events.all-languages.remove-interpreters": true
  },
  "update-other-attributes": {
    "all-events.all-languages.update-scheduled-event": true
  }
}
 */
if ($this->interpreters):
    $plural =  count($this->interpreters) > 1;
endif;
$this->entity = [
    'date' =>  $this->request->getDate(),
    'time' =>  $this->request->getTime(),
    'language' => (string)$this->request->getLanguage(),
    'eventType' =>  (string)$this->request->getEventType(),
    'location' =>  (string)$this->request->getLocation(),
    'docket'  => $this->request->getDocket(),
    'comments' => $this->request->getComments(),
    'judge' =>  (string)$this->request->getJudge(),
    'extraData' => $this->request->getExtraData(),
    'defendants' => $this->request->getDefendants()->toArray(),
];
if ($this->user_event == 'cancel') :
    $verb = '<strong>cancelled</strong>';
    $template = 'event-details';
else:
    $verb = 'updated';
    $template = 'event-diff';
endif;
?>
<p>
This automated message is to inform you that user <?php echo "{$this->user->firstname} {$this->user->lastname}"?>
has just <?php echo $verb ?> the following request for interpreting services. As a result, the corresponding
event on the schedule was automatically <?php echo $this->user_event == 'cancel' ? "removed" : "updated" ?>.
</p>
<?php if ($this->interpreters):?>
<p>
Also, please note that the following <?php echo $plural ? 'interpreters were ':'interpreter was'  ?>
removed from the assignment, and automatic email-notification to interpreters in such cases is disabled.
Therefore, it's up to you to contact  <?php echo $plural ? 'these interpreters':'this interpreter' ?> if
you wish to do so:
</p>
<p style="padding-left:2em;">
    <?php foreach ($this->interpreters as $i):
        echo "{$i->getFirstName()} {$i->getLastname()} ",$this->escapeHtml('<'.$i->getEmail().'>'),'<br>';
        ?>
    <?php endforeach;?>
</p>
<?php endif;

echo $this->partial("interpreters-office/email/partials/{$template}.phtml",
    ['entity'=>$this->entity]);
?>
