<?php
/**  module/Admin/view/email/blank-page.phtml  */
$address = $this->to;
if (!empty($address['name'])):
    $salutation = "Dear {$address['name']}:";
else:
    $salutation = 'Hello,';
endif;
?>
<p><?php echo $salutation ?></p>
<p>
<?php echo //nl2br()
    $this->notes ?>
</p>
<?php if ($this->entity): ?>
<p>Event details:</p>
<?php
    echo $this->partial('interpreters-office/email/partials/event-details.phtml',
        ['entity'=>$this->entity]);
endif;
?>
<p>Very truly yours,</p>

<p>The Interpreters Office</p>
