<?php
/**
 *
 * view script for
 * (1) email sent automatically when a request is updated or
 * (2) email sent manually through schedule/admin interface
 *
 *
 */

if (is_object($this->entity)) {
    $data = $this->entity = [
        'date' =>  $this->entity->getDate(),
        'time' =>  $this->entity->getTime(),
        'language' => (string)$this->entity->getLanguage(),
        'eventType' =>  (string)$this->entity->getEventType(),
        'location' =>  (string)$this->entity->getLocation(),
        'docket'  => $this->entity->getDocket(),
        //'comments' => $this->entity->getComments(),
        'judge' =>  (string)$this->entity->getJudge(),
        'extraData' => $this->entity instanceof InterpretersOffice\Requests\Entity\Request ? $this->entity->getExtraData(): null,
        'defendants' => $this->entity->getDefendants()->toArray(),
    ];
    $this->entity = $data;
    //
    // if (key_exists('comments',$this->before)) {
    //     unset($this->before['comments']);
    // 
}
if (is_object($this->interpreter) && $this->interpreter instanceof \InterpretersOffice\Entity\Interpreter) :
    $salutation = "Dear {$this->interpreter->getFullname()}:";
else:
    //$salutation = print_r($this->to,true);
    $address = $this->to;
    if (isset($address['name']) && $address['name'] != $address['email']):
        $salutation = "Dear {$address['name']}:";
    else:
        $salutation = 'Hello,';
    endif;
endif;
?>
<p><?=$salutation?></p>
<p>This is to advise you that the following event to which you
    are assigned as interpreter has been modified, as indicated below.
</p>
<?php
if ($this->before):
    echo $this->partial('interpreters-office/email/partials/event-diff.phtml',
    ['entity'=>$this->entity, 'before' => $this->before, 'with_comments'=>false]);
else:
    echo $this->partial('interpreters-office/email/partials/event-details.phtml',
    ['entity'=>$this->entity,  'with_comments'=>false,'escaped' => $this->escaped ]);
endif;    ?>
<p style="margin-top:1em">
If you have any questions, please contact the Interpreters promptly.
</p>
