<?php
/** module/Admin/view/email/index.phtml viewscript for batch-email */
$this->headTitle('admin | email');
$this->headScript()
    ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
    ->appendFile($this->basePath('js/admin/batch-email.js'));
?>
<h2 class="mx-auto text-center"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>

<div style="max-width:800px" class="mx-auto p-2">
    <div class="progress mb-2 mx-auto">
      <div id="progress" class="progress-bar progress-bar-striped bg-info" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
<?php echo $this->errorMessage() ?>
<form id="email-form" class="carousel" data-interval="false" action="index.html" method="post" <?php
    if (isset($this->site_config['contact']['organization_name'])) :
        printf('data-organization_name="%s"',$this->site_config['contact']['organization_name']);
    endif;
?>>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="form-row form-group">
                <label for="recipient_list" class="col-sm-3 col-form-label float-md-right">
                    recipient list
                </label>
                <div class="col-sm-9">
                    <select class="custom-select" name="recipient_list" id="recipient_list">
                        <option value=""></option>
                    <?php foreach ($this->recipient_list_options as $opt):?>
                        <option label="<?=$opt?>" value="<?=$opt?>"><?=$opt?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </div>
            <div class="form-row form-group">
                <label for="subject" class="col-sm-3 col-form-label float-md-right">
                    subject
                </label>
                <div class="col-sm-9">
                    <input type="text" id="subject" class="form-control" name="subject" value="">
                </div>
            </div>
            <div class="form-row form-group">
                <label for="salutation" class="col-sm-3 col-form-label float-md-right">
                    salutation
                </label>
                <div class="col-sm-9">
                    <select class="custom-select" id="salutation" name="salutation">
                        <option value="personalized">Dear <?php echo $this->escapeHtml("<first name> <surname>:")?></option>
                        <option value="other">I'll write my own</option>
                    </select>
                </div>
            </div>
            <div class="form-row form-group">
                <label for="body" class="col-sm-3 col-form-label float-md-right">
                    message
                </label>
                <div class="col-sm-9"><textarea placeholder="the body of your message" id="body" name="body" rows="8" class="form-control"></textarea>
                <span class="text-muted">You can use <a target="__blank" href="https://www.markdownguide.org/basic-syntax">Markdown</a> for formatting</span>
                </div>
            </div>
            <div class="form-row form-group">
                <div class="col-sm-9 offset-sm-3">
                    <button type="button" class="btn btn-success" name="preview">preview</button>
                </div>
            </div>
        </div>
        <div class="carousel-item border px-2">
            <div class="row pt-2">
                <div class="col-sm-3">
                    <div class="float-md-right">to</div>
                </div>
                <div id="recipient-preview" class="col-sm-9"></div>
            </div>
            <div class="row pt-2">
                <div class="col-sm-3">
                    <div class="float-md-right">subject</div>
                </div>
                <div id="subject-preview" class="col-sm-9"></div>
            </div>
            <div class="row pt-2">
                <div class="col-sm-3">
                    <div class="float-md-right">salutation</div>
                </div>
                <div id="salutation-preview" class="col-sm-9"></div>
            </div>
            <div class="row pt-2">
                <div class="col-sm-3 float-md-right">
                    <div class=" pt-2 float-md-right">message text</div>
                </div>
                <div id="message-preview" class="col-sm-8 pt-2 border border-default rounded">
                </div>
            </div>
            <div class="row pt-2">
                <div class="col-sm-9 offset-sm-3">
                    <button type="button" class="btn btn-info" name="revise">revise</button>
                    <button type="button" class="btn btn-success" name="send">send</button>
                </div>
            </div>
        </div>
    </div>
</form>
</div>
