<?php $this->headTitle('admin | email') ?>
<div class="row">
    <div class="col offset-md-3">
        <h2 class="mb-3"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
        <p><a href="<?=$this->url('email/batch')?>">send broadcast email</a></p>
        <p><a href="<?=$this->url('interpreters/availability_list/list')?>">edit availability-solicitation list</a></p>
    </div>
</div>
