<?php
/**
 * view script/email template for automatically sending update notice to interpreters
 * when a request undergoes certain changes
 *
 * idea:  a button in the message linked to a script at sdnyinterpreters.org,
 * with a token in the url that triggers an email on their behalf and says thanks
 */
$address = $this->to;
if (!empty($address['name'])):
    $salutation = "Dear {$address['name']}:";
else:
    $salutation = 'Hello,';
endif;
?>
<p><?php echo $salutation ?></p>
<p>This is to advise you that the following event to which you were assigned
<strong>has been cancelled</strong>.</p>
<p style="font-size:115%;"><em>Please reply to the Interpreters Office at your
    earliest convenience to acknowledge this notice.</em></p>
<?php
echo $this->partial('interpreters-office/email/partials/event-details.phtml',
    ['entity'=>$entity, ]);
?>
<?php if ($this->notes):?>
<p>Additional notes:</p>
<p style="margin-left:2em"><?php echo $this->notes ?></p>
<?php endif ?>
<p style="margin-top:2em">Very truly yours,</p>

<p>The Interpreters Office</p>
