<?php
/**
 * module/Admin/view/email/schedule-update-notice.phtml
 *
 *
 *
 */

if (is_object($this->entity)) {
    $data = $this->entity = [
        'date' =>  $this->entity->getDate(),
        'time' =>  $this->entity->getTime(),
        'language' => (string)$this->entity->getLanguage(),
        'eventType' =>  (string)$this->entity->getEventType(),
        'location' =>  (string)$this->entity->getLocation(),
        'docket'  => $this->entity->getDocket(),
        'comments' => $this->entity->getComments(),
        'judge' =>  (string)$this->entity->getJudge(),
        'extraData' => $this->entity instanceof InterpretersOffice\Requests\Entity\Request
            ? $this->entity->getExtraData(): null,
        'defendants' => $this->entity->getDefendants()->toArray(),
        //'is_default_location' => 'whatever',
    ];
    $this->entity = $data;
}
?>
<p>Hello,</p>
<p>This is to advise you that the following interpreter request
    has just been updated by <?php echo "{$this->user->firstname} {$this->user->lastname} ({$this->user->email})" ?>
    and the corresponding event on the schedule will be updated as needed.
</p>
<?php if (! $this->interpreters): ?>
<p>
    As of now, no interpreters are assigned.
</p>
<?php else:
    $interpreter_names = '<ul style="margin-left:2em"><li>' . implode("</li><li>",array_map(
        function($i){ return $i->getFullName();},$this->interpreters
    )) . '</li></ul>';
    $what = [];
    if ($this->remove_interpreters):
        $what[] = 'removing'; endif;
    if ($this->notify_interpreters):
        $what[] = 'emailing notification to';
    endif;
    if ($what) : $actions = implode(' and ',$what)?>
        <p>We are <?php echo $actions ?> the following interpreter(s).
            <?php if (count($what )< 2): ?> No further action is being taken automatically.<?php endif ?></p>
        <?php
    else:
        ?>
        <p>No further action is being taken automatically. As of now, the interpreters assigned to this event are:</p>
        <?php
    endif;
?>
        <?php echo $interpreter_names ?>
<?php endif; ?>
<?php // echo count($this->interpreters)," interpreters<br>";?>
<?php // echo "remove interpreters: ",  ($this->remove_interpreters === true ? "true":"false"), "<br>";?>
<?php // echo "notify interpreters: ",  ($this->notify_interpreters === true ? "true":"false"), "<br>";?>
<?php
if ($this->before):
    //echo "DEBUG: we are rendering partials/event-diff because of \$this->before";
    echo $this->partial('interpreters-office/email/partials/event-diff.phtml',
    ['entity'=>$this->entity, 'before' => $this->before, 'with_comments'=>true]);
else:
    echo $this->partial('interpreters-office/email/partials/event-details.phtml',
    ['entity'=>$this->entity,  'with_comments'=>true,'escaped' => $this->escaped ]);
endif;    ?>
