<div class="modal" id="modal-confirm-cancel" tabindex="-1" role="dialog" aria-labelledby="modal-confirmation-label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-confirmation-label">please confirm cancellation</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id="confirmation-message"></p>
        <p>(Note that if you have another date and time you can <a class="reschedule" href="#">update</a> instead.)</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">no</button>
        <button type="button" id="btn-confirm-cancellation" class="btn btn-primary">yes</button>
      </div>
    </div>
  </div>
</div>
