<?php
    $this->headTitle('requests | '.$this->layout()->action);
    $this->headLink()
            ->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
    $this->headScript()
            ->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.js'))
            ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
            ->appendFile($this->basePath('js/form-utilities.js'))
            ->appendFile($this->basePath('js/requests/form.js'));
    $this->headStyle()->captureStart()?>
        span.fas:hover { cursor : pointer; }
        #deft-results-slideout {
            position : absolute;
            z-index: 100;
            display : none;
            left : 100px;
            top : 120px;
            min-height : 200px;
        }
    <?php $this->headStyle()->captureEnd();
    $messenger = $this->flashMessenger();
    if ($messenger->hasErrorMessages()) :
        echo $messenger->render('error', ['alert','alert-warning',], false);
    endif;
    $form = $this->form;
    $action = $this->basePath('requests/'.$this->layout()->action);
    if ($this->id) {  $action .= "/$id"; }
    $form->setAttribute('action',$action);
    $form->prepare();
    $fieldset = $this->form->get('request');
    // convert \DateTime to string
    foreach (['date'=> 'm/d/Y','time' => 'g:i a'] as $field => $format):
        $value = $fieldset->get($field)->getValue();
        if (is_object($value)):
            $fieldset->get($field)->setValue($value->format($format));
        endif;
    endforeach;
    foreach (['judge','eventType','location'] as $field) {
      $value = $fieldset->get($field)->getValue();
      if (is_object($value)):
          $fieldset->get($field)->setValue($value->getId());
      endif;

    }
    // try to set default judge and courtroom, if applicable
    $user = $this->layout()->user;
    if ($user->judge_ids && 1 == count($user->judge_ids)) :
        $judge = $user->judge_ids[0];
        $fieldset->get('judge')->setValue($judge);
        if ($fieldset->get('location')->getValue() !== null) :
            $opts = $fieldset->get('judge')->getValueOptions();
            foreach ($opts as $opt) :
                if ($opt['value'] == $judge) :
                    $fieldset->get('location')
                    ->setValue($opt['attributes']['data-default_location']);
                    break;
                endif;
            endforeach;
        endif;
        ?>
        <?php
    endif;
?>
<div class="center-block mx-auto" style="max-width:800px">
    <h2 class="navigation mb-3"><?php echo $this->navigation('Zend\Navigation\RequestsBreadcrumbs')->breadcrumbs() ?></h2>
    <?php echo $this->errorMessage($this->errorMessage);  ?><?php
    if ($this->errorMessage) : ?></div><?php  return;  endif; ?>

    <div id="deft-results-slideout" class="bg-light border border-info shadow rounded p-3" >
        <h4 class="text-muted">search results <button type="button" class="float-right close" aria-label="close"><span aria-hidden="true">&times;</span></button></h4>
        <div id="deft-results">
        </div>
        <div class="text-center">
            <button id="btn-show-deft-form" title="display a form for entering a name that is not found in the database" class="btn btn-sm btn-primary mt-2 text-center border rounded">name not found?</button>
        </div>
        <form style="display:none" id="form-add-deft" action="javascript:void()" method="post">
            <h4 class="border border-top p-2 mt-2">add a name</h4>
            <div class="form-group">
                <label class="" for="surname">surname(s)</label>
                <input type="text" class="form-control" name="surnames" value="" id="surnames" required>
            </div>
            <div class="form-group">
                <label for="given_names">given name(s)</label>
                <input type="text" class="form-control" name="given_names" value="" id="given_names" required>
            </div>
            <div class="form-group">
                <button type="button" id="btn-add-new" class="btn btn-success">add</button>
            </div>
        </form>
    </div>
    <?php  echo  $this->form()->openTag($form);  ?>
    <div class="form-group form-row">
        <div id="error_duplicate" class="col-sm-7 offset-sm-3 alert alert-warning validation-error" style="display:none">
        </div>
    </div>
    <div class="form-group form-row">
        <div id="error_insufficient_notice" class="col-sm-7 offset-sm-3 alert alert-warning validation-error" style="display:none">
        </div>
        <label for="date" class="col-form-label col-sm-3 pr-1">date</label>
        <div class="col-sm-3"><?php echo $this->formElement($fieldset->get('date')),
            $this->formElementErrors($fieldset->get('date'));?>
        </div>
        <label for="time" class="col-form-label col-sm-1">time</label>
        <div class="col-sm-3"><?php echo $this->formElement($fieldset->get('time')),
            $this->formElementErrors($fieldset->get('time'));?>
        </div>
    </div>
    <?php
        foreach (['language','judge','eventType','location','docket'] as $name) :
            $element = $fieldset->get($name);
    ?>
    <div class="form-group form-row">
        <label for="<?php echo $element->getAttribute('id')?>" class="col-sm-3 col-form-label pr-1">
            <?php echo $element->getLabel()?></label>
        <div class="col-sm-7"><?php echo $this->formElement($element),
            $this->formElementErrors($element);?></div>
    </div>
    <?php endforeach ?>
    <div class="form-group form-row">
        <label for="defendant-search" class="col-form-label col-sm-3 pr-1">defendant(s)</label>
        <div class="col-sm-7">
            <div id="help-defendant-search" class="alert alert-info alert-dismissible" style="display:none">
                <button type="button" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <p>
                    Type two or more letters of the last name, optionally followed by a comma and one or more letters of the
                    first name. Any matching names will be displayed automatically. Use more letters to narrow your search
                    results.
                </p>
                <p>
                    If you see the name you're looking for, select it (with your mouse or keyboard). If not, click
                    the search icon (to the right of the above text field) to display full search results and
                    a form for adding whatever name you cannot find in the database.
                </p>
            </div>
            <div class="input-group">
                <?php echo $this->formElement($fieldset->get('defendant-search'))?>
                <div class="input-group-append">
                    <button id="btn-deft-search" title="search database" class="input-group-text fas fa-search pt-2 bg-primary text-white"></button>
                    <span id="btn-help-deft-search" title="get help" class="input-group-text fas fa-question pt-2 text-muted border"></span>
                </div>
            </div>
            <ul id="defendants" class="list-group mt-2"><?php
                $defendants = $form->getObject()->getDefendants();
                if ($defendants->count()) :
                    foreach ($defendants as $deft):
                        echo $this->partial('partials/defendant',[
                            'namespace' => 'request', 'id' => $deft->getId(), 'name' => (string)$deft
                        ]);
                    endforeach;
                endif;
                if ($form->getObject()->getExtraDefendantNames()):
                    $pseudo_id = time();
                    foreach($form->getObject()->getExtraDefendantNames() as $name):
                        echo $this->partial('partials/defendant',
                            [
                                'namespace' => 'request', 'id'=> ++$pseudo_id,
                                'name'=>$name,'xtra_defendants' => true,
                            ]);
                    endforeach;
                endif;
            ?></ul>
        </div>
    </div>
    <div class="form-group form-row">
        <label for="comments" class="col-form-label col-sm-3 pr-1">notes</label>
        <div class="col-sm-7"><?php echo $this->formElement($fieldset->get('comments')),
            $this->formElementErrors($fieldset->get('comments'));?>
        </div>
    </div>
    <div class="form-group form-row">
        <div class="col-sm-7 offset-sm-3">
            <?php echo $this->formElement($fieldset->get('id')),
             $this->formElement($form->get('csrf')),
             $this->formElementErrors($form->get('csrf'))?>
            <button id="btn-save" type="submit" class="btn btn-success">save</button>
        </div>
    </div>
    </form>
</div><!-- /wrapper -->
<script>
if (document.referrer.indexOf("/requests/list") !== -1) {
    document.querySelector("h2.navigation a").href = document.referrer;
}
</script>
