<?php $this->headTitle('requests') ?>

<h2>Interpreter Scheduling</h2>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasErrorMessages()) :
    echo $messenger->render('error', ['alert','alert-warning',], false);
endif;
?>
<div class="row">
    <div class="col-md-5 offset-md-1">
            <p class="mt-3"><a class="btn btn-primary btn-block btn-lg" role="button" href="<?php echo $this->url('requests/list')?>">list</a>
                <span class="text-muted">view/manage your past requests for interpreters</span>
            </p>
            <p class="text-muted"><a  class="btn btn-primary btn-block btn-lg" role="button" href="<?php echo $this->url('requests/create')?>">create</a>
                <span class="text-muted">schedule an interpreter for a future event</span>
            </p>
            <p class="text-muted"><a  class="btn btn-primary btn-block btn-lg" role="button" href="<?php echo $this->url('requests/search')?>">search</a>
                <span class="text-muted">find previous requests</span>
            </p>
            <p class=""><a  class="btn btn-primary btn-block btn-lg" role="button" href="<?php echo $this->url('account/edit-profile')?>">profile</a>
            <span class="text-muted">edit your user account details</span>
            </p>
            <p class=""><a  class="btn btn-primary btn-block btn-lg" role="button" href="<?php echo $this->url('requests/help')?>">help</a>
                <span class="text-muted">read the help documentation</span>
            </p>
            <p class=""><a  class="btn btn-primary btn-block btn-lg" role="button" href="<?php echo $this->url('contact')?>">contact</a>
            <span class="text-muted">contact the Interpreters Office</span>
            </p>
    </div>
    <div class="col-md-4 pt-2">
        <?php echo number_format($this->count) ?> total requests posted to date.
    </div>
</div>
