<?php
/** module/Requests/view/interpreters-office/requests/index/list.phtml
*
*   view script for displaying user's interpreter requests
*/
$this->headScript()
    ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
    ->appendFile($this->basePath('js/requests/list.js'))
    ;
$this->headTitle('requests | list') ?>
<div id="content">
<h2><?php echo $this->navigation('Zend\Navigation\RequestsBreadcrumbs')->breadcrumbs() ?></h2>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
endif;
?>
<?php echo $this->errorMessage($this->errorMessage);  ?>
<div class="alert alert-success alert-dismissible border shadow-sm" id="success-div" style="display:none; max-width:600px">
    <div id="success-message"></div>
    <button type="button" class="close" data-dismiss="alert" aria-label="close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<?php
if ($this->paginator && $this->paginator->getTotalItemCount()):
    ?><p>
        <?php echo $this->paginationControl($this->paginator, null, 'partials/pagination_head');?>
    </p>
<table id="requests-table" data-deadline="<?php echo $this->deadline->format('Y-m-d H:i:s') ?>" data-csrf="<?php echo $this->csrf ?>" class="table table-sm">
    <caption class="sr-only">list of interpreter requests</caption>
    <thead></thead>
    <tbody>
    <?php
        foreach ($this->paginator as $r):
            $r = array_merge($r,$r[0]); unset($r[0]);
            //printf("<pre>%s</pre>",print_r($r,true)); break;
            $docket = $r['docket'] ? substr($r['docket'],2) : '';
            $xtra = $r['extraData'];
            $xtra_defts = '';
            if ($xtra) :
                $data = json_decode($xtra,\JSON_OBJECT_AS_ARRAY);
                if (isset($data['defendants'])):
                    $xtra_defts = implode('<br>', $data['defendants']);
                endif;
            endif;
        ?><tr data-request_id="<?php echo $r['id']?>">
            <td class="date"><span class="avoidwrap"><?php echo $r['date']->format('d-M-Y')?></span></td>
            <td class="d-md-none d-lg-table-cell time"><?php echo $r['time']->format('g:i a')?></td>
            <td class="language"><?php echo $this->escapeHtml($r['language']) ?></td>
            <td class="event-type"><?php echo $this->escapeHtml($r['type'])?></td>
            <td><?php echo $this->escapeHtml($r['location']) ?></td>
            <td class="d-md-none d-lg-table-cell"><?php echo $this->escapeHtml($docket) ?></td>
            <td><?php echo $r['judge']?></td>
            <td><?php echo $this->defendants($r['id']),$xtra_defts?></td>
            <td class="dropdown">
                <a class="btn dropdown-toggle text-primary" role="button" data-toggle="dropdown"  id="request-dropdown-<?php echo $r['id']?>" aria-haspopup="true" aria-expanded="false">
                    <span class="fas fa-bars"></span>
                    <span class="sr-only">menu</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="request-dropdown-<?php echo $r['id']?>">
                  <a title="display detailed view of this request" class="dropdown-item request-details text-primary" href="<?php echo $this->url('requests/view',['id'=>$r['id']])?>">view details</a>
                  <div class="dropdown-divider"></div>
                  <a title="schedule an interpreter for another event in this same case" class="dropdown-item request-repeat text-primary" href="<?php echo $this->url('requests/create',['id'=>$r['id']])?>">repeat</a>
                  <div class="dropdown-divider"></div>
                  <a title="modify this request" class="dropdown-item request-update text-muted disabled" href="<?php echo $this->url('requests/update',['id'=>$r['id']])?>"><span class="text-muted">edit</span></a>
                  <div class="dropdown-divider"></div>
                  <a title="cancel this request" class="dropdown-item request-cancel text-muted disabled" href="<?php echo $this->url('requests/cancel',['id'=>$r['id']])?>"><span class="text-muted">cancel</span></a>
                </div>
            </td>
        </tr><?php
        endforeach;
    ?>
    </tbody>
</table>
<?php echo $this->paginationControl(
    $this->paginator,'sliding', 'partials/pagination_control',['route' => 'requests/list']
);?>
<?php else: $url =  $this->url('requests/create');?>
<p class="alert alert-warning">You have no electronically submitted interpreter requests
in the database. To create one please go to <a href="<?php echo $url?>"><?php echo $url?></a>.</p>
<?php endif;?>
</div>
<?php echo $this->render('confirm-cancel')?>
