<?php     $this->headTitle('requests | '.$this->layout()->action);?>
<h2 class="text-center py-2 navigation"><?php echo $this->navigation('Zend\Navigation\RequestsBreadcrumbs')->breadcrumbs() ?></h2>
<?php echo $this->errorMessage($this->errorMessage);
    if ($this->errorMessage): return; endif;
?>
<?php
if (! $this->data):
?>
<div class="alert alert-warning shadow-sm border">
    The request was not found in the database. It may have been deleted, or you
    may have a wrong record id number in the url.
</div>
<?php
return; endif;
$this->headScript()
    ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
    ->appendFile($this->basePath('js/requests/view.js'));

$r = $this->data; // we are lazy
$scheduled_datetime = new \DateTime(sprintf('%s %s',$r->getDate()->format("Y-m-d"), $r->getTime()->format('H:i')));
$editable = ($scheduled_datetime > $this->deadline) && !($r->getEvent() && $r->getEvent()->getDeleted());
//var_dump($r['event_deleted']);var_dump($editable);
echo $this->partial('partials/request-details',['request'=>$r, 'deadline'=> $this->deadline]);
?>
    <div class="col-md-12 text-center pt-2"><?php
        if ($editable):
            ?>
            <a role="button" title="modify this request" class="btn btn-success request-update" href="<?php echo $this->url('requests/update',['id'=>$r->getId()])?>">update</a>
            <a data-csrf="<?php echo $this->csrf ?>" role="button" id="btn-cancel" title="withdraw this request" class="btn btn-success request-update" href="<?php echo $this->url('requests/cancel',['id'=>$r->getId()])?>">cancel request</a>
            <?php
        endif;?> <a role="button" class="btn btn-success" href="<?php echo $this->url('requests/create',['id'=>$r->getId()])?>">repeat</a>
    </div>
    <div class="col-md-12" style="display:none"><!-- experiment/learning exercise -->
        <div style="position:relative; font-size:200%;">
            <span style="width:250px;display:inline-block; border:1px dotted gray" class="text-center text-muted">overlay example</span>
            <span style="width:250px;display:inline-block;position:absolute; top:0; left: 0; color:red;" class="text-center fa fa-ban pt-2"></span>
        </div>
    </div>
</div>
<?php echo $this->render('confirm-cancel')?>
<?php
/*

    [location] =>
    [parent_location] =>
    [event_id] => 115056
    [pending] =>
    [event_date] => DateTime Object
        (
            [date] => 2018-12-19 00:00:00.000000
            [timezone_type] => 3
            [timezone] => America/New_York
        )

    [event_time] => DateTime Object
        (
            [date] => 1970-01-01 13:00:00.000000
            [timezone_type] => 3
            [timezone] => America/New_York
        )

    [defendants] => Array
        (
            [0] => Array
                (
                    [surnames] => López Guerzon
                    [given_names] => Erick Gastón
                )

        )
 */
?>
