<?php     $this->headTitle('requests | '.$this->layout()->action);?>
<h2 class="text-center py-2 navigation"><?php echo $this->navigation('Zend\Navigation\RequestsBreadcrumbs')->breadcrumbs() ?></h2>
<?php
if (! $this->data):
?>
<div class="alert alert-warning shadow-sm border">
    The request was not found in the database. It may have been deleted, or you
    may have a wrong record id number in the url.
</div>
<?php
return; endif;
$this->headScript()
    ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
    ->appendFile($this->basePath('js/requests/view.js'));

$r = $this->data;
$scheduled_datetime = new \DateTime(sprintf('%s %s',$r['date']->format("Y-m-d"), $r['time']->format('H:i')));
$editable = $scheduled_datetime > $this->deadline;
?>
    <div id="request-details" class="row mx-auto border p-3 shadow-sm" data-deadline="<?php echo $this->deadline->format('Y-m-d H:i:s')?>" style="max-width:825px">
    <div class="col-md-2 text-muted text-md-right pr-1">date</div><div id="date" class="col-md-4"><?php echo $r['date']->format('D d-M-Y') ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">time</div><div id="time" class="col-md-4"><?php echo $r['time']->format('g:i a') ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">judge</div><div class="col-md-4"><?php if ($r['judge_lastname']):
        echo "{$r['judge_firstname']} {$r['judge_middlename']} {$r['judge_lastname']}, {$r['judge_flavor']}"; endif; ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">place</div><div class="col-md-4"><?php
        echo $r['location']; if ($r['parent_location']): echo ", {$r['parent_location']}";
    endif; ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">type</div><div class="col-md-4"><?php echo $r['type'] ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">language</div><div class="col-md-4"><?php echo $r['language'] ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">defendants</div><div class="col-md-4"><?php
        if ($r['defendants']):
            foreach ($r['defendants']  as $d):
                echo $this->escapeHtml("{$d['surnames']}, {$d['given_names']}"),'<br>';
            endforeach;
        endif;
    ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">docket</div><div class="col-md-4"><?php echo $r['docket'] ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">comments</div><div class="col-md-10"><?php echo $r['comments'] ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">submitted</div><div class="col-md-10"><?php
        echo "{$r['created']->format('d-M-Y g:i a')}  by {$r['submitter_firstname']} {$r['submitter_lastname']}, {$r['submitter_hat']}";
    ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">updated</div><div class="col-md-10"><?php
        if ($r['created'] != $r['modified']):
            echo "{$r['modified']->format('d-M-Y g:i a')}  by {$r['modified_by_firstname']} {$r['modified_by_lastname']}, {$r['modified_by_hat']}";
        else: ?>(n/a)<?php
        endif;
    ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">status</div><div class="col-md-10"><?php
        if ($r['pending']):
            ?>pending<?php
        elseif ($r['event_id']) :
            if ($r['cancellation']) :
                ?>cancelled<?php
                if ($r['cancellation'] !== 'other'):
                    echo " ({$r['cancellation']})";
                endif;
            elseif ($r['event_date'] < new \DateTime()):
                // it's the past
                ?>completed<?php
            else :
                ?>scheduled<?php
            endif;
        else :
            ?>deleted<?php
        endif;
    ?></div>
    <div class="col-md-12 text-center"><?php
        if ($editable):
            ?>
            <a role="button" title="modify this request" class="btn btn-success request-update" href="<?php echo $this->url('requests/update',['id'=>$r['id']])?>">update</a>
            <a role="button" id="btn-cancel" title="withdraw this request" class="btn btn-success request-update" href="<?php echo $this->url('requests/cancel',['id'=>$r['id']])?>">cancel request</a>
            <?php
        endif;?> <a role="button" class="btn btn-success" href="<?php echo $this->url('requests/create',['id'=>$r['id']])?>">repeat</a>
    </div>
    <div class="col-md-12" style="display:none"><!-- experiment/learning exercise -->
        <div style="position:relative; font-size:200%;">
            <span style="width:250px;display:inline-block; border:1px dotted gray" class="text-center text-muted">overlay example</span>
            <span style="width:250px;display:inline-block;position:absolute; top:0; left: 0; color:red;" class="text-center fa fa-ban pt-2"></span>
        </div>
    </div>
</div>
<?php
/*

    [location] =>
    [parent_location] =>
    [event_id] => 115056
    [pending] =>
    [event_date] => DateTime Object
        (
            [date] => 2018-12-19 00:00:00.000000
            [timezone_type] => 3
            [timezone] => America/New_York
        )

    [event_time] => DateTime Object
        (
            [date] => 1970-01-01 13:00:00.000000
            [timezone_type] => 3
            [timezone] => America/New_York
        )

    [defendants] => Array
        (
            [0] => Array
                (
                    [surnames] => López Guerzon
                    [given_names] => Erick Gastón
                )

        )
 */
?>
<script>
if (document.referrer.indexOf("/requests/list") !== -1) {
    document.querySelector("h2.navigation a").href = document.referrer;
}
</script>
