<?php /** module/Admin/view/interpreters-office/admin/defendants/form.phtml */
$this->headScript()->appendFile($this->basePath('/js/defendant-form.js'));
$form = $this->form;
$action = $this->layout()->action;
if ($this->error) :?>
<div data-status="<?php echo $this->status ?>" id="defendant-form">
    <div class="alert alert-danger">
        <?php echo $this->error ?>
    </div>
</div>
    <?php return;
endif;
if ($action == 'add') :
    $url = $this->url('admin-defendants/add');
else :
    $url = $this->url('admin-defendants/edit', ['id' => $form->getObject()->getId()]);
    $form->setAttribute('data-defendant_name', (string)$form->getObject());
endif;
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
    'attributes' => ['value' => 'save','id' => 'btn-submit', 'class' => 'btn btn-success btn-lg mt-2'],
])->setAttribute('method', 'post')->setAttribute('action', $url)
->setAttribute('data-redirect_url', $this->url("admin-defendants"));

$this->headTitle('admin | defendants |'.$action);
$form->prepare();
?>
<div class="center-block mx-auto" style="max-width:500px"><!-- wrapper -->
    <h2 class="navigation mb-3 mt-4"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
<?php
    echo $this->form()->openTag($form);
if ($this->error) :?>
    <?php echo $this->form()->closeTag() ?>
    </div>
    <?php return;
endif;
?>
    <div id="defendant-form-success" class="alert alert-success" style="display:none"></div>
<?php if ($form->has('duplicate_resolution')) :?>
    <p class="duplicate-name duplicate-name-instructions" style="display:none">There already exists an inexact duplicate of this name in your database: <span id="deft-existing-duplicate-name" style="font-weight:bold"></span>. Please choose one of the following:</p>
    <div id="duplicate_resolution" class="form-group duplicate-resolution-radio mb-1" style="display:none" >
        <?php $opts = $form->get('duplicate_resolution')->getValueOptions();
        foreach ($opts as $value => $label) :
            ?><div class="form-check"><input name="duplicate_resolution" value="<?php echo $value?>" class="form-check-input" type="radio" id="radio-<?php echo $value?>">
            <label for="radio-<?php echo $value?>" name="duplicate_resolution" value="<?php echo $value?>" class="form-check-label"><?php echo $label ?></label></div>
                <?php
        endforeach;?>
    </div>
    <p class="duplicate-name" style="display:none">
    <button id="btn-use-existing" class="btn btn-outline-primary btn-block mb-0 pl-4 text-left">discard my changes and use existing</button>
    <button id="btn-update-existing" class="btn btn-outline-primary btn-block border-top-0 mt-0 pl-4 text-left">apply my changes to existing name</button>
    <button id="btn-cancel" class="btn btn-outline-primary btn-block border-top-0 mt-0 pl-4 text-left" title="close this dialog">never mind, get me out of here</button>
    </p>
<?php endif; // form has duplicate_resolution element ?>
    <div class="form-group"><?php
    $surname = $form->get('surnames');
    echo $this->formLabel($surname),$this->formElement($surname), $this->formElementErrors($surname);
    ?>
    </div>
    <div class="form-group"><?php
    $given_name = $form->get('given_names');
    echo $this->formLabel($given_name),$this->formElement($given_name),$this->formElementErrors($given_name);
    ?>
    </div>
    <?php
    if ($this->occurrences) :?>
    occurrences <span class="text-muted">-- select the contexts where this update should apply:</span><br>
    <div id="occurrences" class="form-group form-check mb-2">
        <?php
        $count = count($this->occurrences);
        foreach ($this->occurrences as $i => $item) :
                $value = json_encode($item);
            ?>
            <input class="form-check-input" type="checkbox" name="occurrences[]" value="<?php echo $this->escapeHtml($value)?>" <?php
            if (1 == $count or in_array($value, $this->checked)) :
                ?> checked="checked"<?php
            endif;
            ?> id="checkbox-<?php echo $i?>">
            <label class="form-check-label" for="checkbox-<?php echo $i?>"><?php
                printf("%s - %s (%d events)", $item['docket'] ?: "(no docket numer)", $item['judge'], $item['events']);
            ?></label><br>
        <?php endforeach;?>
        <?php if ($count > 2) : ?>
            <button id="btn-select-all" class="btn btn-sm btn-default border border-info">select all</button><!--
        --><button id="btn-invert-selection" class="btn btn-sm btn-default border border-info">invert selection</button>
        <?php endif;?>
    </div>
    <?php endif; //occurrences ?>
    <div id="defendant-form-error" class="alert alert-warning" style="display:none"></div><?php
    $csrf = $form->get('defendant_csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    echo $this->formElement($form->get('id'));
    if (! $this->xhr) :
        echo $this->formSubmit($form->get('submit'));if (! $this->occurrences
        && $action == 'edit') :
            ?><input id="btn-delete" type="button" class="btn btn-lg btn-warning mt-2" title="delete this defendant name from your database" value="delete" id="btn-delete"><?php
        endif;
    endif;
    echo $this->form()->closeTag() ?>
</div>
