<main style="max-width:800px" class="center-block mx-auto">
    <h2 class="navigation mb-3 mt-4"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
    <?php
    $this->headScript()->appendFile($this->basePath('/js/admin/defendant-names-index.js'));
    $messenger = $this->flashMessenger();
    if ($messenger->hasSuccessMessages()) :
        echo $messenger->render('success', ['alert','alert-success',], false);
    endif;
    ?>
    <div class="form-row form-group mt-4">
        <div class="col-sm-5">
            <div class="input-group">
              <input value="<?=$this->escapeHtml($this->search_term ?? '')?>" type="text" id="defendant-autocomplete" value="<?=$this->docket?>" class="form-control defendant" placeholder="last name(s)[, first name(s)]" aria-label="defendant name" aria-describedby="btn-search">
              <div class="input-group-append"><button class="fas fa-search btn btn-primary" id="btn-search"><span class="sr-only">search</span></button>
              </div>
          </div>
        </div>
    </div>
    <div class="row">
        <div id="results" class="col-md-5 results">
            <?php if ($this->paginator): ?>
            <?php echo $this->partial('interpreters-office/defendants/search.phtml',['paginator'=>$this->paginator,'search'=>$this->search_term]) ; endif?>
        </div>
    </div>
</main>
