<div id="modal-confirm-delete" class="modal" tabindex="-1" role="dialog" aria-labelledby="label-delete-modal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="label-delete-modal" class="modal-title">Delete this event?</h5>
            </div>
            <div class="modal-body justify-content-center text-center pb-2">
            <?php if (! $this->count_interpreters): ?>
                <button type="button" id="btn-confirm-delete" class="btn btn-primary">Yes</button><button id="btn-no-delete" type="button" class="btn btn-secondary ml-1" data-dismiss="modal">No</button>
            </div><!--  /modal-body -->
        <?php else: $what = 'the interpreter'; if ($this->count_interpreters > 1): $what .= 's'; endif;?>
                <div class="form-check form-check-inline">
                    <button id="btn-confirm-delete" type="button"  class="btn btn-primary mr-2">Yes</button>
                    <label class="form-check-label mr-2" for="email-notification">and email <?=$what?></label>
                    <input class="form-check-input" type="checkbox" id="email-notification" value="1" checked>
                </div>
            </div>
            <div class="modal-footer justify-content-center text-center">
                <button id="btn-no-delete" type="button" class="btn btn-secondary ml-1" data-dismiss="modal">No</button>
            </div>
            <?php endif ?>
        </div><!-- /modal-content -->
    </div><!-- /modal-dialog -->
</div><!-- /.modal -->
