<?php /* module/Admin/view/interpreters-office/admin/schedule/index.phtml */
$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
$this->headScript()->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'))
    ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
    ->appendFile($this->basePath('js/schedule.js'));
$this->headTitle($this->date->format('D d M Y'));
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
elseif ($messenger->hasErrorMessages()) :
    echo $messenger->render('danger', ['alert','alert-danger',], false);
endif;?>
<div class="row mb-0 mt-3 py-2">
    <div class="col-2 align-self-center text-left">
    <a role="button" title="go back one day" data-toggle="tooltip" class="btn btn-lg btn-primary py-1 fas fa-arrow-left" style="font-size:1.2rem;background-color:#74b4fb" href="<?php
        echo $this->url('events').$this->prev
    ?>"><span class="sr-only">previous</span></a>
    </div>
    <div class="col-8 text-center border rounded">
        <h2 class="navigation pt-1"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?> <small class="text-muted display-date"><?php echo $this->date->format('D d M Y')?></small>
        </h2>
    </div>
    <div class="col-2 align-self-center text-right">
    <a role="button" title="go forward one day" data-toggle="tooltip" class="btn btn-lg btn-primary py-1 fas fa-arrow-right" style="font-size:1.2rem;background-color:#74b4fb" href="<?php
        echo $this->url('events').$this->next
    ?>"><span class="sr-only">previous</span></a>
    </div>
</div><!-- /row   -->
<!-- <div class="row"> -->
    <div class="offset-md-2 col-8 d-flex">
        <div class="form-inline mx-auto">
            <label for="language-select" class="text-md-right px-1">language</label>
            <select class="form-control form-control-sm custom-select" id="language-select" name="language">
                <option label="all" value="all">all</option>
                <option label="Spanish" <?php if ($this->language == 'spanish') :
                    ?>selected="selected" <?php
                                        endif;?>value="spanish">Spanish</option>
                <option label="not Spanish" <?php if ($this->language == 'not-spanish') :
                    ?>selected="selected" <?php
                                            endif;?>value="not-spanish">not Spanish</option>
            </select>
            <label for="date-input" class="text-md-right pl-2 pr-1">date</label>
            <input type="text" name="date" id="date-input" class="form-control  form-control-sm" style="max-width:125px">
        </div>
    </div>
<?php echo $this->partial('interpreters-office/admin/schedule/partials/table', ['data' => $data]);
