<?php /** module/Admin/view/interpreters-office/admin/schedule/view.phtml  */
$this->headScript()
->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'))
->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
->appendFile($this->basePath('js/event-email.js'))
->appendFile($this->basePath('js/event-delete.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
$this->headStyle()->captureStart();?>
.ui-autocomplete {
  z-index: 99999 !important;
}
.tooltip-inner {
    text-align: left;
}
<?php $this->headStyle()->captureEnd();
/**
 *
 * @var \InterpretersOffice\Entity\Event $event
 */
$event = $this->event;

if ('submitter' ==  $event['last_update_user_role']) :
    $event['last_updated_by'] = 'system';
    // instead of "{$event['last_update_firstname_init']}. {$event['last_update_lastname']}";
endif;
$this->entity = $event;
if (! $event or $event['deleted']) :
    $this->headTitle('event not found');
     ?>
    <div class="alert alert-warning mx-auto mt-3 border shadow-sm" style="max-width:600px">
        <h3>event not found</h3>
        Event id #<?= $this->id ?>  was not found in the database. You may have a wrong id in your URL parameter, or the event may have been deleted.</div>
    <?php
    return;
endif;
$this->headTitle('event details');
?>
<h2 class="navigation pt-1 mx-auto my-4 text-center"><a href="/admin">admin</a> | <a href="/admin/schedule">schedule</a> <small class="text-muted text-md-right">event details</small></h2>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
else : ?>
<div class="alert alert-success mx-auto" style="max-width:900px;display:none"><button type="button" class="close" data-hide="alert" aria-hidden="true">&times;</button><p></p></div>
<?php
endif;
if ($messenger->hasErrorMessages()) :
    echo $messenger->render('danger', ['alert','alert-danger',], false);
else: ?>
<div class="alert alert-warning mx-auto pt-3 pb-0" style="max-width:900px;display:none"><button type="button" class="close" data-hide="alert" aria-hidden="true">&times;</button><p></p></div>
<?php endif;
if ($event['deleted']):
 echo "say shit, we have been deleted";
endif;
?>
<div data-modified="<?php echo $event['last_updated'] ? $event['last_updated']->format('Y-m-d H:i:s') : ''?>" data-event_category="<?php echo $event['category']?>" data-event_datetime="<?php echo $event['datetime']?>" data-event_id="<?php echo $event['id']?>" class="row event-details mx-auto border p-2 shadow-sm" style="max-width:900px">
<?php
if (!$this->before):?>
    <div class="col-sm-3 text-muted text-md-right">
        date
    </div>
    <div class="col-sm-3 pl-0 date">
        <?php echo $this->event['date']->format('d-M-Y')?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        time
    </div>
    <div class="col-sm-3 pl-0 time">
        <?php echo $this->event['time'] ?$this->event['time']->format('g:i a'): '<em>?</em>' ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        type
    </div>
    <div class="col-sm-3 pl-0  event_type">
        <?php echo $this->event['type']; ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        language
    </div>
    <div class="col-sm-3 pl-0 language">
        <?php echo $this->event['language']?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        judge
    </div>
    <div class="col-sm-3 pl-0 judge"<?php if ($event['judge_lastname']) : ?> data-judge_lastname="<?php echo $this->escapeHtml($event['judge_lastname'])?>"<?php endif; ?>>
        <?php echo $this->event['judge'];
        if ($event['aj_default_location']) :
            ?> <span class="text-muted"><?php echo $event['aj_default_location']?></span><?php
        endif; ?>
    </div>
    <div class="col-sm-3  text-muted text-md-right">
        location
    </div>
    <div class="col-sm-3 pl-0 location">
        <?php echo $this->event['location'];  if ($event['is_default_location']):?> <span class="text-muted text-md-right">**</span><?php endif ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        defendants
    </div>
    <div class="col-sm-3 pl-0 defendants"><?php
        echo implode('<br>',array_map(function($d){
            return $this->escapeHtml("{$d['surnames']}, {$d['given_names']}");
        },$this->event['defendants']))
    ?>
    </div>
    <div class="col-sm-3  text-muted text-md-right">
        docket
    </div>
    <div class="col-sm-3 pl-0 docket">
        <?php echo $this->event['docket'] ?>
    </div>
    <div class="col-sm-3  text-muted text-md-right">
        interpreters
    </div>
    <div class="col-sm-3 pl-0 interpreters"><?php
    echo implode('<br>',array_map(function($i){
        return $this->escapeHtml("{$i['lastname']}, {$i['firstname']}");
    },$this->event['interpreters']))
    ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        cancellation
    </div>
    <div class="col-sm-3 pl-0 cancellation">
        <?php echo $this->event['reason_for_cancellation'] ?: '<span class="text-muted">n/a</span>'?>
    </div>
    <div class="col-sm-3  text-muted text-md-right">
        <?php if ($event['request_id']):?>* <?php endif ?>request by
    </div>
    <div class="col-sm-3 pl-0 submitter" data-id="<?php echo $event['submitter_id']?>"><span class="avoidwrap">
        <?php echo $event['submitter'] ;
        ?><?php
    if ($event['submitter_hat']) :
    ?>,</span> <span class="avoidwrap"><?php
    echo $this->event['submitter_hat'];
    endif;?></span>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        requested on
    </div>
    <div class="col-sm-3 pl-0">
    <?php
        printf('%s %s',
        $event['submission_date']->format('d-M-Y'),
        $event['submission_time']->format('g:i a')
        );
    ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        created
    </div>
    <div class="col-sm-3 pl-0">
        <?php echo $event['created']->format('d-M-Y g:i a'), " ({$event['created_by']})"; ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        last updated
    </div>
    <div class="col-sm-3 pl-0 last-modified">
        <?php
        echo $event['created'] != $event['last_updated'] ?
        "{$this->event['last_updated']->format('d-M-Y g:i a')}<br>({$event['last_updated_by']})"
        : '<span class="text-muted">n/a</span>';
        ?>
    </div>
    <?php if ($event['submitter_comments']): ?>
    <div class="col-sm-3 text-muted text-md-right">
        submitter comments
    </div>
    <div class="col-sm-9 pl-0">
        <?php echo nl2br($this->escapeHtml($this->event['submitter_comments'])) ?>
    </div>
    <?php endif; ?>
    <div class="col-sm-3 text-muted text-md-right">
        comments (public)
    </div>
    <div class="col-sm-9 pl-0">
        <?php echo nl2br($this->escapeHtml($this->event['comments']))?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        comments (internal)
    </div>
    <div class="col-sm-9 pl-0">
        <?php echo nl2br($this->escapeHtml($this->event['admin_comments']));
        if ($event['submitter_extra_data'] and
            isset($event['submitter_extra_data']['defendants'])): ?>
            <div class="extra-deft-names text-muted mt-0 pt-0">
                Defendant name(s) the submitter did not find in the database:<br>
                <ul><li>
                <?php echo implode('</li><li>',
                    $event['submitter_extra_data']['defendants']);
                ?></li></ul>
            </div>
        <?php endif; ?>
    </div>
<?php else: $this->with_comments = true; // for the diff() helper ?>
    <div class="col-sm-3 text-muted text-md-right">
        date
    </div>
    <div class="col-sm-3 pl-0 date">
        <?php echo $this->diff('date')?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        time
    </div>
    <div class="col-sm-3 pl-0 time">
        <?php echo $this->diff('time') ?: '<em>?</em>' ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        type
    </div>
    <div class="col-sm-3 pl-0  event_type">
        <?php echo $this->diff('type'); ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        language
    </div>
    <div class="col-sm-3 pl-0 language">
        <?php echo $this->diff('language')?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        judge
    </div>
    <div class="col-sm-3 pl-0 judge"<?php if ($event['judge_lastname']) : ?> data-judge_lastname="<?php echo $this->escapeHtml($event['judge_lastname'])?>"<?php endif; ?>>
        <?php echo $this->diff('judge');
        if ($event['aj_default_location']) :
            ?> <span class="text-muted"><?php echo $event['aj_default_location']?></span><?php
        endif; ?>
    </div>
    <div class="col-sm-3  text-muted text-md-right">
        location
    </div>
    <div class="col-sm-3 pl-0 location">
        <?php echo $this->diff('location');  if ($event['is_default_location']):?> <span class="text-muted text-md-right">**</span><?php endif ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        defendants
    </div>
    <div class="col-sm-3 pl-0 defendants"><?php
        echo $this->diff('defendants');
    ?>
    </div>
    <div class="col-sm-3  text-muted text-md-right">
        docket
    </div>
    <div class="col-sm-3 pl-0 docket">
        <?php echo $this->diff('docket') ?>
    </div>
    <div class="col-sm-3  text-muted text-md-right">
        interpreters
    </div>
    <div class="col-sm-3 pl-0 interpreters"><?php
        echo $this->diff('interpreters');
    ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        cancellation
    </div>
    <div class="col-sm-3 pl-0 cancellation">
        <?php echo $this->diff('reason_for_cancellation') ;//?: '<span class="text-muted">n/a</span>'?>
    </div>
        <div class="col-sm-3  text-muted text-md-right">
        <?php if ($event['request_id']):?>* <?php endif ?>request by
    </div>
    <div class="col-sm-3 pl-0 submitter" data-id="<?php echo $event['submitter_id']?>"><span class="avoidwrap">
        <?php echo $event['submitter'] ;
        ?><?php
if ($event['submitter_hat']) :
    ?>,</span> <span class="avoidwrap"><?php
    echo $this->diff('submitter_hat');
endif;?></span>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        requested on
    </div>
    <div class="col-sm-3 pl-0">
    <?php
    if ($event['request_id']):
        printf('%s %s',
        $event['submission_date']->format('d-M-Y'),
        $event['submission_time']->format('g:i a')
        );
    else:
        printf('%s %s',
            $this->diff('submission_date'),
            $this->diff('submission_time')
        );
    endif;
    ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        created
    </div>
    <div class="col-sm-3 pl-0">
        <?php echo $event['created']->format('d-M-Y g:i a'), " ({$event['created_by']})"; ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        last updated
    </div>
    <div class="col-sm-3 pl-0 last-modified">
        <?php
        echo $event['created'] != $event['last_updated'] ?
        "{$this->diff('last_updated')}<br>({$this->diff('last_updated_by')})"
        : '<span class="text-muted">n/a</span>';
        ?>
    </div>
<?php if ($event['submitter_comments']): ?>
    <div class="col-sm-3 text-muted text-md-right">
        submitter comments
    </div>
    <div class="col-sm-9 pl-0">
        <?php echo nl2br($this->escapeHtml($event['submitter_comments'])) ?>
    </div>
<?php endif; ?>
    <div class="col-sm-3 text-muted text-md-right">
        comments (public)
    </div>
    <div class="col-sm-9 pl-0">
        <?php //echo nl2br($this->escapeHtml($event['comments']))
        echo nl2br($this->diff('comments'))
        ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        comments (internal)
    </div>
    <div class="col-sm-9 pl-0">
        <?php echo nl2br($this->diff('admin_comments'));
        if ($event['submitter_extra_data'] and
            isset($event['submitter_extra_data']['defendants'])): ?>
            <div class="extra-deft-names text-muted mt-0 pt-0">
                Defendant name(s) the submitter did not find in the database:<br>
                <ul><li>
                <?php echo implode('</li><li>',
                    $event['submitter_extra_data']['defendants']);
                ?></li></ul>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
    <div class="col-12 d-flex">
        <div class="btn-group mx-auto" role="group" aria-label="available actions">
        <?php if (!$event['deleted']):?>
            <a href="<?php echo $this->url('events/edit', ['id' => $event['id']])?>" role="button" class="btn btn-success">edit</a>
            <a href="<?php echo $this->url('events/add', ['id' => $event['id']]);?>" role="button" class="btn btn-success">repeat</a>
            <a id="btn-email" data-toggle="modal" data-target="#email-dialog" href="<?php echo "#";//$this->url('events/add', ['id' => $event['id']]);?>" role="button" class="btn btn-success">email</a>
            <a role="button" data-toggle="modal" data-target="#modal-confirm-delete" data-csrf="<?php echo $this->csrf ?>" href="<?php echo $this->url('events/edit', ['action' => 'delete',  'id' => $event['id']])?>" id="btn-delete" class="btn btn-success">fuckin delete</a>
        </div>
        <?php else: ?>
            <div class="alert alert-warning pt-2 border event-deleted">
                This event has been deleted from your schedule.
            </div>
        <?php endif; ?>
    </div>
    <?php if ($event['request_id'] or $event['is_default_location']): ?>
    <div class="col-sm-9 pl-0 offset-sm-3  text-muted border-bottom-0" style=font-size:90%;>
        <?php if ($event['request_id']):?>* request was submitted online<br><?php endif; ?>
        <?php if ($event['is_default_location']) :?>** location not specified; this is the default<?php endif; ?>
    </div>
    <?php endif;?>
</div>
    <?php $suggestions = [];
    if ($event['interpreters'] or $event['submitter_email']):
        if ($event['submitter_email']) {
            $suggestions[] = ['role'=>'submitter','name' => $event['submitter'],
            'email' => strtolower($event['submitter_email']), 'id' => $event['submitter_id']];
        }
        if ($event['interpreters'])
            {
            foreach($event['interpreters'] as $i) {
                // in some cases, the submitter and the interpreter are identical
                if (count($suggestions) && in_array($i['email'],array_column($suggestions,'email'))) {
                    $suggestions[0]['role'] = 'interpreter';
                    continue;
                }
                $suggestions[] = ['role'=>'interpreter','name' => "$i[firstname] $i[lastname]",
                'id' => $i['id'],
                'email' =>  strtolower($i['email'])];
            }
        }
    endif;
    if ($this->before && isset($this->before['interpreters'])) :
        foreach ($this->before['interpreters'] as $i) :
            if (! $event['interpreters'] or
                ! in_array($i['email'],array_column($suggestions,'email'))):
                $suggestions[] = ['role'=>'interpreter','name' => "$i[firstname] $i[lastname]",
                    'email' => $i['email'], 'id' => $event['submitter_id']];
            endif;
        endforeach;
    endif;
    echo $this->partial('schedule/email-modal.phtml',compact('suggestions','event'));
    echo $this->partial('schedule/confirm-delete-modal.phtml',['count_interpreters'=>count($event['interpreters'])]);
?><!-- -->
