<?php /** module/Admin/view/interpreters-office/admin/schedule/view.phtml  */
$this->headScript()
->appendFile($this->basePath('js/event-delete.js'))
->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'))
->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
->appendFile($this->basePath('js/event-email.js'));
$this->headLink()
        ->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
//->appendFile($this->basePath('js/lib/sweetalert2.min.js'))
//$this->headLink()->appendStylesheet($this->basePath('css/sweetalert2.css'));
$this->headStyle()->captureStart();?>
.ui-autocomplete {
  z-index: 99999 !important;
}
.tooltip-inner {
    text-align: left;
}
<?php $this->headStyle()->captureEnd();
/**
 *
 * @var \InterpretersOffice\Entity\Event $event
 */
$event = $this->event;
$this->entity = $event; // hint the Diff helper
if (! $event) :  ?>
    <p class="alert alert-warning">event not found!</p>
    <?php
    return;
endif;
$this->headTitle('event details');
?>
<h2 class="navigation pt-1 mx-auto my-4 text-center"><a href="/admin">admin</a> | <a href="/admin/schedule">schedule</a> <small class="text-muted text-md-right">event details</small></h2>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
elseif ($messenger->hasErrorMessages()) :
    echo $messenger->render('danger', ['alert','alert-danger',], false);
endif;?>
<!-- experimental debug zone -->
<pre><?php
//print_r($event['category']);
$session = new \Zend\Session\Container('event_updates');
//print_r(array_keys($this->entity));
if ($session->{$event['id']}) {
    $this->before = $session->{$event['id']};
    unset($session->{$event['id']});
}
?></pre>
<!-- TO DO: make partials for flat-out details and for "diff"
    and use one or the other, depending
-->
<div data-modified="<?php echo $event['last_updated'] ? $event['last_updated']->format('Y-m-d H:i:s') : ''?>" data-event_category="<?php echo $event['category']?>" data-event_datetime="<?php echo $event['datetime']?>" data-event_id="<?php echo $event['id']?>" class="row event-details mx-auto border p-2 shadow-sm" style="max-width:900px">
    <div class="col-sm-3 text-muted text-md-right">
        date
    </div>
    <div class="col-sm-3 pl-0 date">
        <?php echo $this->diff('date')?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        time
    </div>
    <div class="col-sm-3 pl-0 time">
        <?php echo $this->diff('time') ?: '<em>?</em>' ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        type
    </div>
    <div class="col-sm-3 pl-0  event_type">
        <?php echo $this->diff('type'); ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        language
    </div>
    <div class="col-sm-3 pl-0 language">
        <?php echo $this->diff('language')?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        judge
    </div>
    <div class="col-sm-3 pl-0 judge"<?php if ($event['judge_lastname']) : ?> data-judge_lastname="<?php echo $this->escapeHtml($event['judge_lastname'])?>"<?php endif; ?>>
        <?php echo $this->diff('judge');
        if ($event['aj_default_location']) :
            ?> <span class="text-muted"><?php echo $event['aj_default_location']?></span><?php
        endif; ?>
    </div>
    <div class="col-sm-3  text-muted text-md-right">
        location
    </div>
    <div class="col-sm-3 pl-0 location">
        <?php echo $this->diff('location');  if ($event['is_default_location']):?> <span class="text-muted text-md-right">**</span><?php endif ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        defendants
    </div>
    <div class="col-sm-3 pl-0 defendants"><?php
        echo $this->diff('defendants');
    ?>
    </div>
    <div class="col-sm-3  text-muted text-md-right">
        docket
    </div>
    <div class="col-sm-3 pl-0 docket">
        <?php echo $this->diff('docket') ?>
    </div>
    <div class="col-sm-3  text-muted text-md-right">
        interpreters
    </div>
    <div class="col-sm-3 pl-0 interpreters"><?php
        echo $this->diff('interpreters');
    ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        cancellation
    </div>
    <div class="col-sm-3 pl-0 cancellation">
        <?php echo $this->diff('reason_for_cancellation') ;//?: '<span class="text-muted">n/a</span>'?>
    </div>
        <div class="col-sm-3  text-muted text-md-right">
        <?php if ($event['request_id']):?>* <?php endif ?>request by
    </div>
    <div class="col-sm-3 pl-0"><span class="avoidwrap">
        <?php echo $event['submitter'] ;
        ?><?php
if ($event['submitter_hat']) :
    ?>,</span> <span class="avoidwrap"><?php
    echo $this->diff('submitter_hat');
endif;?></span>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        requested on
    </div>
    <div class="col-sm-3 pl-0">
    <?php
    if ($event['request_id']):
        printf('%s %s',
        $event['submission_date']->format('d-M-Y'),
        $event['submission_time']->format('g:i a')
        );
    else:
        printf('%s %s',
            $this->diff('submission_date'),
            $this->diff('submission_time')
        );
    endif;

    ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        created
    </div>
    <div class="col-sm-3 pl-0">
        <?php echo $event['created']->format('d-M-Y g:i a'), " ({$event['created_by']})"; ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        last updated
    </div>
    <div class="col-sm-3 pl-0">
        <?php echo $event['created'] != $event['last_updated'] ?
        "{$this->diff('last_updated')} ({$this->diff('last_updated_by')})"
        : '<span class="text-muted">n/a</span>';
        ?>
    </div>
<?php if ($event['submitter_comments']): ?>
    <div class="col-sm-3 text-muted text-md-right">
        submitter comments
    </div>
    <div class="col-sm-9 pl-0">
        <?php echo nl2br($this->escapeHtml($event['submitter_comments'])) ?>
    </div>
<?php endif; ?>
    <div class="col-sm-3 text-muted text-md-right">
        comments (public)
    </div>
    <div class="col-sm-9 pl-0">
        <?php //echo nl2br($this->escapeHtml($event['comments']))
        echo nl2br($this->diff('comments'))
        ?>
    </div>
    <div class="col-sm-3 text-muted text-md-right">
        comments (internal)
    </div>
    <div class="col-sm-9 pl-0">
        <?php echo nl2br($this->diff('admin_comments'));
        if ($event['submitter_extra_data'] and
            isset($event['submitter_extra_data']['defendants'])): ?>
            <div class="extra-deft-names text-muted mt-0 pt-0">
                The submitter did not find defendant name(s) in your database:<br>
                <ul><li>
                <?php echo implode('</li><li>',
                    $event['submitter_extra_data']['defendants']);
                ?></li></ul>
            </div>
        <?php endif; ?>
    </div>
    <div class="col-12 d-flex">
        <div class="btn-group mx-auto" role="group" aria-label="available actions">
          <a href="<?php echo $this->url('events/edit', ['id' => $event['id']])?>" role="button" class="btn btn-success">edit</a>
          <a href="<?php echo $this->url('events/add', ['id' => $event['id']]);?>" role="button" class="btn btn-success">repeat</a>
          <a id="btn-email" data-toggle="modal" data-target="#email-dialog" href="<?php echo "#";//$this->url('events/add', ['id' => $event['id']]);?>" role="button" class="btn btn-success">email</a>
          <a data-csrf="<?php echo $this->csrf ?>" href="<?php echo $this->url('events/edit', ['action' => 'delete',  'id' => $event['id']])?>" id="btn-delete" role="button" class="btn btn-success">delete</a>
        </div>
    </div>
    <?php if ($event['request_id'] or $event['is_default_location']): ?>
        <div class="col-sm-9 pl-0 offset-sm-3  text-muted border-bottom-0" style=font-size:90%;>
            <?php if ($event['request_id']):?>* request was submitted online<br><?php endif; ?>
            <?php if ($event['is_default_location']) :?>** location not specified; this is the default<?php endif; ?>
        </div>
    <?php endif;
    $suggestions = [];
    if ($event['interpreters'] or $event['submitter_email']):
        if ($event['submitter_email']) {
            $suggestions[] = ['role'=>'submitter','name' => $event['submitter'], 'email' => $event['submitter_email']];
        }
        if ($event['interpreters'])
            {
            foreach($event['interpreters'] as $i) {
                // in some cases, the submitter and the interpreter are identical
                if (count($suggestions) && in_array($i['email'],array_column($suggestions,'email'))) {
                    $suggestions[0]['role'] = 'interpreter';
                    continue;
                }
                $suggestions[] = ['role'=>'interpreter','name' => "$i[firstname] $i[lastname]", 'email' => $i['email']];
            }
        }
    endif;
    ?>
</div>
<div class="modal fade" id="email-dialog" role="dialog" aria-labelledby="email-modal-label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="email-modal-label">send email</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div style="min-height:300px" class="modal-body">
                <div class="container-fluid">
                    <form id="email-form">
                        <div class="form-row form-group mb-3">
                            <label for="recipient-autocomplete" class="col-md-2 text-right col-form-label">To
                            </label>
                            <div class="col-md-10">
                                <div class="input-group"><!--  dropleft -->
                                    <!--   -->
                                    <input id="recipient-autocomplete" name="recipient-autocomplete" type="text" class="form-control" placeholder="start typing last name<?php
                                    if ($suggestions):?>, or use the dropdown<?php endif;
                                    ?>">
                                   <button id="btn-add-recipient" data-toggle="tooltip" class="btn btn-sm btn-secondary btn-add-recipient border disabled" title="manually add a recipient">
                                      <span class="fas fa-plus" aria-hidden="true"></span><span class="sr-only">add another recipient</span>
                                  </button>
                                  <?php
                                  // if there are any email addresses involved, assemble a dropdown to display them
                                  if ($suggestions): ?>
                                  <a title="suggested recipients" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-recipients" data-toggle="dropdown" data-offset="-50" aria-haspopup="true" aria-expanded="false">select</a>
                                  <div id="email-dropdown" class="dropdown-menu pl-1">
                                        <?php foreach ($suggestions as $i => $person):?>
                                            <div class="form-group">
                                              <div class="form-check">
                                                <input <?php if (isset($person['role'])): ?>data-role="<?php echo $person['role']?>" <?php endif;?>name="recipients[]" value="<?php echo $person['email']?>" type="checkbox" class="form-check-input" id="email-<?php echo $i?>" checked>
                                                <label class="form-check-label" for="email-<?php echo $i?>">
                                                  <?php echo $person['name'] ?>
                                                </label>
                                              </div>
                                            </div>
                                        <?php endforeach; ?>
                                        <div class="dropdown-divider">
                                        </div>
                                        <div class="dropdown-item">
                                            <button title="add people selected above as email recipients" id="btn-add-recipients" class="btn btn-sm btn-outline-primary">Add</button>
                                            <button class="btn btn-sm btn-outline-secondary">Cancel</button>
                                        </div>
                                        <div class="alert alert-warning validation-error" style="display:none"></div>
                                  </div>
                              <?php endif; ?>
                               </div>
                            </div>
                        </div>
                        <div class="form-row form-group email-subject">
                            <label for="message-subject" class="col-md-2 text-right col-form-label">Subject
                            </label>
                            <div class="col-md-10">
                                <div class="input-group">
                                    <input name="subject" id="message-subject" type="text" class="form-control text-truncate" placeholder="type your subject line, or use the dropdown">
                                    <a title="suggested subject lines" class="btn btn-outline-secondary dropdown-toggle  dropdown-toggle-subject" data-toggle="dropdown" data-offset="-50" aria-haspopup="true" aria-expanded="false">select</a>
                                    <div id="subject-dropdown" class="dropdown-menu pl-1">
                                    <?php if ($event['submitter_email']) :?>
                                        <div data-toggle="tooltip" data-placement="left" title="contact <?php echo $this->escapeHtml($event['submitter'])?>" data-subject="your request" class="dropdown-item">
                                            <a href="#">your interpreter request
                                        </div>
                                        <div class="dropdown-divider"></div>
                                    <?php endif; ?>
                                        <div data-toggle="tooltip" data-placement="left" title="offer this assignment" data-subject="available" class="dropdown-item">
                                             <a href="#">assignment available</a>
                                        </div>
                                        <div class="dropdown-divider"></div>
                                    <?php if ($event['interpreters']) :?>
                                        <?php if ($event['interpreters']) :?>
                                            <div data-toggle="tooltip" data-placement="left" title="send details of noteworthy updates" data-subject="update" class="dropdown-item">
                                                <a href="#">assignment update</a>
                                            </div>
                                            <div class="dropdown-divider"></div>
                                        <?php endif; ?>
                                        <div data-toggle="tooltip" data-placement="left" title="send confirmation as to this assignment" data-subject="confirmation" class="dropdown-item">
                                            <a href="#">assignment confirmation</a>
                                        </div>
                                        <div class="dropdown-divider"></div>
                                    <?php endif; ?>
                                    <?php if ('n/a' != $event['reason_for_cancellation']) :?>
                                        <div data-toggle="tooltip" data-placement="left" title="notify that the assignment has been cancelled" data-subject="cancellation" class="dropdown-item">
                                            <a href="#">assignment cancellation</a>
                                        </div>
                                        <div class="dropdown-divider"></div>
                                    <?php endif; ?>
                                    </div>
                               </div>
                            </div>
                        </div>
                    <div class="form-row form-group">
                        <label for="message-body" class="col-md-2 text-right col-form-label">Message</label>
                        <div class="col-md-10">
                            <div class="input-group">
                                <textarea name="message-body" placeholder="some bullshit here" id="message-body" class="form-control" rows="8"></textarea>
                           </div>
                        </div>
                    </div>
                    <div class="form-row form-group">
                        <div class="form-check offset-md-2 col-md-10">
                            <input class="form-check-input" type="checkbox" id="include-details" name="include-details" value="1" checked>
                            <label for="include-details" class="ml-1 form-check-label">Include event details</label>
                        </div>
                    </div>
                    </form>
                </div>
            <div class="modal-footer center-block row" id="modal-footer">
                <div class="col text-center">
                    <button disabled="disabled" id="btn-send" class="btn btn-success disabled">send</button>
                    <button id="btn-cancel" class="btn btn-secondary">cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- -->
<!-- -->
