<?php /** module/Admin/view/docket-annotations/form.phtml */
$this->headTitle('docket annotations |'.$this->layout()->action);
$this->headScript()->appendFile($this->basePath('js/admin/docket-annotations-form.js'));?>

<div class="mx-auto" style="max-width:800px">
    <h2><?= $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
    <?php
    if ($this->note):
        $priority = $this->note->getPriority();
        $docket = $this->note->getDocket();
    else:
        $priority = null;
        $docket = $this->docket ?? '';
    endif;
    if ($this->layout()->action == 'edit') :
        if (! $this->note) :
            ?>
            <div class="alert alert-warning mt-4 border border-warning py-2 px-2">
                Docket annotation was not found in the database. It may have been deleted, or
                your query may contain an invalid id number.
            </div>
        </div>
        <?php return;
            endif;
        $action = $this->basePath('/admin/docket-notes/api/update');
        $method = 'PUT';
    elseif ($this->layout()->action == 'add'):
        $action = $this->basePath('/admin/docket-notes/api/create');
        $method = 'POST';
    endif;
    ?>
    <div id="status" class="alert alert-success" style="display:none"></div>
    <form class="mt-4" id="annotation-form" action="<?=$action ?? ''?>" method="<?= $method ?? ''?>">
        <div class="form-row form-group">
            <label class="col-form-label col-sm-3" for="docket">
                <span class="float-md-right">docket</span>
            </label>
            <div class="col-sm-4">
                <input type="text" id="docket" class="form-control" name="docket" value="<?=$this->escapeHtml($docket)?>">
            </div>
        </div>
        <div class="form-row form-group">
            <label class="col-form-label col-sm-3" for="comment">
                <span class="float-md-right">text</span>
            </label>
            <div class="col-sm-6">
                <textarea id="comment" name="comment" class="form-control" rows="5" cols="60"><?php if ($this->note): echo $this->note->getComment(); endif?></textarea>
                <span class="text-muted">You can use <a target="__blank" href="https://www.markdownguide.org/basic-syntax">Markdown</a> for formatting</span>
            </div>
        </div>
        <div class="form-row form-group">
            <div class="col-sm-3" for="priority">
                <span class="float-md-right">priority</span>
            </div>
            <div class="col-sm-4">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="priority" id="priority-1" value="1" <?php if ($priority == 1):?>checked<?php endif ?>>
                    <label class="form-check-label" for="priority-1"><span class="fas fa-info-circle text-info"></span>
                        informational
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="priority" id="priority-2" value="2" <?php if ($priority == 2):?>checked<?php endif ?>>
                    <label class="form-check-label" for="priority-2"><span class="fas fa-exclamation-triangle text-warning"></span>
                        warning
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="priority" id="priority-3" value="3" <?php if ($priority == 3):?>checked<?php endif ?>>
                    <label class="form-check-label" for="priority-3"><span class="fas fa-skull-crossbones text-danger"></span>
                        danger
                    </label>
                </div>
            </div>
        </div>
        <div class="row mt-0 py-0">
            <div id="error_priority" class="col-sm-4 offset-sm-3 alert alert-warning validation-error" style="display:none"></div>
        </div>
        <div class="form-row form-group">
            <div class="col-sm-4 offset-sm-3 pt-2"><button type="button" id="btn-save" class="btn btn-success">save</button><?php if ($this->note): ?>
                <button type="button" class="btn btn-warning" id="btn-delete">delete</button>
            <?php endif;?>
                <input type="hidden" name="id" value="<?=$this->note ? $this->note->getId() : ''?>">
                <input type="hidden" name="csrf" value="<?= $this->csrf ?>">
            </div>
    </form>
</div>
