<?php $this->headTitle('docket annotations');
$this->headScript()->appendFile($this->basePath('js/admin/docket-annotations.js'));
?>
<div class="mx-auto" style="max-width:800px">
    <h2><?= $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
    <div class="form-row form-group mt-4">
        <div class="col-sm-5">
            <div class="input-group">
              <input type="text" id="docket" value="<?=$this->docket?>" class="form-control docket" placeholder="docket number" aria-label="docket number" aria-describedby="btn-search">
              <div class="input-group-append"><button class="fas fa-search btn btn-primary" id="btn-search"><span class="sr-only">search</span></button>
              </div>
          </div>
          <div style="display:none" id="error_docket" class="alert alert-warning validation-error"></div>
        </div>
    </div>
    <div id="results" data-csrf="<?=$this->csrf?>" class="results">
        <?php echo $this->partial('docket-annotations/partials/table',[
            'data' => $this->data, 'docket' => $this->docket
        ]);?>
    </div>
    <div class="text-center">
        <a role="button" href="<?= $this->url('admin/docket-annotations/add',['docket'=>$this->docket ?? ''])?>" type="button" id="btn-create" class="btn btn-primary btn-sm" name="button"><span class="fas fa-plus"></span> add</a>
    </div>
</div>
