<?php $this->headTitle('docket annotations');
$this->headScript()->appendFile($this->basePath('js/admin/docket-annotations.js'));
?>
<div class="mx-auto border" style="max-width:800px">
    <h2><?= $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
    <?php
        // $data = $this->service->find('2018-CR-0509');
        // $obj = $data[0];
        // echo $obj->getComment(),"<br>";
        //echo $obj->getCreatedBy()->getUsername();
    ?>
    <div class="form-row form-group mt-4">
        <!-- <label class="sr-only col-form-label col-sm-2" for="docket">
            <span class="float-md-right">docket</span>
        </label> -->
        <div class="col-sm-5">
            <div class="input-group">
              <input type="text" class="form-control docket" placeholder="docket number" aria-label="docket number" aria-describedby="btn-search">
              <div class="input-group-append"><button class="fas fa-search btn btn-primary" id="btn-search"><span class="sr-only">search</span></button>
              </div>
          </div>
          <div style="display:none" id="error_docket" class="alert alert-warning validation-error"></div>
        </div>
    </div>
    <div class="results">
    </div>
    <div class="text-center">
        <button type="button" id="btn-create" class="btn btn-primary btn-sm" name="button"><span class="fas fa-plus"></span> add</button>
    </div>
</div>
