
<table id="schedule-table" class="table table-hover table-bordered table-sm rounded mt-2">
    <thead>
        <tr>
            <th>time</th>
            <th>type</th>
            <th>judge</th>
            <th>language</th>
            <th>docket</th>
            <th>defendants</th>
            <th>notes</th>
            <th>interpreters</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->data) :
            foreach ($this->data['events'] as $e) :
                if (stristr($e['judge'], 'magistrate') !== false && ! $e['location']) :
                    $magistrate_default = $e['aj_default_location'];
                endif;
                ?>
        <tr data-id="<?php echo $e['id']?>" class="event-category-<?php echo str_replace(' ', '-', $e['category']) ?><?php
        if ($e['cancellation']) :
            echo " event-cancelled" ;
        endif;?>">
            <td class="text-right text-nowrap"><?php echo $e['time'] ? $e['time']->format('g:i a') : ''?></td>
            <td style="line-height:1.2em" class="py-2 clearfix">
                <a data-toggle="tooltip" title="view event details" href="<?php echo $this->url('events/view', ['id' => $e['id']]);?>"><?php echo $e['type']; ?><?php
                if ($e['location_type'] == 'jail') :
                    ?><br><span class="text-muted"><?php echo $e['location'];?></span><?php
                endif;
                ?></a>
                <a class="link-edit-event" href="<?php echo $this->url('events/edit', ['id' => $e['id']]) ?>">
                    <span data-toggle="tooltip" title="edit this event" class="ml-1 float-right align-self-top fas fa-edit text-primary mr-2"> </span>
                    <span class="sr-only">edit this event</span>
                </a>
            </td>
            <td class="text-nowrap"><?php echo $e['judge'];
            if (($e['category'] == "in" or 'magistrate' == $e['judge'])) :
                ?><br><span class="text-muted"><?php echo $e['location'] ?: $e['aj_default_location'];?></span><?php
            endif;
            ?></td>
            <td><?php echo $e['language']?></td>
            <td class="text-nowrap"><?php echo substr($e['docket'], 2)?></td>
            <td class="defendants text-nowrap"><?php echo $this->defendants($e['id'])?></td>
            <td style="line-height: 1.2em; font-size: 95%"><?php echo $e['comments']?></td>
            <td class="interpreters-assigned text-nowrap"><?php echo $this->interpreters($e['id'])?></td>
        </tr>
            <?php endforeach;
        else :
            ?><tr><td colspan="8" class="text-center py-4 px-4 no-events">
        <div class="alert alert-info mx-auto">no events scheduled for this date and language.</div>
    </td></tr><?php
        endif;?>
    </tbody>
    <tfoot></tfoot>
</table>
