
<table id="schedule-table" class="table table-hover table-bordered table-sm rounded mt-2">
    <thead>
        <tr>
            <th>time</th>
            <th>type</th>
            <th>judge</th>
            <th>language</th>
            <th class="d-none d-lg-table-cell">docket</th>
            <th>defendants</th>
            <th class="d-sm-none d-lg-table-cell">notes</th>
            <th class="border-right-0">interpreters</th>
            <th class="border-left-0"></th>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->data) :
            foreach ($this->data['events'] as $e) :
                if (stristr($e['judge'], 'magistrate') !== false && ! $e['location']) :
                    $magistrate_default = $e['aj_default_location'];
                endif;
                ?>
        <tr data-id="<?php echo $e['id']?>" class="event-category-<?php echo str_replace(' ', '-', $e['category']) ?><?php
        if ($e['cancellation']) :
            echo " event-cancelled" ;
        endif;?>">
            <td class="text-right text-nowrap"><?php echo $e['time'] ? $e['time']->format('g:i a') : ''?></td>
            <td style="line-height:1.2em" class="py-2 clearfix"><?php /** this isn't really working that well... */?>
                <a class="link-edit-event" href="<?php echo $this->url('events/edit', ['id' => $e['id']]) ?>">
                    <span data-toggle="tooltip" title="edit this event" class="ml-1 float-right align-self-top fas fa-edit text-primary mr-2"> </span>
                    <span class="sr-only">edit this event</span>
                </a>
                <a data-toggle="tooltip" title="view event details" href="<?php echo $this->url('events/view', ['id' => $e['id']]);?>"><?php
                    echo $e['type']; ?><?php
                if ($e['location_type'] == 'jail' or ($e['location'] && $e['category'] == "not applicable")) :
                    ?><br><span class="text-muted"><?php echo $e['location'];?></span><?php
                endif;
                ?></a>
            </td>
            <td class="text-nowrap"><?php echo $e['judge'];
            if (($e['category'] == "in" or 'magistrate' == $e['judge'])) :
                 $location = $e['location'] ?: $e['aj_default_location'];
                 if ($location && $e['parent_location']): $location .= ", {$e['parent_location']}"; endif;
                ?><br><span class="text-muted"><?php echo $location ;?></span><?php
            endif;
            ?></td>
            <td><?php echo $e['language']?></td>
            <td class="text-nowrap d-none d-lg-table-cell"><?php echo substr($e['docket'], 2)?></td>
            <td class="defendants text-nowrap"><?php echo $this->defendants($e['id'])?></td>
            <td class="d-none d-lg-table-cell"style="line-height: 1.2em; font-size: 95%"><?php echo $e['comments']?></td>
            <td data-language_id="<?php echo $e['language_id']?>" class="interpreters-assigned text-nowrap border-right-0"><?php echo $this->interpreters($e['id'])?></td>
            <td class="border-left-0"><a class="edit-interpreters"  data-toggle="tooltip" data-container="tr[data-id=<?php echo $e['id'] ?>]" role="button" href="#"><span title="add or remove interpreters for this event" class="fas fa-edit"></span></a></td>
        </tr>
            <?php endforeach;
        else :
        ?><tr><td colspan="9" class="text-center py-4 px-4 no-events">
        <div class="alert alert-info mx-auto">no events scheduled for this date and language criterion.</div>
    </td></tr><?php
        endif;?>
    </tbody>
    <tfoot></tfoot>
</table>
