<?php
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;
$formAction = strstr($this->title,'add') ? $this->url('locations/add') 
	:  $this->url('locations/edit',['id' => $this->id ]);
$form = $this->form;
$form->add([
	'name'=>'submit',
	'type'=>'Zend\Form\Element\Submit',
	'attributes' => ['value'=>'submit'],
])->setAttribute('method', 'post')->setAttribute('action', $actionAttrib);

?>
<h2><?php echo $this->title ?></h2>

our form action will be <?=$formAction?>

<?php

$form->prepare();
echo $this->form()->openTag($form);?>
<div class="form-group"><?php 
$name = $form->get('name');
echo $this->formLabel($name),$this->formElement($name),$this->formElementErrors($name);
?>
<div class="form-group"><?php 
$location_type = $form->get('type'); 
echo $this->formLabel($location_type),$this->formElement($location_type),$this->formElementErrors($location_type);
?>
<div class="form-group"><?php 
echo $this->formSubmit($form->get('submit'));
echo $this->formElement($form->get('id'));
echo $this->form()->closeTag();
?>
</div>