<?php /**  locations/index view script */  ?>

<h2>locations</h2>

<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) : echo $messenger->render('success',['alert','alert-success',]); endif;
?>
<div class="list-group">
<p>Choose a type to display</p>
  <a href="#" class="list-group-item">courthouse</a>
  <a href="#" class="list-group-item">courtroom</a>
  <a href="#" class="list-group-item">probation office</a>
  <a href="#" class="list-group-item">pretrial services office</a>
  <a href="#" class="list-group-item">interpreters office</a>
  <a href="#" class="list-group-item">jail</a>
  <a href="#" class="list-group-item">holding cell</a>
  <a href="#" class="list-group-item">public area</a>
</div>