
<li id="deft-<?php echo $this->id ?>" class="list-group-item pr-0 py-0">
<span class="float-left pt-2 deft-name"><?php echo $this->name ?></span>
<input name="<?php echo $this->namespace ?>[defendants][]" value="<?php echo $this->id ?>" type="hidden">
<button class="btn btn-warning btn-remove-item float-right border" title="remove this defendant">
<span class="fas fa-times" aria-hidden="true"></span><span class="sr-only">remove this defendant</span></button>
</li>
