<?php
    if ($this->xtra_defendants) {
        // the input value should simply be the name
        $input_value = $this->name;
        // the element name should be 'extra_defendants'
        $element_name = 'extra_defendants';
    } else {
        $input_value = $this->id;
        $element_name = 'defendants';
    }
?>
<li id="deft-<?php echo $this->id ?>" class="list-group-item pr-0 py-0">
<span class="float-left pt-2 deft-name"><?php echo $this->name ?></span>
<input name="<?php echo $this->namespace ?>[<?php echo $element_name ?>][]" value="<?php echo $input_value ?>" type="hidden">
<button class="btn btn-warning btn-remove-item float-right border" title="remove this defendant">
<span class="fas fa-times" aria-hidden="true"></span><span class="sr-only">remove this defendant</span></button>
</li>
