<form class="form-inline"  id="form-login" action="<?php echo $this->url('login') ?>" method="post">
    <div class="form-group">
      <label class="sr-only" for="identity">username or email</label>
            <?php echo $this->formElementErrors($this->form->get('identity'))?>
        <?php echo $this->formElement($this->form->get('identity')); //return; ?>
    </div>
    <div class="form-group pl-1">
      <label class="sr-only" for="password">password</label>
            <?php echo $this->formElementErrors($this->form->get('password')) ?>
            <?php echo $this->formElement($this->form->get('password')); //return; ?>
    </div>
      <button type="submit" class="btn btn-success ml-1">log in</button>
        <?php echo $this->formElement($this->form->get('login_csrf')) ?>
        <?php echo $this->formElementErrors($this->form->get('login_csrf')) ?>
 </form>
