<?php /** based on https://stackoverflow.com/questions/14884572/zend-framework-2-navigation-menu-twitter-bootstrap-integration */
$route = $this->layout()->routeMatch;?>
<ul class="navbar-nav mr-auto"><?php
/* @var $page Laminas\Navigation\Page\Mvc */
foreach ($this->container as $page) :
    $label = $page->getLabel();
    $active = false;
    if ( $label == $route or ($page->route_matches && in_array($route,$page->route_matches))):
        $active = true;
    endif;
    // when using partials we need to manually check for ACL conditions
    if (false === $page->display || !$page->isVisible() || !$this->navigation()->accept($page)) :
        continue;
    endif;
    if ($label == 'search'): // this one is a special case ?><?php //if ($active):.. //endif;?>
        <li class="nav-item dropdown <?php if ($active): ?> active<?php endif;?>" id="nav-search"><a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">search</a>
            <div class="dropdown-menu"  style="max-width:250px;min-width:200px" >
                <div class="px-2" method="get">
                    <div class="input-group">
                        <input class="form-control" type="text" name="docket" placeholder="docket #" value="">
                        <div class="input-group-append">
                            <a id="btn-docket-search" href="<?php echo $this->url($page->route)?>" role="button" class="btn btn-primary">
                                <span class="fa fa-search"></span>
                                <span class="sr-only">search</span>
                            </a>
                        </div>
                    </div>
                    <div class="validation-error alert alert-warning" style="display:none"></div>
                </div>
                <a href="<?php echo $this->url($page->route)?>" class="dropdown-item pl-3">advanced search</a>
            </div>
        </li>
    <?php continue;  endif;
    if (! $page->hasPages() or false === $page->expand_children ) :
?><li class="nav-item<?php if ($active): ?> active<?php endif; if ($page->css_class): echo " $page->css_class";endif ?>"><a title="<?php if ($page->title): echo $page->title; endif ?>" class="nav-link" href="<?php echo $page->getHref() ?>"><?php echo $label ?></a></li>
<?php else :
?><li class="nav-item dropdown">
    <a title="<?php if ($page->title): echo $page->title; endif ?>" href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><?php echo $page->getLabel() ?> <b class="caret"></b></a>
    <div class="dropdown-menu"><?php
     //echo "fuck? ",count($page->getPages());
     /** sort the pages */
     $child_pages = $page->getPages();
     usort($child_pages, function($a,$b){
         if ($a->order == $b->order) { return 1; }
         return ($a->order < $b->order) ? -1 : 1;
     });
     foreach ($child_pages as $child) : ?>
        <?php
        if (!$child->isVisible() || !$this->navigation()->accept($child)) :
            continue;
        endif;
        $label = $child->getLabel();
            if ( $label == $route or ($child->route_matches && in_array($route,$child->route_matches))):
             $active = true;
         else:
             $active = false;
         endif;

        ?><a <?php if ($child->id): printf('id="%s" ',$child->id); endif;?>title="<?php
            if ($child->title): echo $child->title; endif ?>" class="dropdown-item<?php if ($active): ?> active<?php endif; ?>" href="<?php
                echo $child->getHref() ?>"><?php echo $child->getLabel() ?></a>
    <?php
        if ($child->divider) : ?><div class="dropdown-divider"></div><?php endif;
    endforeach; ?>
    </div>
</li>
<?php endif; ?>
<?php endforeach;?>
</ul>
