<?php
/**
 * module/InterpretersOffice/view/partials/pagination_control.phtml
 * pagination control, partial view script for presenting links to paginated query
 * results. based on:
 * https://zf2.readthedocs.org/en/latest/tutorials/tutorial.pagination.html
 */

if ($this->pageCount < 2) :
    return;
endif;

$url = $this->url($this->route, $this->params ?: [],$this->query ? ['query'=>$this->query]:null);
$SEP = $this->query ? '&' : '?';
?>
<nav class="mb-1">
<ul class="pagination">
<?php if ($this->first < $this->firstPageInRange) : ?>
<li class="page-item"><a class="page-link" href="<?php echo "{$url}{$SEP}page=$this->first"  ?>">&lt;&lt;</a></li>
<?php endif?>
<?php if (isset($this->previous)) : ?>
  <li class="page-item"><a class="page-link" title="previous page" href="<?php echo "$url{$SEP}page=$this->previous" ?>">&lt;</a></li>
<?php else :
?><li class="disabled"><span class="page-link">&lt;</span></li>
<?php endif; ?>
<?php foreach ($this->pagesInRange as $page) : ?>
    <?php if ($page != $this->current) : ?>
    <li class="page-item"><a class="page-link" href="<?php echo "{$url}{$SEP}page=$page"; ?>"><?php echo $page; ?></a></li>
    <?php else : ?>
    <li class="page-item active"><span class="page-link"><?php echo $page; ?></span></li>
    <?php endif; ?>
<?php endforeach; ?>
<!-- Next page link -->
<?php if (isset($this->next)) : ?>
  <li class="page-item"><a class="page-link" href="<?php echo "{$url}{$SEP}page={$this->next}"; ?>">&gt;</a></li>
<?php else : ?>
  <li class="disabled"><span class="page-link">&gt;</span></li>
<?php endif; ?>
<?php if ($this->last > $this->lastPageInRange) : ?>
<li class="page-item"><a class="page-link" title="last page of results" href="<?php echo "{$url}{$SEP}page=$this->last"?>">&gt;&gt;</a></li>
<?php endif?>
</ul>
</nav>
