<?php
/**
 * view script for email sent to Interpreters Office when Spanish interpreter
 * auto-cancel is triggered. this happens when they either (1) cancel outright
 * or (2) reschedule a request across an am/pm boundary or (3) (rarely occuring)
 * they  change the language from Spanish to something else. In any of these cases
 * the Spanish interpreters are automatically cancelled but they are NOT
 * automatically notified.
 */

/*
{
  "cancel": {
    "in-court.spanish.delete-scheduled-event": true,
    "in-court.spanish.notify-assigned-interpreters": false,
    "out-of-court.spanish.delete-scheduled-event": true,
    "out-of-court.spanish.notify-assigned-interpreters": true,
    "out-of-court.non-spanish.delete-scheduled-event": true,
    "out-of-court.non-spanish.notify-assigned-interpreters": true
  },
  "change-date": {
    "all-events.all-languages.update-scheduled-event": true,
    "all-events.all-languages.remove-interpreters": true,
    "all-events.all-languages.notify-assigned-interpreters": true
  },
  "change-x-am-pm": {
    "all-events.all-languages.update-scheduled-event": true,
    "all-events.all-languages.notify-assigned-interpreters": true,
    "all-events.all-languages.remove-interpreters": true
  },
  "change-within-am-pm": {
    "in-court.spanish.update-scheduled-event": true,
    "in-court.spanish.notify-assigned-interpreters": true,
    "in-court.spanish.remove-interpreters": false,
    "in-court.non-spanish.update-scheduled-event": true,
    "in-court.non-spanish.notify-assigned-interpreters": true,
    "in-court.non-spanish.remove-interpreters": false,
    "out-of-court.spanish.update-scheduled-event": true,
    "out-of-court.spanish.notify-assigned-interpreters": true,
    "out-of-court.spanish.remove-interpreters": false,
    "out-of-court.non-spanish.update-scheduled-event": true,
    "out-of-court.non-spanish.notify-assigned-interpreters": true,
    "out-of-court.non-spanish.remove-interpreters": false
  },
  "change-language": {
    "all-events.all-languages.update-scheduled-event": true,
    "all-events.all-languages.notify-assigned-interpreters": true,
    "all-events.all-languages.remove-interpreters": true
  },
  "update-other-attributes": {
    "all-events.all-languages.update-scheduled-event": true
  }
}
 */
if ($this->interpreters):
    $plural =  count($this->interpreters) > 1;
endif;
$this->entity = [
    'date' =>  $this->request->getDate(),
    'time' =>  $this->request->getTime(),
    'language' => (string)$this->request->getLanguage(),
    'eventType' =>  (string)$this->request->getEventType(),
    'location' =>  (string)$this->request->getLocation(),
    'docket'  => $this->request->getDocket(),
    'comments' => $this->request->getComments(),
    'judge' =>  (string)$this->request->getJudge(),
    'extraData' => $this->request->getExtraData(),
    'defendants' => $this->request->getDefendants()->toArray(),
];

?>

<p>
This automated message is to inform you that user <?php echo "{$this->user->firstname} {$this->user->lastname}"?> has just
<?php echo $this->user_event == 'cancel' ? "<strong>cancelled</strong>" : "modified" ?>
the following request for interpreting services. As a result, the corresponding
event on the schedule was automatically <?php echo $this->user_event == 'cancel' ? "deleted" : "updated" ?>.
</p>
<?php if ($this->interpreters):?>
<p>Also, please note that the following <?php echo $plural ? 'interpreters were ':'interpreter was'  ?> deleted,
    and automatic email-notification to interpreters in such cases is disabled. Therefore, it's up to you
    to contact  <?php echo $plural ? 'this interpreters':'these interpreters' ?> if you wish to do so:
</p>
<p style="padding-left:2em;">
    <?php foreach ($this->interpreters as $i):
        echo "{$i->getFirstName()} {$i->getLastname()} ",$this->escapeHtml('<'.$i->getEmail().'>'),'<br>';
        ?>
    <?php endforeach;?>
</p>
<?php endif;?>
<table>
    <?php foreach (array_keys($this->entity) as $field):?>
    <tr style="border-bottom:1px dotted gray">
        <td><?php echo $field?></td>
        <td><?php echo $this->diff($field)?></td>
    </tr>
<?php endforeach ?>
</table>
<p>
    user action is: <?php echo $this->user_event ?>. request is a <?php
     echo gettype($this->request)
    ?>
    interpreters? <?php echo gettype($this->interpreters); if (is_array($this->interpreters)):
        echo " ",count($this->interpreters);
        $i = $this->interpreters[0];
        ?>
        <p><?php echo $i->getEmail() ?>
        </p>
        <?php
    endif;?>
</p>
<!--
<p>
Please note that the following interpreter request has been <?php
//echo $this->request_cancelled ? "cancelled" : "modified" ?> by
<?php // echo $this->request->getModifiedBy()->getFullName() ?>.
As a result, the corresponding event has been automatically
<?php //echo $this->request_cancelled ? "deleted" : "updated accordingly" ?>
and the interpreter<?php //echo $plural? 's have been' : ' has been' ?> <strong>removed</strong>.
</p>
<p>However, as of this writing, <strong>the interpreter<?php //echo $plural ? 's have' : ' has'?> yet to be notified of
    this cancellation</strong> so that you have an opportunity to decide the appropriate action.
</p>
-->
<?php
/*
if ($this->request_cancelled): // a cancellation
    echo $this->partial('partials/email/event-details.phtml',
    [  'event'=>$this->event,
      'interpreters_cancelled'=>$this->interpreters_cancelled ]
    );
else: // an update
    echo $this->partial('requests/email/partials/request-details.diff.phtml',
  [
      'request'=>$this->request,
      'changeSet'=>$this->changeSet,
      'notificationService'=>$this->notificationService,
  ]);
endif
*/
?>
