<?php
/**
 *
 * view script for sending email when a request is updated.
 *
 * TO BE CONTINUED
 *
 * 
 *
 *
 *
 */
?>
<p><!-- <?php echo basename(__FILE__);?> -->

</p>
<?php
// echo $this->partial('requests/email/partials/request-details.diff.phtml',
//   [   'request'=>$this->request,
//       'interpreters_cancelled' => $this->interpreters_cancelled,
//       'changeSet'=>$this->changeSet,
//       'notificationService'=>$this->notificationService,
//       $this->interpreters_cancelled
// ]);
