<?php
/**
 * view script/email template for automatically sending update notice to interpreters
 * when a request undergoes certain changes
 *
 * idea:  a button in the message linked to a script at sdnyinterpreters.org,
 * with a token in the url that triggers an email on their behalf and says thanks
 */
?>
<p>Dear <?=$this->interpreter?>:</p>

<p>This is to advise you that the following event to which you were assigned in the Southern District of New York
<strong>has been cancelled</strong>.</p>

<p style="font-size:115%;"><em>Please reply to the Interpreters Office at your earliest convenience to acknowledge this notice.</em></p>

<?php
// echo $this->partial('partials/email/event-details.phtml',
//   [   'event'=>$this->event,
//       'interpreters_cancelled'=>$this->interpreters_cancelled ]
// );
?>

<p>Very truly yours,</p>

<p>SDNY Interpreters Office</p>
