<?php /**  module/InterpretersOffice/view/interpreters-office/email/password_reset.phtml */?>
<p>Hello,</p>
<p>
We received a request to reset the password for your user account. If you would
like to reset your password, please hit this button:
</p>
<p style="text-align:center">
    <a href="<?php echo $this->url ?>">
        <button style="font-size:125%;border-radius: 4px; cursor:pointer; border: 1px solid #dee2e6;background-color:#32a5e6;color:white;padding:1em;" type="button" name="button">
            <strong>reset password</strong>
        </button>
    </a>
</p>
<p><?php //echo $this->url ?></p>

<p>Note that this link expires in 30 minutes. If you do not need to reset
your password, you can simply ignore this message.</p>

<p>Thank you,</p>

<p>The Interpreters Office</p>
