<?php
$action = $this->layout()->action;
$type = $this->type;
$this->headTitle("$action $type");
$this->headScript()->appendFile($this->basePath('js/admin/notes-form.js'));
$method = $action == 'create'?'POST':'PUT'?>
<div class="mx-auto" style="max-width:800px">
<?php
if ('edit' == $action and ! $this->note):
    ?>
    <div class="alert alert-warning border border-danger">
        Shit was not found.
    </div>
<div>
    <?php return;
endif;
?>
    <h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?> <?php echo $type?></h2>

    <form data-type="<?php echo $this->type?>" class="ml-auto mr-auto mt-3" id="notes-form" action="/admin/notes/<?php echo $action?>" method="<?php echo $method?>">
        <div class="row">
            <div class="col offset-sm-2">
                <h4><?php printf('%s for %s',$type,$this->date->format('D d-M-Y'))?></h4>
            </div>
        </div>
        <div class="form-row">
            <label class="col-sm-2 col-form-label text-md-right pr-1" for="content">text of <?php echo $type ?></label>
            <div class="col">
                <textarea class="form-control" name="content" id="note-content" placeholder="Enter text here. You can use markdown" rows="6" cols="60"></textarea>
            </div>
        </div>
        <div class="form-row">
            <div class="col offset-sm-2 pt-2">
                <button type="button" class="btn btn-success">save</button>
            </div>
        </div>
    </form>
</div>
