<?php
$action = $this->layout()->action;
$type = $this->type;
$this->headTitle("$action $type");
// $this->headScript()->appendFile($this->basePath('js/admin/notes-form.js'));
$method = $action == 'create'?'POST':'PUT'?>
<div class="mx-auto" style="max-width:800px">
<?php
if ('edit' == $action and ! $this->note):
    ?>
    <div class="alert alert-warning border border-danger">
        The <?php echo $type ?> was not found in the database.
    </div>
<div>
    <?php return;
endif;
?>
    <h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?> <?php echo $type?></h2>
    <div class="row">
        <div class="col offset-sm-2">
            <h4><?php printf('%s for %s',$type,$this->date->format('D d-M-Y'))?></h4>
        </div>
    </div>
    <?php echo $this->partial('notes/partials/form.phtml',[
        'date'=>$this->date,'type'=>$this->type,'note'=> $this->note,
         'csrf'=>$this->csrf,
    ]); ?>
</div>
