<?php $this->headTitle('Notes (MOT[DW]');
$this->headScript()
    ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
    ->appendFile($this->basePath('js/admin/notes-form.js'));
?>
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
<pre class="border p-1">
layout->action is <?php echo $this->layout()->action ?>

$this->date is <?php echo $this->date->format("D d-M-Y");?>

$this->notes:
<?php if ($this->notes) 
{
    foreach ($this->notes as $k => $v) {
        printf ("key is $k, value type is %s",gettype($v));
        if ($v) {
            printf("... with date: %s",$v->getDate()->format("D Y-m-d"));
        }
        echo "\n";
    }
} else {
    echo gettype($this->notes),"\n";
}
printf("our action is <strong>%s</strong> for type <strong>%s</strong>; monday is initially %s",
    ($this->action ?: $this->layout()->action),
    $this->type ?: 'N/A', $this->monday ? $this->monday->format('l Y-m-d') : "null"
);
// return;
?>
</pre>

<div class="row border-bottom mb-2 pb-2">
    <div id="motd-content" class="note-content col">
        <?php $motd_date = $this->notes['motd'] ? $this->notes['motd']->getDate() : $this->date  ?>
        <h4>MOTD for <?=$motd_date->format('l d-M-Y')?></h4>
        <?php if ($this->notes['motd']): ?>
            <?php $note = $this->notes['motd'];
                if ($this->action != 'index' && $this->type == 'motd') :
                    echo $this->partial('notes/partials/form.phtml',[
                    'date'=>$this->date,'type'=>$this->type,'note'=> $this->notes['motd'],
                    'csrf'=>$this->csrf,'action' =>$this->action,
                    ]);                    
                elseif ($note->getId()):
                    echo $note->getContent();
                    ?>
                    <a class="btn btn-primary fas fa-edit" id="btn-editor-motd" role="button" href="/admin/notes/edit/motd/<?=$note->getId()?>/date/<?=$note->getDate()->format('Y-m-d')?>"><span class="sr-only">edit</span></a>
                    <?php         
                else :
                    ?>no MOTD for <?php echo $this->date->format('l d-M-Y');
                endif;
            else:
                ?>no MOTD for <?php echo $this->date->format('l d-M-Y');
            endif;        
        ?>
    </div>
    <div class="col">
        <div data-date="<?=$this->date->format('Y-m-d')?>" id="calendar-motd"></div>
    </div>
</div>
<div class="row pt-3">
    <div id="motw-content" class="note-content col">
    <h4>MOTW for <?=$this->monday->format('l d-M-Y')?></h4>
    <?php if ($this->notes['motw']):  ?>
            <?php $note = $this->notes['motw'];
            if ($this->action != 'index' && $this->type == 'motw') :
                echo $this->partial('notes/partials/form.phtml',[
                    'date'=>$this->monday,'type'=>$this->type,'note'=> $note,
                    'csrf'=>$this->csrf,'action' =>$this->action,
                    ]);
        elseif ($note->getId()):?>
            <?php echo $note->getContent();?>
               <a class="btn btn-primary fas fa-edit" id="btn-editor-motw" role="button" href="/admin/notes/edit/motw/<?=$note->getId()?>/date/<?=$note->getDate()->format('Y-m-d')?>"><span class="sr-only">edit</span></a>
        <?php  else:?>          
        <?php
            ?>no MOTW for <?php echo $this->monday->format("D Y-m-d");
        endif;
    else:?>        
        no MOTW for <?php echo $this->monday->format('D d-M-Y'); ?>
    <?php endif  ?>

    </div>
    <div class="col"><div data-date="<?=$this->monday->format('Y-m-d')?>" id="calendar-motw"></div></div>
</div>