<?php $this->headTitle('Notes (MOT[DW]');
$this->headScript()
    ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
    ->appendFile($this->basePath('js/admin/notes-form.js'));
?>
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
<pre class="border p-1">

<br>layout->action is <?php echo $this->layout()->action ?>
<br>$this->date is <?php echo $this->date->format("D d-M-Y");?>
<br>$this->notes:
<?php if ($this->notes) 
{
    foreach ($this->notes as $k => $v) {
        printf ("key is $k, value type is %s",gettype($v));
        if ($v) {
            printf("... with date: %s",$v->getDate()->format("D Y-m-d"));
        }
        echo "\n";
    }
} else {
    echo gettype($this->notes),"\n";
}
printf("our action is <strong>%s</strong> for type <strong>%s</strong>; monday is initially %s",
    ($this->action ?: $this->layout()->action),
    $this->type ?: 'N/A', $this->monday ? $this->monday->format('D Y-m-d') : "null"
);

?>
</pre>

<div class="row">
    <div class="col">data MOTD:<br>
        <?php if ($this->notes['motd']): ?>
            <?php $note = $this->notes['motd'];
                if ($this->action != 'index' && $this->type == 'motd') :
                    ?><br>display form to <?=$this->layout()->action?>
                     <?php echo $this->type ?> id <?php echo $note->getId()?>
                     <?php echo $this->partial('notes/partials/form.phtml',[
                    'date'=>$this->date,'type'=>$this->type,'note'=> $this->notes['motd'],
                    'csrf'=>$this->csrf,'action' =>$this->action,
                    ]);                    
                elseif ($note->getId()):
                    echo $note->getContent();
                else :
                    ?>no MOTD for <?php echo $this->date->format('D d-M-Y');
                endif;
         endif;        
        ?>
    </div>
    <div class="col">cal</div>
    <div class="col">data MOTW:<br>
    <?php if ($this->notes['motw']):  ?>
            <?php $note = $this->notes['motw'];
            if ($this->action != 'index' && $this->type == 'motw') :
                ?><br>display the form to <?=$this->layout()->action ?> a <?=$this->type ?>
                for <?= $note->getDate()->format('D d-M-Y');?>
                <?php echo $this->partial('notes/partials/form.phtml',[
                    'date'=>$this->monday,'type'=>$this->type,'note'=> $note,
                    'csrf'=>$this->csrf,'action' =>$this->action,
                    ]);
        elseif ($note->getId()):            
            echo $note->getContent();
        else:
            ?> ? no MOTW for <?php echo $this->monday->format("D Y-m-d");
        endif;
    endif;
        ?>

    </div>
    <div class="col">cal</div>
</div>