<?php
$this->headTitle('admin | rotations');
$this->headScript()->appendFile($this->basePath('js/admin/tasks-form.js'));
?>
<div class="mx-auto" style="max-width:800px">
    <h2 class="mb-4"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
    <form id="rotation-form" action="<?= $this->basePath()?>/admin/rotations/assignments/create" method="post">
        <div class="form-group row">
            <label class="col-form-label col-sm-3" for="task">
                task
            </label>
            <div class="col-sm-6">
                <select id="task" name="task" class="form-control">
                    <option label="" value=""></option>
                    <?php foreach ($this->tasks as $t) :?>
                    <option label="<?= $this->escapeHtml($t->getName()) ?>" value="<?=$t->getId()?>"<?php
                    if ($this->task_id == $t->getId()):?> selected<?php endif;
                    ?>><?= $this->escapeHtml($t->getName()) ?></option>
                <?php endforeach;?>
                </select>
            </div>
        </div>
        <?php echo $this->partial('partials/rotation-components.phtml',[])?>
        <div class="form-group row">
            <div class="offset-sm-3 pl-3">
                <button type="button" id="btn-save" name="button" class="btn btn-success">save</button>
            </div>

        </div>
        <?php $hash = (new \Zend\Validator\Csrf(['timeout'=>6000]))->getHash() ?>
        <input type="hidden" name="csrf" value="<?=$hash?>">
    </form>
</div>
