<?php
$this->headTitle('admin | rotations');
$this->headScript()->appendFile($this->basePath('js/admin/tasks-form.js'));
?>
<div class="mx-auto" style="max-width:800px">
    <h2 class="mb-4"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
    <div class="alert alert-warning" style="display:none">
        <p id="error-message"></p>
    </div>
    <form class="task-rotation" id="rotation-form" action="<?= $this->basePath()?>/admin/rotations/assignments/create" method="post">
        <div class="form-group row">
            <label class="col-form-label col-sm-3" for="task">
                task
            </label>
            <div class="col-sm-6">
                <select id="task" name="rotation[task]" class="form-control">
                    <option label="" value=""></option>
                    <?php foreach ($this->tasks as $t) :?>
                    <option label="<?= $this->escapeHtml($t->getName()) ?>" value="<?=$t->getId()?>"<?php
                    if ($this->task_id == $t->getId()):?> selected<?php endif;
                    ?>><?= $this->escapeHtml($t->getName()) ?></option>
                <?php endforeach;?>
                </select>
            </div>
        </div>
        <?php echo $this->partial('partials/rotation-components.phtml',[])?>
        <div class="form-group row">
            <div class="offset-sm-3 pl-3">
                <button type="button" id="btn-save" name="button" class="btn btn-success">save</button>
            </div>

        </div>
        <?php $hash = (new \Zend\Validator\Csrf(['timeout'=>6000]))->getHash() ?>
        <input type="hidden" name="csrf" value="<?=$hash?>">
    </form>
    <div class="row">
        <div class="col-sm-7 offset-sm-2 alert alert-info">
            <strong>Please note:</strong> This feature should be used with care. There is presently
            no means of modifying or removing task rotations once they have been created, short of
            editing the underlying database directly.
        </div>
    </div>
</div>
<div id="dialog" aria-labelledby="dialog-title" style="display:none" class="modal" role="dialog" tabindex="-1">
    <div class="modal-dialog" role="document" >
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="dialog-title">please confirm rotation</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" id="btn-confirm" class="btn btn-primary">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>
