<?php
$this->headScript()->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
->appendFile($this->basePath('js/admin/tasks.js'));
$this->headTitle('admin| rotations | view details');
if ($this->task):
    $header = $this->escapeHtml($this->task->getName());
    $rotations = $this->task->getRotations();
else:
    $header = 'view';
endif;
?>
<div style="max-width:800px" class="mx-auto">
    <h2 class="mb-4"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() . $header?></h2>
    <div class="row">
        <div class="col">
            <div class="row task" data-task_id="<?= $this->task->getId()?>"
              data-dow="<?=  $this->escapeHtml($this->task->getDayOfWeek())?>"
              data-task_frequency="<?php echo $this->escapeHtml($this->task->getFrequency()) ?>">
                <div class="col-md-3 pr-1"><div class="float-md-right">name</div>
                </div>
                <div class="col-md-9">
                    <?php echo $this->escapeHtml($this->task->getName()) ?>
                </div>
                <div class="col-md-3 pr-1 py-1"><div class="float-md-right">assigned</div>
                </div>
                <div class="col-md-9 current-assignment border border-warning rounded pl-3 pr-1 py-1">
                <?php
                if ($this->current['assigned']) :
                    $name = $this->escapeHtml($this->current['assigned']);
                    $date = $this->current['date'];
                    if (!$date instanceof \DateTimeInterface) :
                        $date = (new \DateTime($date))->format('D d-M-Y');
                    endif;
                    ?>
                    <span class="assignment-date"><?= $date ?>:</span>
                    <span class="assignment-person"><?php
                    if ($this->current['assigned'] != $this->current['default']):
                        ?><span style="text-decoration:line-through"><?= $this->escapeHtml($this->current['default'])?></span>
                    <?php
                    endif;
                    echo  $name
                    ?>
                    </span>
                <?php
            else: $name = ''?>
            <span class="assignment-date"></span>
            <span class="assignment-person text-muted">(nobody)</span>
            <?php
                endif;?>
                <button data-toggle="modal" data-target="#dialog" class="btn btn-primary btn-sm float-right py-0"><span class="fas fa-edit"></span><span class="sr-only"></span></button>
                </div>
                <div class="col-md-3 pr-1"><div class="float-md-right">description</div>
                </div>
                <div class="col-md-9">
                    <?php echo $this->escapeHtml($this->task->getDescription())?:'<span class="text-muted">(none)</span>' ?>
                </div>
                <div class="col-md-3 pr-1"><div class="float-md-right">sequence</div>
                </div>
                <div class="col-md-9 rotation"><?php
                    $current = $rotations->get(0);
                    if ($current):
                        foreach($current->getMembers() as $m):
                            echo $this->escapeHtml($m->getPerson()->getFullName()),'<br>';
                        endforeach;
                    else:
                        ?><span class="text-muted">(none)</span><?php
                    endif;
                ?></div>
                <div class="col-md-3 pr-1">
                    <div class="float-md-right">start date</div>
                </div>
                <div class="col-md-9 start_date"><?php
                  if ($current): echo $current->getStartDate()->format('d M Y');
                  else: ?><span class="text-muted">(n/a)</span><?php
                  endif;
                ?></div>
                <div class="offset-md-3 col-md-9 pt-2">
                    <button type="button" data-toggle="modal" data-target="#dialog" class="btn btn-outline-primary btn-sm">do shit</button>
                </div>
            </div>
        </div>
        <div class="col">
          <span class="text-muted">see who is assigned for a given date</span>
          <div id="calendar"></div>
        </div>
    </div>
</div><!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary" >
  Launch demo modal
</button> -->

<!-- Modal -->
<div class="modal" id="dialog" tabindex="-1" role="dialog" aria-labelledby="dialog-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="dialog-label">edit assignment: <span class="task-assignment"><?= $this->escapeHtml($this->task->getName())?> </span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Replace <span class="assignment-person"><?= $name ?></span> with:
         <select class="" name="">
             <option value="eenie">eenie</option>
             <option value="meenie">meenie</option>
             <option value="mienie">mienie</option>
         </select>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-primary">save</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">cancel</button>
      </div>
    </div>
  </div>
</div>
