<?php
use InterpretersOffice\Admin\Form\View\Helper\LanguageElementCollection;
/**
 *  module/Admin/view/interpreters-office/admin/people/form.phtml
 *  view script for rendering interpreters create|update form
 */
$this->headTitle('admin | interpreters | '.$this->layout()->action);
$this->headLink()->appendStylesheet($this->basePath('css/jquery-bootstrap-datepicker.css'));
$this->headScript()
        ->appendFile($this->basePath('js/lib/modernizr-custom.js'))
        ->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'))
        ->appendFile($this->basePath('js/common.js'))
        ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
        ->appendFile($this->basePath('js/interpreter-form.js'));

if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;
$formAction = $this->layout()->action == 'add' ? $this->url('interpreters/add')
    : $this->url('interpreters/edit', ['id' => $this->id ]);

$form = $this->form;
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
     'attributes' => ['value' => 'save','class'=>'btn btn-success btn-lg'],
])->setAttribute('method', 'post')
   ->setAttribute('action', $formAction)
   ->setAttribute('class', 'form-horizontal');
?>
<div class="center-block" style="max-width:900px"><!-- wrapper -->
<h2><?php echo $this->navigation('default')->breadcrumbs() ?></h2>

<?php
$form->prepare();
$fieldset = $form->get('interpreter');
echo $this->form()->openTag($form);?>


<!-- Nav tabs --><!-- -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="true">contact</a>
  </li>
  <li class="nav-item">
      <a class="nav-link" id="languages-tab" data-toggle="tab" href="#languages" role="tab" aria-controls="shit" aria-selected="false">languages &amp; notes</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="administrative-tab" data-toggle="tab" href="#administrative" role="tab" aria-controls="administrative" aria-selected="false">administrative/security</a>
  </li>  
</ul>
<!--  -->
<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane pt-3 active" id="contact" role="tabpanel" aria-labelledby="contact-tab"><!-- contact -->
        <?php foreach (['lastname','firstname','middlename','email','officePhone','mobilePhone','homePhone',
                    'address1','address2','city','state', 'zip'  ] as $elementName) :
                        $element = $fieldset->get($elementName);
               ?><div class="form-group form-row">
                    <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
                    <div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element) ?>
                    </div>
                </div>
        <?php endforeach; ?>        
    </div><!-- /contact -->
    <div class="tab-pane pt-3" id="languages" role="tabpanel" aria-labelledby="languages-tab">
          <div class="form-group"><?php // select element for choosing languages //?>               
            <div class="col-sm-10 col-sm-offset-2 form-inline"><?php 
                    $languageSelect = $fieldset->get('language-select'); 
                    echo $this->formSelect($languageSelect),$this->formElementErrors($languageSelect) ;
                    ?><button id="btn-add-language" class="btn btn-info" title="add this language">
                        <span class="fa fa-plus" aria-hidden="true"></span>
                        <span class="sr-only">add language</span></button><?php                    
                     /** @todo display fieldset validation errors ? */
           ?></div>
        </div>
        <div class="form-group panel panel-default" id="languages-div">
        <?php 
        $collection = $fieldset->get('interpreterLanguages');
        $helper = (new LanguageElementCollection())->setView($this);
        echo $helper();
        $collectionErrors = $this->formElementErrors($collection);
        if (stristr($collectionErrors, 'language is required')) :
            echo $collectionErrors;
        endif;
        ?>
        </div><!-- /languages-div -->       
    </div>
  <div class="tab-pane" id="administrative" role="tabpanel" aria-labelledby="administrative-tab">shit here is concerning administrative shit</div>

</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
<br><br><br>
 
<?php return;
$form->prepare();
$fieldset = $form->get('interpreter');
echo $this->form()->openTag($form);?>
<!-- nav tabs -->
<ul class="nav nav-tabs" id="nav-tabs"  id="interpreter-tabs" role="tablist">
    <li role="presentation"><a href="#contact" aria-controls="contact" role="tab" data-toggle="tab"  aria-selected="true">contact info</a></li>
    <li role="presentation"><a href="#languages-pane" aria-controls="languages-pane" role="tab" data-toggle="tab">languages &amp; notes</a></li>
    <li role="presentation"><a href="#administrative" aria-controls="administrative" role="tab" data-toggle="tab">administrative/security</a></li>
</ul>
<!-- /nav tabs -->
<div class="tab-content" style="padding-top: 1em">
    <div class="tab-pane" role="tabpanel"  id="contact"><!-- contact -->
        <?php foreach (['lastname','firstname','middlename','email','officePhone','mobilePhone','homePhone',
                    'address1','address2','city','state', 'zip'  ] as $elementName) :
                        $element = $fieldset->get($elementName);
               ?><div class="form-group">
                    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
                    <div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element) ?>
                    </div>
                </div>
            <?php endforeach; ?>
            <!-- end "contact" form elements -->
    </div><!-- /#contact ================================================================================ -->
    <div role="tabpanel" class="tab-pane" id="languages-pane">
        <div class="form-group"><?php // select element for choosing languages //?>               
            <div class="col-sm-10 col-sm-offset-2 form-inline"><?php 
                    $languageSelect = $fieldset->get('language-select'); 
                    echo $this->formSelect($languageSelect),$this->formElementErrors($languageSelect) ;
                    ?><button id="btn-add-language" class="btn btn-info" title="add this language">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        <span class="sr-only">add language</span></button><?php                    
                     /** @todo display fieldset validation errors ? */
           ?></div>
        </div>
        <div class="form-group panel panel-default" id="languages-div">
        <?php 
        $collection = $fieldset->get('interpreterLanguages');
        $helper = (new \InterpretersOffice\Admin\Form\View\Helper\LanguageElementCollection())->setView($this);
        echo $helper();
        $collectionErrors = $this->formElementErrors($collection);
        if (stristr($collectionErrors, 'language is required')) :
            echo $collectionErrors;
        endif;
            ?>
            
        </div><!-- /#languages .form-group -->
       <?php $element = $fieldset->get('comments');?>
       <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
       <div class="col-sm-9 form-inline" style="margin-bottom:1em"><?php echo $this->formElement($element), $this->formElementErrors($element)?>
       </div>
    </div><!-- /#languages-pane ================================================================================ -->
    <div role="tabpanel" class="tab-pane" id="administrative">
        
        <?php foreach (['hat','active','fingerprintDate','securityClearanceDate','contractExpirationDate','oathDate',] as $elementName):
                    $element = $fieldset->get($elementName);
                    $value = $element->getValue();
                    if (is_object($value) && $value instanceof \DateTime) {
                        $element->setValue($value->format('m/d/Y'));
                    }
         ?>
                <div class="form-group">
                    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
                    <div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element)                   ?>
                    </div>
                </div>
                <?php endforeach; ?>
                <!-- They say: 
                    "Do not mix form groups or grid column classes directly with input groups. 
                    Instead, nest the input group inside of the form group or grid-related element."
                -->
                <?php 
                if (! $this->obscure_values) : // regular plain-text elements
                    foreach (['dob','ssn'] as $elementName) : 
                        if (! $fieldset->has($elementName)) {
                            continue;
                        }
                        $element = $fieldset->get($elementName); 
                ?>
                <div class="form-group">
                    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
                    <div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element) ?></div>
                </div><?php
                    endforeach;
                else:  // should be obscured until they re-authenticate/decrypt             
                    foreach (['dob','ssn'] as $elementName) :
                        if (! $fieldset->has($elementName)) : break; endif;
                    $element = $fieldset->get($elementName);?>
                <div class="form-group">
                    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
                    <?php $encrypted = $element->getValue();
                    if (! $encrypted): // nothing to obscure
                        ?><div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element) ?></div><?php
                    else:  // display text inputs as encrypted/disabled
                        $element->setAttribute('disabled','disabled');?>
                    <div class="col-sm-9 form-inline encrypted">
                        <?php 
                            $element->setValue('**************');
                        ?><div class="input-group-btn"><?php echo $this->formElement($element)?><button data-toggle="modal" data-target="#login-modal" title="re-authenticate to view or edit sensitive data fields" class="btn btn-default" type="button"><span class="glyphicon glyphicon-lock"></span><span class="sr-only">unlock</span></button>                        
                        <?php 
                            echo $this->formElementErrors($element);
                            $hidden = (new \Zend\Form\Element\Hidden( 'encrypted.'.$elementName ))->setValue($encrypted);
                            echo $this->formHidden($hidden);
                        ?>
                        </div>
                    </div>    
                <?php endif;?>                    
                </div>

             <?php endforeach; endif; ?>
    </div>
</div><!-- /.tab-content -->
 <div style="margin-top:1em" class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
        <?php
        $csrf = $form->get('csrf');
        echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
        echo $this->formHidden($fieldset->get('id'));
        echo $this->formSubmit($form->get('submit'));?>
    </div>       
</div><!-- / .form-group -->
<?php echo $this->form()->closeTag(); ?>    
</div><!-- /wrapper -->
<?php // the following is only for "edit" action: re-authentication dialog for reading DOB and SSN ?>
<div class="modal" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="modal-auth-title">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 id="modal-auth-title" class="modal-title">Please re-authenticate for access to dob/ssn</h4>
      </div>
      <div class="modal-body">
          <div id="div-auth-error" class="alert alert-warning alert-dismissable hidden">Authentication failed.</div>
          <form autocomplete="off" id="form-login">
              <div class="form-group">
                <label class="sr-only"  for="identity">username or email</label>
                <input name="identity" autocomplete="off" value="" type="text" class="form-control" id="identity" placeholder="email or username">
              </div>
              <div class="form-group">
                <label class="sr-only" for="password">password</label>
                <input name="password" autocomplete="off" value="" type="password" class="form-control" id="password" placeholder="password">
              </div>              
              <?php if ($this->login_csrf): 
                        echo $this->formHidden($this->login_csrf),$this->formElementErrors($this->login_csrf) ;
                    endif;
               ?>
          </form>
      </div>
      <div class="modal-footer" style="text-align: center">
        <button type="button" id="auth-submit" class="btn btn-primary">authenticate</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">cancel</button>        
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
