<?php
use Zend\Form\Element;
/**
 *  module/Admin/view/interpreters-office/admin/people/form.phtml
 *  view script for rendering people create|update form
 */
$this->headTitle($this->title);
$this->headLink()->appendStylesheet($this->basePath('css/jquery-bootstrap-datepicker.css'));
$this->headScript()
        ->appendFile($this->basePath('js/lib/modernizr-custom.js'))
        ->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'));

if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;
$formAction = strstr($this->title, 'add') ? $this->url('interpreters/add')
    : $this->url('interpreters/edit', ['id' => $this->id ]);

$form = $this->form;
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
     'attributes' => ['value' => 'save','class'=>'btn btn-success btn-lg'],
])->setAttribute('method', 'post')
   ->setAttribute('action', $formAction)
   ->setAttribute('class', 'form-horizontal')    ;
?>
<div class="center-block" style="max-width:800px"><!-- wrapper -->
    <h2><?php echo $this->title ?></h2>
    <?php
    $form->prepare();
    $fieldset = $form->get('interpreter');
    echo $this->form()->openTag($form);?>
        
        
        <ul class="nav nav-tabs" role="tablist"><!-- nav tabs -->
            <li role="presentation"><a href="#contact" aria-controls="contact" role="tab" data-toggle="tab">contact &amp; languages</a></li>
            <li role="presentation"><a href="#administrative" aria-controls="administrative" role="tab" data-toggle="tab">administrative</a></li>
        </ul>  <!-- /nav tabs -->
        <div class="tab-content" style="padding-top: 1em">

            <div role="tabpanel" class="tab-pane" id="contact">
                
            <!-- begin "contact" form elements -->
            <?php foreach (['hat','lastname','firstname','middlename','email','officePhone','mobilePhone','active'] as $elementName) :
                        $element = $fieldset->get($elementName);?>
                <div class="form-group">
                    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
                    <div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element) ?>
                    </div>
                </div>
            <?php endforeach;?>
                <div class="form-group">
                  <label class="control-label col-sm-3">languages</label>

            <?php
            /* ----------- languages  ----------- */
            $interpreterLanguages =  $form->getObject()->getInterpreterLanguages(); 
            $fed_certification_options = ['-1' => 'N/A', 1 => 'yes', 0 => 'no', ];
            if (count($interpreterLanguages)):
                $i = 0;
                foreach ($interpreterLanguages as $ilanguage):
                    $columns = $i ? 'col-sm-offset-3 col-sm-4' : 'col-sm-4';
                    $language = $ilanguage->getLanguage();
                    $language_id = $language->getId();
                    $certifiable = $language->isFederallyCertified();
                    //$fed_certification_options['-1'] = $certifiable ? '' : 'N/A';
                    $language_id =  $language->getId();
                    
                ?>
                    <div class="<?php echo $columns?>  interpreter-language language-name" id="language-<?php echo $language_id ?>"><?php 
                        echo $this->escapeHtml($ilanguage->getLanguage());
                        // language and interpreter ids as hidden inputs
                       ?><input type="hidden" name="interpreter[interpreter-languages][<?php echo $i?>][language_id]" value="<?php echo $language_id; ?>">
                    </div>
                  <div class="col-sm-5 form-inline"><?php
                       $element = new Element\Select("interpreter[interpreter-languages][$i][federalCertification]");
                       $selected = $ilanguage->getFederalCertification() === null ? "-1" : (int)$ilanguage->getFederalCertification();
                       $element->setValueOptions($fed_certification_options)
                               ->setValue($selected)
                               ->setAttributes(['class' => 'form-control','id'=>'fed-certification-'.$i]);
                       $disabled = false;
                       if (! $ilanguage->isCertifiable()) {
                           $element->setAttribute("disabled","disabled");
                           $disabled = true;
                       }
                       ?><label for="fed-certification-<?php echo $i?>">fed certified</label><?php
                       echo $this->formSelect($element);                       
                       
                  ?>
                  </div>
                <?php
                    $i++;
                endforeach;
                
            endif; // count(languages)
            ?>
                </div><!-- /languages -->

            <!-- end "contact" form elements -->
            </div><!-- /tab-pane -->
            <div role="tabpanel" class="tab-pane" id="administrative">

                other form elements  here<br>
                <?php $element = $fieldset->get('fingerprintDate');?>
                <div class="form-group">
                    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
                    <div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element) ?></div>
                </div>
            </div><!--  / .tab-pane -->
    
    
        </div><!-- /tab-content -->
        <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <?php
            $csrf = $form->get('csrf');
            echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
            echo $this->formHidden($fieldset->get('id'));
            echo $this->formSubmit($form->get('submit'));?>
        </div>       
    </div><!-- / .form-group -->
  <?php echo $this->form()->closeTag(); ?>  
</div><!-- /wrapper -->


<script type="text/javascript">
    
/** 
 * attach event listeners
 * 
 * @todo live in its own file ?
 * @todo add a button to the select and attach listener to its 'click' event
 * instead of 'change' event on select menu 
 * @todo refactor so this function is not so long and monolithic
 * 
 */

$(function(){
    $('a[href="#contact"]').trigger('click');
    console.log("triggered click on contact tab. see bootstrap doc re how to do it right");
    
    if (! Modernizr.inputtypes.date) {
        $('#fingerprint_date').datepicker();
    }
    
   
    // testing
    // $('#hat').val(3); $('#lastname').val("Doink"); $('#firstname').val("Boink");
    // select.children(':contains("French")').attr({selected:"selected"}).trigger("change");
});
</script>
