<?php
use Zend\Form\Element;
/**
 *  module/Admin/view/interpreters-office/admin/people/form.phtml
 *  view script for rendering people create|update form
 */
$this->headTitle($this->title);
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;
$formAction = strstr($this->title, 'add') ? $this->url('interpreters/add')
    : $this->url('interpreters/edit', ['id' => $this->id ]);

$form = $this->form;
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
     'attributes' => ['value' => 'save','class'=>'btn btn-success btn-lg'],
])->setAttribute('method', 'post')
   ->setAttribute('action', $formAction)
   ->setAttribute('class', 'form-horizontal')    ;
?>
<div class="center-block" style="max-width:800px"><!-- wrapper -->
<h2><?php echo $this->title ?></h2>
<?php

$form->prepare();
$fieldset = $form->get('interpreter');
echo $this->form()->openTag($form);?>
<?php
$hat = $fieldset->get('hat');?>
    <div class="form-group">
        <label class="control-label col-sm-3"><?php echo $hat->getLabel()?></label>
        <div class="col-sm-9"><?php echo $this->formSelect($hat),$this->formElementErrors($hat) ?>            
        </div>
    </div>
<?php
 // text inputs
foreach (['lastname','firstname','middlename','email','officePhone','mobilePhone'] as $elementName) :
    $element = $fieldset->get($elementName);?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>            
    </div>
</div>
<?php
endforeach;
$active = $fieldset->get('active');?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $active->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formCheckbox($active),$this->formElementErrors($active) ?>            
    </div>
 </div>

<div class="form-group">
    <label class="control-label col-sm-3">languages</label>
    <div class="col-sm-9"><?php 
    $languageSelect = $fieldset->get('language-select'); 
    /** @todo figure out where validator should be attached, and how to get error messages */
    echo $this->formSelect($languageSelect),$this->formElementErrors($languageSelect) ?> 
    <input name="interpreter[language-select]" type="hidden" value="-1">           
    </div>
    <!-- wrapper for nested grid // border:1px solid #afd9ee; -->
    <div class="row" style="clear:both">
        <div class="col-sm-3 col-sm-offset-4 languages-header">language</div>
        <div class="col-sm-2 languages-header">fed certification</div>
        <div class="col-sm-3"></div>     
<?php 
    $entity = $form->getObject();
    $interpreterLanguages = $entity->getInterpreterLanguages();
    $fed_certification_options = ['' => 'N/A', 1 => 'yes', 0 => 'no', ];
    
    if (true && count($interpreterLanguages)) :     
        $i = 0;?>            
        <?php
        foreach ($interpreterLanguages as $ilanguage) :
            $language_id = $ilanguage->getLanguage()->getId();
        ?>
        <div class="col-sm-3 col-sm-offset-4 interpreter-language" id="language-<?php echo $language_id?>"><?php 
            echo $this->escapeHtml($ilanguage->getLanguage());
            // language and interpreter ids as hidden inputs
           ?><input type="hidden" name="interpreter[interpreterLanguages][<?php echo $i?>][language]" value="<?php echo $language_id; ?>"><?php 
           ?><input type="hidden" name="interpreter[interpreterLanguages][<?php echo $i?>][interpreter]" value="<?php echo $this->id?>">
        </div>
        <div class="col-sm-2 interpreter-language language-fed-certification"><?php 
           $element = new Element\Select("interpreter[interpreterLanguages][$i][federalCertification]");
           $element->setValueOptions($fed_certification_options)->setValue($ilanguage->getFederalCertification())->setAttribute('class', 'form-control');
           echo $this->formSelect($element);
        ?></div>
        <div class="col-sm-3 interpreter-language">
            <button title="remove from this interpreter's working languages" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-remove"></span><span class="sr-only">remove</span></button></div>
        <?php  
        $i++; 
        endforeach;
    endif;
?>              
   </div><!-- /grid wrapper -->   

</div>

<?php 
if (false):
$i = 0;

foreach ($interpreterLanguagesFieldset as $thing) : // fieldset
    echo '<div class="interpreter-language">';
//printf ( "class of language is %s; class of interpreter is %s<br>", get_class($thing->get('language')), get_class($thing->get('interpreter')));
    echo $this->formHidden($thing->get('language')); echo $this->escapeHtml('<-- shit');
    ////echo $this->formHidden($thing->get('interpreter'));
    //name="interpreter[interpreterLanguages][0][language]
    ?><input type="hidden" name="interpreter[interpreterLanguages][<?php echo ++$i?>][interpreter]" value="<?php echo $this->id?>">
    <?php echo $this->formSelect($thing->get('federalCertification'));
echo "</div>";
endforeach;

endif; ?><!--pre><?php //print_r(get_class_methods($interpreterLanguagesFieldset)); ?></pre> -->

<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
    <?php
    $csrf = $form->get('csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    echo $this->formHidden($fieldset->get('id'));
    echo $this->formSubmit($form->get('submit'));?></div>
</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
<script type="text/javascript">
    
/** dynamically add a language. @todo live in its own file ? */
// no point in typing this more than once
var languageElementName = "interpreter[interpreterLanguages][]";
$(function(){
    var select = $('#language-select');    
    select.on("change",function(){
        console.log("change event on select element");
        
    });
    
    
    /*
    if (false) {
    // when form is (re)loaded, create list from hidden select element
    $('#interpreterLanguages option:selected').each(function(){ 
			var option = $(this);
			createLanguageItem(option).appendTo(list);
			option.removeAttr('selected');
    });
    // when language select menu item is chosen, add it to the list
    select.on("change",function(){
        if (! select.val()) {
            return;
        }
        var option = select.children(':selected');
        var language = option.text();
        if (list.children(':contains("'+language+'")').length) {
            return;
        }
        createLanguageItem(option).appendTo(list);
        select.val('');
    });   
    }
    */

    //  testing
    $('#hat').val(3);
    $('#lastname').val("Doink");
    $('#firstname').val("Boink");
    // select.children(':contains("French")').attr({selected:"selected"}).trigger("change");
});
/**
 * helper function to create li element
 * not currently in use!
 * @param option jQuery with one <option> element
 * @returns jQuery with one <li> element
 */
createLanguageItem = function(option)
{
    var li = $('<li>').addClass('list-group-item');
    var input = $('<input>').attr({
            type: "hidden",
            name: languageElementName,
            value: option.attr('value')
        });
    return li.text(option.text()).append(input);
};
</script>