<?php
/** module/Admin/views/interpreters-office/admin/interpreters/index.phtml
 *  viewscript for main interpreter-administration page
 */
$this->headScript()->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.css'));
$form = $this->form;
// set some defaults for the search form
foreach (['language_id','active','security_clearance_expiration'] as $e) :
    if (isset($this->params[$e])) { $form->get($e)->setValue($this->params[$e]); }
endforeach;
if ($this->interpreter): 
    $form->get('name')->setValue("{$interpreter->getLastname()}, {$interpreter->getFirstName()}");
else:
    $form->get('name')->setValue(key_exists('name',$this->params)? $this->params['name']:'');
endif;

$this->headTitle($this->title);
?>
<h2><?php echo $this->navigation('default')->breadcrumbs() ?></h2>
<?php
$messenger = $this->flashMessenger()->setAutoEscape(false);
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',]);
endif;
?>
<div class="panel panel-default">
  <div class="panel-body">
    <form>
    <div class="form-group form-inline panel-body">
    <div id="form-errors" class="alert alert-warning hidden"></div>
    Find interpreters of
        <label for="language" class="sr-only">language</label> <?php echo $this->formElement($form->get('language_id'))?>
        who are <label for="active" class="sr-only">status</label>
        <?php echo $this->formSelect($form->get('active'))?>
        with security clearance <label for="security_clearance_expiration" class="sr-only">security clearance</label>
         <?php echo $this->formSelect($form->get('security_clearance_expiration'))?><!--
    --><a id="btn-search-language" href="<?php echo $this->url('interpreters') ?>" class="btn btn-success"><span class="glyphicon glyphicon-search"></span> search</a> 
    </div>
    <div class="form-group form-inline">or whose name is <?php echo $this->formElement($form->get('name'))?><a href="<?php echo $this->url('interpreters')?>" id="btn-search-name" class="btn btn-success"><span class="glyphicon glyphicon-search"></span> search</a></div> 
    </form>
  </div>
</div>

<br>
<?php 
if ($this->interpreter) :
    
    echo "<p>yes we have an interpreter. to do: create a view partial and render</p>";

endif;
if ($this->results): 
    echo $this->paginationControl($this->results, null, 'partials/pagination_head'); 
?>

<table class="table table-hover table-bordered" style="max-width:700px">
    <tbody>
        <?php
        foreach ($this->results as $row) : /** note to self: use array hydration? */
            $interpreter = $row[0];  ?>
        <tr><td><?php echo $this->escapeHtml(sprintf('%s, %s',$interpreter->getLastname(),$interpreter->getFirstname())) ?></td><td></td></tr>
<?php  endforeach;  ?>
    </tbody>
</table>
<p>TO DO: action menu thingy for each table row, e.g: edit, view, cron, email</p>
<?php echo $this->paginationControl(
    $this->results,
    'sliding',
    'partials/pagination_control',
     ['route'=>$this->routeName,'params'=>$this->params]     
);?>
<?php 
    else : 
        if ($this->isQuery and !$this->interpreter) :
?><p>No matching records found.</p><?php 
    endif; 
endif; ?>
<a href="<?php echo $this->url('interpreters/add') ?>" role="button" title="add a new interpreter" id="btn-add-interpreter" class="btn btn-info">
<span aria-hidden="true" class="icon glyphicon glyphicon-plus"></span> new interpreter
</a>
<script type="text/javascript">
$(function(){
    var languageSelect = $('#language_id'); 
    var languageButton = $('#btn-search-language');
    languageButton.on("click",function(event){
        event.preventDefault();
        var language_id = languageSelect.val() || "0";  
        var url = languageButton.attr('href');
        url += '/language/' + language_id;        
        url += '/active/'+$('#active').val();                
        var security = $('#security_clearance_expiration').val();
        url += '/security/'+security;
        document.location = url;
    });
    var nameElement = $('#name');
    nameElement.autocomplete({
        source : window.basePath+'/admin/interpreters',
        minLength : 2,
        select : function( event, ui ) {            
           nameElement.data({ interpreterName : ui.item.label, interpreterId: ui.item.id });
           //console.log("select. shit is real");
        }
    });
    
    $('#btn-search-name').on("click",function(event){
        event.preventDefault();       
        var name = nameElement.val().trim();
        if (! name) {
            return;
        }
        
        var url = window.basePath + "/admin/interpreters";
        var selected = nameElement.data();
        // if we have an interpreter id, use it in the url
        if (name === selected.interpreterName) {
            url  += "/" + selected.interpreterId;
        } else {            
            //'route' => '/name/:lastname[/:firstname]',
            var pos = name.lastIndexOf(',');
            if (-1 === pos) {
                url += "/name/"+name.trim();
            } else {                
                 var lastname = encodeURIComponent(name.substring(0,pos).trim());
                 var firstname = encodeURIComponent(name.substr(pos+1).trim());
                 url += "/name/"+ lastname + "/" + firstname;
            }
        }
        document.location = url;
    });
});

</script>