<?php
/** module/Admin/views/interpreters-office/admin/interpreters/index.phtml
 *  viewscript for main interpreter-administration page
 */
$this->headScript()
        ->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'))
        ->appendFile($this->basePath('js/interpreters-index.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.css'));
$form = $this->form;
// set some defaults for the search form
foreach (['language_id','active','security_clearance_expiration'] as $e) :
    $element = $form->get($e);
    if (isset($this->params[$e])) {
        $element->setValue($this->params[$e]);
    }
    $element->setAttribute('class', 'form-control mx-2');
endforeach;
$name_element = $form->get('name');
if ($this->interpreter) :
    $name_element->setValue("{$interpreter->getLastname()}, {$interpreter->getFirstName()}");
else :
    $name_element->setValue(key_exists('name', $this->params) ? $this->params['name'] : '');
endif;
$name_element->setAttribute('class', 'form-control mx-2');
$this->headTitle($this->title);
?>
<h2 class="text-center"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
<?php
$messenger = $this->flashMessenger()->setAutoEscape(false);
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',]);
endif;
?>
<div class="card shadow-sm">
  <div class="card-body pb-1 pl-5">
    <form>
    <div class="form-group form-inline">
        <div id="form-errors" class="alert alert-warning hidden" style="display:none"></div>
        Find <label for="language" class="sr-only">language</label> <?php echo $this->formElement($form->get('language_id'))?>
        interpreters who are <label for="active" class="sr-only">status</label>
        <?php echo $this->formSelect($form->get('active'))?>
        with security clearance <label for="security_clearance_expiration" class="sr-only">security clearance</label>
            <?php echo $this->formSelect($form->get('security_clearance_expiration')) ?><!--
            --><a id="btn-search-language" href="<?php echo $this->url('interpreters') ?>" class="btn btn-primary"><span class="fa fa-search"></span> search</a>
    </div>
    <div class="form-group form-inline"><label class="pr-1" for="name">Or whose name is</label><?php echo $this->formElement($form->get('name'))?><a href="<?php echo $this->url('interpreters')?>" id="btn-search-name" class="btn btn-primary"><span class="fa fa-search"></span> search</a></div>
    </form>
  </div>
</div>
<br>
<?php
if ($this->interpreter) :
    echo $this->render('view');
endif;
?>
<div class="mx-auto" style="max-width:600px">
<?php
if ($this->results) : ?>
<table class="table table-hover table-bordered table-sm mx-auto">
    <thead>
        <tr><th colspan="3" class="font-weight-normal pl-3">
            <?php echo $this->paginationControl($this->results, null, 'partials/pagination_head');?> interpreters found</th></tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->results as $row) : /** note to self: use array hydration? */
            $interpreter = $row[0];
            $id = $interpreter->getId();
            $status = $interpreter->isActive() ? 'active' : 'inactive';
            $view_url = $this->url('interpreters/find_by_id', ['id' => $id])?>
        <tr>
            <td class="pl-2 align-middle border-left-0 border-right-0 col-9">
                <a   data-toggle="tooltip" title="view interpreter details" href="<?php echo $view_url?>">
                <?php echo $this->escapeHtml(sprintf('%s, %s', $interpreter->getLastname(), $interpreter->getFirstname())) ?></a>
                <?php if ($row['hat'] == 'staff court interpreter') :
?> <span class="text-muted">staff interpreter</span><?php
endif; ?>
            </td>
            <td class="align-middle text-center border-left-0 border-right-0 col-2 text-md-right">
                <span style="opacity:.7" data-toggle="tooltip" title="this interpreter is currently flagged as <?php
                    echo $status ?>" class="pr-2 fas fa-<?php echo $status == 'active' ? "check text-success" : "times text-danger"?>"></span>
            </td><td class="border-left-0 text-md-left">
                <a data-toggle="tooltip" title="edit interpreter details" href="<?php echo $this->url('interpreters/edit', ['id' => $interpreter->getId()])?>"><span class="fas fa-edit"></span><span class="sr-only">edit details</span></a>
            </td>
        </tr>
        <?php  endforeach;  ?>
    </tbody>
</table>

<?php echo $this->paginationControl(
    $this->results,
    'sliding',
    'partials/pagination_control',
    ['route' => $this->routeName,'params' => $this->params]
);?>
<?php
else :
    if ($this->isQuery and ! $this->interpreter) :
    ?><p>No matching records found.</p><br>
<?php
    endif;
endif;
// make them work for it
if ($this->isQuery):
?>
<br>
<a href="<?php echo $this->url('interpreters/add') ?>" role="button" title="add a new interpreter" id="btn-add-interpreter" class="btn btn-primary">
<span aria-hidden="true" class="icon fa fa-plus"></span> new interpreter
</a>
<?php endif; ?>
</div>
