<?php // the following is only for "edit" action: re-authentication dialog for reading DOB and SSN ?>
<div class="modal" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="modal-auth-title">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h4 id="modal-auth-title" class="modal-title ml-2">Please re-authenticate for access to dob/ssn</h4>
      <div class="float-right">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
        
      </div>
      <div class="modal-body">
          <div id="div-auth-error" class="alert alert-warning alert-dismissable" style="display:none">Authentication failed.</div>
          <form autocomplete="off" id="form-login">
                <?php  $fake_identity = bin2hex(openssl_random_pseudo_bytes(8));
                     $fake_password = bin2hex(openssl_random_pseudo_bytes(8));
                ?>
              <div class="form-group">
                <label class="sr-only"  for="<?php echo $fake_identity ?>">username or email</label>
                <input name="<?php echo $fake_identity ?>" autocomplete="off" value="" type="text" class="form-control thing1" id="<?php echo $fake_identity ?>" placeholder="email or username">
              </div>
              <div class="form-group">
                <label class="sr-only" for="<?php echo $fake_password ?>">password</label>
                <input name="<?php echo $fake_password ?>" autocomplete="off" value="" type="password" class="form-control thing2" id="<?php echo $fake_password ?>" placeholder="password">
              </div>              
                <?php if (! $this->login_csrf) :
                        $this->login_csrf = (new \Zend\Form\Element\Csrf('login_csrf'))
                        ->setAttribute('id', 'login_csrf');
                endif;
                     echo $this->formHidden($this->login_csrf),$this->formElementErrors($this->login_csrf) ;
                ?>
          </form>
      </div>
      <div class="modal-footer" style="text-align: center">
        <button type="button" id="auth-submit" class="btn btn-primary">authenticate</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">cancel</button>        
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
