<div style="max-width:700px" class="mx-auto">
    <h2 class="text-center"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
    <p class="mt-4">
        Documentation is still incomplete, but whatever is available can be found at the InterpretersOffice project website: 
        <a href="https://interpretersoffice.org/documentation">https://interpretersoffice.org/documentation</a>         
    </p>
    <p>
        You are also welcome to contact the application developer with any questions: david@davidmintz.org
    </p>
</div>