<?php 
/**
 * module/InterpretersOffice/view/partials/interpreters/language.phtml
 * 
 * this is intended to keep the HTML in one place and the Javascript simple
 * for rendering/dynamically adding languages to the Interpreter form
 * 
 * expected variables are either:
 *  
 *  (1) $this->count and $this->collection
 *     or
 *  (2) a $this->language entity and an index number $this->index
 */

if ($this->language) : 
    $this->count = 1;   
endif;

for ($i = 0; $i < $this->count; $i++) :
    
    if ($this->collection) { // rendering existing languages
        
        $fs = $this->collection->get($i);        
        $language_element = $fs->get('language');
        $obj = $language_element->getValue();
        $certifiable = $obj->isFederallyCertified();
        $language_id = $obj->getId();
        $language_element->setValue($language_id);
        $certification_element = $fs->get('federalCertification');
        $certification_element->setAttribute('id',"fed-certification-{$i}");  
        // finally..
        $this->language = $obj;
        
    } else { // XHR request for some markup
        
        $i = $this->index;
        $certifiable = $this->language->isFederallyCertified();
        $language_id = $this->language->getId();
        $language_element = new \Zend\Form\Element\Hidden(
                 "interpreter[interpreterLanguages][$i][language]",
                [                        
                    //'name' => "interpreter[interpreterLanguages][$i][language]",
                    'value' => $language_id,
                ]
        );           
        $certification_element = new \Zend\Form\Element\Select(
                "interpreter[interpreterLanguages][$i][federalCertification]",
                [
                'options' => [
                    'value_options' => ['-1' => 'N/A', 1 => 'yes', 0 => 'no', ],
                    'attributes' => ['class' => 'form-control','id'=>"fed-certification-{$i}"],
                    'value' => '-1',
                ]
            ]
         );
    }        
    if (! $certifiable) :
        // federal certification is not applicable
        $certification_element
            ->setValue(-1)
            ->setAttribute('disabled','disabled');
    else :
        // "N/A" is not an option, so change empty option label
        $certification_element->setValueOptions(['-1' => '', 1 => 'yes', 0 => 'no', ]);
    endif; // now, the markup
    
    ?><div class="col-sm-offset-1 col-sm-3  interpreter-language language-name" id="language-<?php echo $language_id ?>">
        <?php 
        echo $this->formElement($language_element),  $this->escapeHtml($this->language->getName());
        ?>
    </div>
    <div class="col-sm-5 form-inline interpreter-language language-certification">
        <label for="fed-certification-<?php echo $i ?>">fed certification:</label>
    <?php echo $this->formElement($certification_element); 
       ?><button class="btn btn-warning btn-xs btn-remove-language" title="remove this language"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            <span class="sr-only">remove language</span></button>
        <?php if ($certification_element->getAttribute('disabled')) : // supply a value, to avoid undefined index error  ?>
            <input type="hidden" name="interpreter[interpreterLanguages][<?php echo $i ?>][federalCertification]" value="-1">
    <?php endif; ?>
        <div class="alert alert-warning validation-error" style="display:none"></div>                
    </div>
<?php endfor;?>

