<?php $this->headTitle('requests | configuration');
$this->headScript()->appendFile($this->basePath('js/requests/admin/config.js'));
?>
<pre>
<?php
foreach ($this->form as $e) {
    //echo $e->getName(),"\n";
}
var_dump($form->has('cancel[in-court][spanish][delete-scheduled-event]'));
?>
</pre>
<main style="max-width:900px"  class="mx-auto">
    <h3>
        <?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs();?>
    </h3>
    <p class="pr-3 my-3">The Requests module does not allow users who submit requests
        to change the Interpreters' schedule themselves.
        When users modify their requests, however, the Interpreters' schedule virtually
        always has to be updated accordingly. To avoid having to do these repetitive tasks
        manually, you can use this page to see and configure how user events are handled automatically.
        For further explanation please <a href="#user-guide-requests-config">see below</a>.
    </p>
<form action="<?php echo $this->url('admin-requests/config') ?>" method="post">
    <table class="table mb-3 table-bordered">
        <thead>
            <tr>
                <th>user event<!--<br><span class="text-muted font-weight-light">(what the user did with the request)</span>--></th>
                <th>language
                    <!-- <br><span class="text-muted font-weight-light">(language for which interpreter was requested)</span> -->
                </th>
                <th>type of event</th>
                <th>actions<!-- <br><span class="text-muted font-weight-light">(what to do automatically)</span> --></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-monospace" rowspan="3">cancel</td>
                <td rowspan="2">Spanish</td>
                <td>in-court</td>
                <td><?php
                $base = 'cancel[in-court][spanish]';
                $element = $this->form->get($base.'[delete-scheduled-event]');
                echo $this->configCheckbox($element);
                $element = $this->form->get($base.'[notify-assigned-interpreters]');
                echo $this->configCheckbox($element);
                ?>
                </td>
            </tr>
            <tr>
                <td>out-of-court</td>
                <td><?php
                $base = 'cancel[out-of-court][spanish]';
                $element = $this->form->get($base.'[delete-scheduled-event]');
                echo $this->configCheckbox($element);
                $element = $this->form->get($base.'[notify-assigned-interpreters]');
                echo $this->configCheckbox($element);
                ?>
                </td>
            </tr>
            <tr>
                <td>non-Spanish</td>
                <td>any</td>
                <td><?php
                $base = 'cancel[out-of-court][non-spanish]';
                $element = $this->form->get($base.'[delete-scheduled-event]');
                echo $this->configCheckbox($element);
                $element = $this->form->get($base.'[notify-assigned-interpreters]');
                echo $this->configCheckbox($element);
                ?></td>
            </tr>
            <tr>
                <td class="text-monospace">change date</td>
                <td>any</td>
                <td>any</td>
                <td><?php
                $base = 'change-date[all-events][all-languages]';
                $element = $element = $this->form->get($base.'[update-scheduled-event]');
                echo $this->configCheckbox($element);
                $element = $element = $this->form->get($base.'[notify-assigned-interpreters]');
                echo $this->configCheckbox($element);
                 ?></td>
            </tr>
            <tr>
                <td class="text-monospace">change time across am/pm</td>
                <td>any</td>
                <td>any</td>
                <td><?php
                // echo // $this->configCheckbox('change-x-am-pm','all-languages','all-events','update-scheduled-event'),
                // $this->configCheckbox('change-x-am-pm','all-languages','all-events','notify-assigned-interpreters'),
                 // $this->configCheckbox('change-x-am-pm','all-languages','all-events','remove-interpreters')
                 ?></td>
            </tr>
            <tr>
                <td rowspan="4" class="text-monospace">change time within am/pm</td>
                <td rowspan="2">Spanish</td>
                <td>in-court</td>
                <td><?php
                // echo // $this->configCheckbox('change-within-am-pm','spanish','in-court','update-scheduled-event'),
                // $this->configCheckbox('change-within-am-pm','spanish','in-court','notify-assigned-interpreters'),
                 // $this->configCheckbox('change-within-am-pm','spanish','in-court','remove-interpreters',null,false)
                 ?></td>
            </tr>
            <tr>
                <td>out-of-court</td>
                <td><?php
                // echo // $this->configCheckbox('change-within-am-pm','spanish','out-of-court','update-scheduled-event'),
                // $this->configCheckbox('change-within-am-pm','spanish','out-of-court','notify-assigned-interpreters'),
                 // $this->configCheckbox('change-within-am-pm','spanish','out-of-court','remove-interpreters',null,false)
                 ?></td>
            </tr>
            <tr>
                <td rowspan="2">non-Spanish</td>
                <td>in-court</td>
                <td><?php
                // echo // $this->configCheckbox('change-within-am-pm','non-spanish','in-court','update-scheduled-event'),
                // $this->configCheckbox('change-within-am-pm','non-spanish','in-court','notify-assigned-interpreters'),
                 // $this->configCheckbox('change-within-am-pm','non-spanish','in-court','remove-interpreters',null,false)
                 ?></td>
            </tr>
            <tr>
                <td>out-of-court</td>
                <td><?php
                // echo // $this->configCheckbox('change-within-am-pm','non-spanish','out-of-court','update-scheduled-event'),
                // $this->configCheckbox('change-within-am-pm','non-spanish','out-of-court','notify-assigned-interpreters'),
                 // $this->configCheckbox('change-within-am-pm','non-spanish','out-of-court','remove-interpreters',null,false)
                 ?></td>
            </tr>
            <tr>
                <td class="text-monospace">change language</td>
                <td>any</td>
                <td>any</td>
                <td><?php
                // echo // $this->configCheckbox('change-language','all-languages','all-events','update-scheduled-event'),
                // $this->configCheckbox('change-language','all-languages','all-events','notify-assigned-interpreters'),
                 // $this->configCheckbox('change-language','all-languages','all-events','remove-interpreters')
                 ?></td>
            </tr>
        </tbody>
    </table>
    <div class="text-center">
        <button type="button" name="button" class="btn btn-success btn-lg border">save configuration</button>
    </div>
    </form>
    <hr class="my-4">
    <h3 id="user-guide-requests-config" class="text-primary">A guide to the Requests module's configuration</h3>
    <h4 class="my-4 p-2 border text-center">actions</h4>
    <dl class="row">
        <dt class="col-sm-4 text-monospace">delete scheduled event</dt>
        <dd class="col-sm-8">If the request has been added to the schedule,
            remove the corresponding event from the schedule. This implies the <code>remove interpreter</code> action.</dd>
        <dt class="col-sm-4 text-monospace">update scheduled event</dt>
        <dd class="col-sm-8">If the request has been added to the schedule,
            update the corresponding scheduled event to match the changes the user just made to the request.</dd>
        <dt class="col-sm-4 text-monospace">remove interpreter</dt>
        <dd class="col-sm-8">Remove the interpreter from the corresponding scheduled event.</dd>
        <dt class="col-sm-4 text-monospace">notify assigned interpreter(s)</dt>
        <dd class="col-sm-8">Send a template-based email to the interpreter informing her or him of the actions taken.
            If you enable automatic removal of the interpreter, enabling notification in most cases is <em>strongly</em> encouraged.
            <em>All such emails are copied to the Interpreters Office.</em>
        </dd>
    </dl>

    <h4 class="my-4 p-2 border text-center">user events</h4>
    <dl class="row">
        <dt class="col-sm-4 text-monospace">cancel</dt>
        <dd class="col-sm-8">The user has withdrawn the request.</dd>
        <dt class="col-sm-4 text-monospace">change date</dt>
        <dd class="col-sm-8">The user changed the date. This implies but does not trigger a <code>change time</code> in addition.</dd>
        <dt class="col-sm-4 text-monospace">change time within/across am-pm</dt>
        <dd class="col-sm-8">The user left the date intact, but changed the time. Since contract court interpreters are frequently hired for
            half-day periods, you may wish to differentiate the handling of the two scenarios: a change of date from morning to afternoon
            (or vice-versa), as opposed to a change of time <em>within</em> the same morning or afternoon. Any time
            before 1:00 pm is considered morning; 1:00 pm or later is considered afternoon.
        </dd>
    </dl>
    <h4 class="my-4 p-2 border text-center">language</h4>
    <p>In practice, Spanish is much more frequently used than any other language, and Spanish interpreters are generally busier.
        Therefore, for some events you may wish to differentiate between Spanish-language events and everything else.</p>
    <h4 class="my-4 p-2 border text-center">type of event</h4>
    <p>In some cases the Requests module's event handlers distinguish between events that take place in-court and those
        that take place elsewhere, typically in an off-site location such as a jail. This feature allows you to avoid sending
        needless emails to interpreters in regard to updates that are not remarkable.</p>
    <h4 class="my-4 p-2 border text-center">general considerations</h4>

    <p>The design goals of the Requests module are to alleviate the burden of repetitive and error-prone tasks and to ensure
        that people receive timely notification of events they need to know about. On the other hand, overuse of email
        notification creates its own problems. By configuring these behaviors yourself, you can experiment and try to strike
        the best balance for your situation.
    </p>
</main>
