<?php $this->headTitle('requests | configuration');
$this->headScript()->appendFile($this->basePath('js/requests/admin/config.js'));
?>
<!-- <pre></pre> -->
<?php    echo $this->errorMessage($this->errorMessage);  ?><?php
    if ($this->errorMessage) :   return;  endif;
?>
<main style="max-width:900px"  class="mx-auto">
    <h3 id="top"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs();?></h3>
    <p class="pr-3 my-3">The InterpretersOffice Requests module does not allow users who submit requests
        to change the Interpreters' schedule directly. But when users modify their requests,
        you frequently do have to take action, e.g., update the schedule, contact interpreters.
        To alleviate this burden and to ensure that necessary action is taken
        promptly, the Requests module can handle these tasks for you automatically.
        This form allows an administrator to configure these behaviors. For further
        explanation please <a href="#user-guide-requests-config">see below</a>.
    </p>

<?php $this->form->prepare()?>
<form action="<?php echo $this->url('admin-requests/update-config') ?>" method="post" id="config-form">
    <table class="table mb-3 table-bordered">
        <thead>
            <tr>
                <th>user event</th>
                <th>language</th>
                <th>type of event</th>
                <th>action</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-monospace" rowspan="3">cancel</td>
                <td rowspan="2">Spanish</td>
                <td>in-court</td>
                <td><?php $fs = $this->form->get('cancel');
                $base = 'in-court.spanish.';
                $element = $fs->get($base.'delete-scheduled-event');
                echo $this->configCheckbox($element);
                $element = $fs->get($base.'notify-assigned-interpreters');
                echo $this->configCheckbox($element);
                ?>
                </td>
            </tr>
            <tr>
                <td>out-of-court</td>
                <td><?php
                $base = 'out-of-court.spanish.';
                $element = $fs->get($base.'delete-scheduled-event');
                echo $this->configCheckbox($element);
                $element = $fs->get($base.'notify-assigned-interpreters');
                echo $this->configCheckbox($element);
                ?>
                </td>
            </tr>
            <tr>
                <td>non-Spanish</td>
                <td>any</td>
                <td><?php
                $base = 'all-events.non-spanish.';
                $element = $fs->get($base.'delete-scheduled-event');
                echo $this->configCheckbox($element);
                $element = $fs->get($base.'notify-assigned-interpreters');
                echo $this->configCheckbox($element);
                ?></td>
            </tr>
            <!--   ==========================================  -->
            <tr>
                <td class="text-monospace">change date</td>
                <td>any</td>
                <td>any</td>
                <td><?php
                $fs = $this->form->get('change-date');
                $base = 'all-events.all-languages.';
                $element = $fs->get($base.'update-scheduled-event');
                echo $this->configCheckbox($element);
                $element = $element = $fs->get($base.'notify-assigned-interpreters');
                echo $this->configCheckbox($element);
                $element = $fs->get($base.'remove-interpreters');
                echo $this->configCheckbox($element);
                 ?></td>
            </tr>
            <tr>
                <td class="text-monospace">change time across am/pm</td>
                <td>any</td>
                <td>any</td>
                <td><?php
                $fs = $this->form->get('change-x-am-pm');
                $base = 'all-events.all-languages.';
                $element = $fs->get($base.'update-scheduled-event');
                echo $this->configCheckbox($element);
                $element = $element = $fs->get($base.'notify-assigned-interpreters');
                echo $this->configCheckbox($element);
                $element = $fs->get($base.'remove-interpreters');
                echo $this->configCheckbox($element);
                 ?></td>
            </tr>
            <tr>
                <td rowspan="4" class="text-monospace">change time within am/pm</td>
                <td rowspan="2">Spanish</td>
                <td>in-court</td>
                <td><?php
                $fs = $this->form->get('change-within-am-pm');
                $base = 'in-court.spanish.';
                $element = $fs->get($base.'update-scheduled-event');
                echo $this->configCheckbox($element);
                $element = $element = $fs->get($base.'notify-assigned-interpreters');
                echo $this->configCheckbox($element);
                $element = $fs->get($base.'remove-interpreters');
                echo $this->configCheckbox($element);
                 ?></td>
            </tr>
            <tr>
                <td>out-of-court</td>
                <td><?php
                $base = 'out-of-court.spanish.';
                $element = $fs->get($base.'update-scheduled-event');
                echo $this->configCheckbox($element);
                $element = $element = $fs->get($base.'notify-assigned-interpreters');
                echo $this->configCheckbox($element);
                $element = $fs->get($base.'remove-interpreters');
                echo $this->configCheckbox($element);
                 ?></td>
            </tr>
            <tr>
                <td rowspan="2">non-Spanish</td>
                <td>in-court</td>
                <td><?php
                $base = 'in-court.non-spanish.';
                $element = $fs->get($base.'update-scheduled-event');
                echo $this->configCheckbox($element);
                $element = $element = $fs->get($base.'notify-assigned-interpreters');
                echo $this->configCheckbox($element);
                $element = $fs->get($base.'remove-interpreters');
                echo $this->configCheckbox($element);
                 ?></td>
            </tr>
            <tr>
                <td>out-of-court</td>
                <td><?php
                $base = 'out-of-court.non-spanish.';
                $element = $fs->get($base.'update-scheduled-event');
                echo $this->configCheckbox($element);
                $element = $element = $fs->get($base.'notify-assigned-interpreters');
                echo $this->configCheckbox($element);
                $element = $fs->get($base.'remove-interpreters');
                echo $this->configCheckbox($element);
                 ?></td>
            </tr>
            <tr>
                <td class="text-monospace">change language</td>
                <td>any</td>
                <td>any</td>
                <td><?php
                $fs = $this->form->get('change-language');
                $base = 'all-events.all-languages.';
                $element = $fs->get($base.'update-scheduled-event');
                echo $this->configCheckbox($element);
                $element = $element = $fs->get($base.'notify-assigned-interpreters');
                echo $this->configCheckbox($element);
                $element = $fs->get($base.'remove-interpreters');
                echo $this->configCheckbox($element);
                 ?></td>
            </tr>
            <tr>
                <td class="text-monospace">change other attributes</td>
                <td>any</td>
                <td>any</td>
                <td><?php $fs = $this->form->get('update-other-attributes');
                $base = 'all-events.all-languages.';
                $element = $fs->get($base.'update-scheduled-event');
                echo $this->configCheckbox($element);
                ?></td>
            </tr>
        </tbody>
    </table>
    <div class="text-center">
        <div class="alert alert-success alert-dismissible fade show" role="alert" style="display:none">
          <p id="status"></p>
          <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <?php if ($this->update_allowed): ?><p class="alert alert-warning border border-danger text-danger">
          You should not change the default settings unless you're sure you know what you're doing.
      </p><?php endif ?>
        <button <?php if (! $this->update_allowed): ?> disabled title="current user is not authorized to modify these settings" style="cursor:not-allowed"<?php endif ?> type="button" id="save" name="button" class="btn btn-success btn-lg border">save configuration</button>
        <?php $display = $this->customized_settings && $this->update_allowed ? 'inline':'none' ?>
        <button type="button" id="restore-defaults" class="btn btn-success btn-lg border" style="display:<?php echo $display?>;">restore defaults</button>
    </div>
    </form>
    <hr class="my-4">
    <h3 id="user-guide-requests-config" class="text-primary">A guide to the Requests module's configuration</h3>
    <h4 class="my-4 p-2 border text-center">user events</h4>
    <p>This describes some things that users who submit requests will sometimes do with their requests for interpreting services.</p>
    <dl class="row">
        <dt class="col-sm-4 text-monospace">cancel</dt>
        <dd class="col-sm-8">The user has withdrawn the request.</dd>
        <dt class="col-sm-4 text-monospace">change date</dt>
        <dd class="col-sm-8">The user changed the date. This implies a <code>change time</code> event but does not trigger any additional actions.</dd>
        <dt class="col-sm-4 text-monospace">
            change time within am-pm<br>
            change time across am-pm<br>
        </dt>
        <dd class="col-sm-8">The user left the date intact, but changed the time. Since contract court interpreters are frequently hired for
            half-day periods, you may wish to differentiate the handling of the two scenarios: a change of date from morning to afternoon
            (or vice-versa), as opposed to a change of time <em>within</em> the same morning or afternoon. Any time
            before 1:00 pm is considered morning; 1:00 pm or later is considered afternoon.
        </dd>
        <dt class="col-sm-4 text-monospace">change language</dt>
        <dd class="col-sm-8">The user changed the language requested. This is unusual, but when it happens to a scheduled event to which
        interpreters have been assigned, action on your part will likely be required.
        </dd>
        <dt class="col-sm-4 text-monospace">change other attributes</dt>
        <dd class="col-sm-8">The user updated other attributes such as the event type, docket number, names and/or
            numbers of defendants.</dd>
    </dl>

    <h4 class="my-4 p-2 border text-center">actions</h4>
    <p>These are the actions which, if enabled, the Requests module will execute automatically in response to
    certain <em>user events</em>, i.e, things that submitters of requests can do with their requests.</p>
    <dl class="row">
        <dt class="col-sm-4 text-monospace">delete scheduled event</dt>
        <dd class="col-sm-8">If the request has been added to the schedule,
            remove the corresponding event from the schedule. This implies the <code>remove interpreter</code> action.</dd>
        <dt class="col-sm-4 text-monospace">update scheduled event</dt>
        <dd class="col-sm-8">If the request has been added to the schedule,
            update the corresponding scheduled event to match the changes the user just made to the request.</dd>
        <dt class="col-sm-4 text-monospace">remove interpreter</dt>
        <dd class="col-sm-8">Remove the interpreter from the corresponding scheduled event.</dd>
        <dt class="col-sm-4 text-monospace">notify assigned interpreter(s)</dt>
        <dd class="col-sm-8">Send a template-based email to the interpreter informing her or him of the actions taken.
            If you enable automatic removal of the interpreter, enabling notification in most cases is <em>strongly</em>
            encouraged.
            <em>All such emails are copied to the Interpreters Office.</em>
        </dd>
    </dl>
    <h4 class="my-4 p-2 border text-center">language</h4>
    <p>In practice, Spanish is much more frequently used than other languages, and Spanish interpreters are generally busier.
        The Requests module classifies the requested language as either Spanish or not-Spanish, so that you have the ability to handle
        the two cases differently.
    </p>
    <h4 class="my-4 p-2 border text-center">type of event</h4>
    <p>In some cases the Requests module allows you to distinguish between interpreter-events that take place in-court and those
        that take place elsewhere, typically in an off-site location such as a jail. This feature allows you to avoid sending
        needless emails to interpreters in regard to updates that are not remarkable. For example, if a Spanish interpreter is assigned to an in-court proceeding whose time
        is changed from 10:00 a.m to 10:30 a.m., you may see no need to fire off an email. But if an interpreter is scheduled
        to show up to a remote location such as a jail, and the time is changed, you will probably want the interpreter to be notified
        immediately via email.</p>
    <h4 class="my-4 p-2 border text-center">general considerations</h4>

    <p>Requests module is designed to:</p>
    <ul>
        <li>alleviate the burden of error-prone, repetitive tasks for staff interpreters;</li>
        <li>provide a convenient interface for users to submit and modify their requests;</li>
        <li>encourage users to submit and cancel their requests in timely fashion; and</li>
        <li>ensure that people receive timely email notification of events they need to know about.</li>
    </ul>
    <p>
        The overuse of email notification, however, creates its own problems. You have the option of adjusting these settings,
        if you wish, to find the best balance for your situation. But we strongly recommend you run with the
        defaults for some time before tweaking.
    </p>

    <p>We also provide this interface to your configuration so you can <em>see</em> and understand how the system works; you may never
    need to <em>change</em> it.</p>
    <p>Enabling automatic updating of scheduled events &mdash; to keep them consistent with the users' requests &mdash; is <em>strongly
        recommended</em>; we know of no good reason to do otherwise. The configuration option is nevertheless provided for those who
        want a maximum degree of control.
    </p>
    <p><a href="#top">top</a></p>
</main>
