<?php  /**  module/Requests/view/admin/index.phtml  */?>
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>

<p>
    This is the <code>admin/requests</code> page.
</p>
<?php if ($this->pending):
    printf("%d requests pending",$this->pending->getTotalItemCount());
    ?>
    <table>
        <thead>

        </thead>
        <tbody>
<?php $shit =  null; foreach ($this->pending as $r) : $shit = array_merge($r,$r[0]); unset($shit[0])?>
    <tr class="request">
    </tr>
<?php endforeach; ?>
        </tbody>
    </table>
    <?php

endif; ?>
<pre>
<?php print_r($shit) ?>
</pre>
