<?php  /**  module/Requests/view/admin/index.phtml  */
$this->headScript()
    ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
    ->appendFile($this->basePath('js/requests/admin/requests.js'))
    ->appendFile($this->basePath('js/requests/admin/index.js'));
$this->headTitle("admin | requests");
?>
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>
<!-- fuckin' active? <?= $this->active ?> -->
<div id="message-success" class="alert alert-success alert-dismissible" role="alert" style="display:none">
    <p class="mb-0"></p>
    <button type="button" class="close" data-dismiss="alert" aria-label="close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link <?php if ('pending-requests' == $this->active):?>active<?php endif ?>" id="pending-requests-tab" data-toggle="tab" href="#pending-requests" role="tab" aria-controls="pending-requests" aria-selected="true">pending</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <?php if ('scheduled-requests' == $this->active):?>active<?php endif ?>" id="scheduled-requests-tab" data-toggle="tab" href="#scheduled-requests" role="tab" aria-controls="scheduled-requests" aria-selected="false">scheduled</a>
  </li>
  <!-- <li class="nav-item">
    <a class="nav-link" id="past-requests-tab" data-toggle="tab" href="#past-requests" role="tab" aria-controls="past-requests" aria-selected="false">previous</a>
  </li> -->
</ul>
<div class="tab-content" id="tab-content">
    <div class="tab-pane fade<?php if ('pending-requests' == $this->active):?> show active<?php endif ?> py-3" id="pending-requests" role="tabpanel" aria-labelledby="pending-requests-tab"><?php
    if ('pending-requests' == $this->active):
            echo $this->partial('partials/pending-requests-table',['csrf'=>$this->csrf,'paginator'=>$this->paginator,'defendants'=>$this->defendants]);
    endif;
  ?></div>
  <div class="tab-pane fade<?php if ('scheduled-requests' == $this->active):?> show active<?php endif ?> py-3" id="scheduled-requests" role="tabpanel" aria-labelledby="scheduled-requests-tab">
      <?php if ('scheduled-requests' == $this->active):
          echo $this->partial('partials/scheduled-requests-table',['paginator'=>$this->paginator,'defendants'=>$this->defendants]);
      endif;
       ?>
  </div>
  <!-- <div class="tab-pane fade py-3" id="past-requests" role="tabpanel" aria-labelledby="past-requests-tab">
      <p>
         previous requests to go here
      </p>
  </div> -->
</div>


<?php // print_r($r) //
/*
Array
(
    [type] => probation PSI interview
    [judge] => Marrero
    [location] => MDC Brooklyn
    [language] => Spanish
    [id] => 20506
    [date] => DateTime Object
        (
            [date] => 2019-01-22 00:00:00.000000
            [timezone_type] => 3
            [timezone] => America/New_York
        )

    [time] => DateTime Object
        (
            [date] => 1970-01-01 16:00:00.000000
            [timezone_type] => 3
            [timezone] => America/New_York
        )

    [docket] => 2011-CR-0740
    [extraData] => []
)
 */
 ?>
