<?php
/**
 *  module/InterpretersOffice/view/interpreters-office/auth/login.phtml
 *  view script for login form
 * @todo don't call get() multiple times for same element
 */
//$this->headScript()->appendFile($this->basepath().'/js/query-ui.min.js');
//$this->headScript()->appendFile($this->basepath().'/js/login.js');
$this->headTitle($this->title);
?>
<h2 class="navigation text-center my-3">user login</h2>
<?php
foreach (['success','default','error','info','warning'] as $ns) {
    echo $this->flashMessenger()->render($ns, ['alert', 'alert-dismissible', "alert-{$ns}"]);
}
?>
<div class="row">
    <div class="mx-auto">
            <!--<p style="margin:1em 0 2em 0;font-size:120%">Please log in to continue.</p>-->
            <?php if ($this->status && $this->status != \Laminas\Authentication\Result::SUCCESS) :?>
            <div class="alert alert-warning alert-dismissible">authentication failed: invalid identity and/or password. <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
            <?php else :?>
            <?php endif;?>
        <?php echo $this->partial('partials/login.phtml',['form'=>$this->form, 'warning'=>$this->warning]);?>
        <p class="mt-3 mb-1"><a href="<?php echo $this->url('account/register') ?>">Need to create a user account?</a></p>
        <p class="mt-0"><a href="<?php echo $this->url('account/request-password') ?>">Forgot password?</a></p>
    </div>
</div>
<!-- scratch
<div class="text-center border"><button class="btn btn-primary btn-lg" style="background: linear-gradient(180deg, #4D82B6, #2991F9)">a button</button></div>
-->
