<?php /** module/Admin/view/interpreters-office/admin/locations/form.phtml */ 
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;
$formAction = strstr($this->title,'add') ? $this->url('locations/add') 
	:  $this->url('locations/edit',['id' => $this->id ]);
$form = $this->form;
$form->add([
	'name'=>'submit',
	'type'=>'Zend\Form\Element\Submit',
	'attributes' => ['value'=>'submit'],
])->setAttribute('method', 'post')->setAttribute('action', $formAction);

?>


our form action will be <?=$formAction?>
<div class="center-block" style="max-width:750px"><!-- wrapper -->
<h2><?php echo $this->title ?></h2>
<?php
$form->prepare();
echo $this->form()->openTag($form);?>
<div class="form-group"><?php 
$name = $form->get('name');
echo $this->formLabel($name),$this->formText($name),$this->formElementErrors($name);
?>
</div>
<div class="form-group"><?php 
$location_type = $form->get('type'); 
echo $this->formLabel($location_type),$this->formSelect($location_type),$this->formElementErrors($location_type);
?>
</div>
<div class="form-group"><?php 
$parentLocation = $form->get('parentLocation'); 
echo $this->formLabel($parentLocation),$this->formSelect($parentLocation),$this->formElementErrors($parentLocation);
?>
</div>
<div class="form-group"><?php 
 $active = $form->get('active');$isActive = $active->getValue();
 echo $this->formLabel($active); ?>
    <br>
    <input type="radio" name="active" value="1"<?php if ($isActive):?> checked="checked"<?php endif;?>> yes&nbsp;&nbsp;&nbsp;
    <input type="radio" name="active" value="0"<?php if (! $isActive):?> checked="checked"<?php endif;?>> no
<?php
 echo $this->formElementErrors($active);
?>
</div>
<div class="form-group"><?php 
$comments = $form->get('comments'); 
echo $this->formLabel($comments),$this->formTextArea($comments),$this->formElementErrors($comments);
?>
</div>
<div class="form-group"><?php 
echo $this->formSubmit($form->get('submit'));
echo $this->formElement($form->get('id'));
?>
</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->

