<?php
/**
 *  module/Admin/view/interpreters-office/admin/locations/form.phtml
 *  view script for rendering locations create|update form
 */
$this->headTitle($this->title);
$this->headScript()->appendFile($this->basePath('/js/locations-form.js'));
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php

return;
$form = $this->form;
endif;
$action = $this->layout()->action;
if ($action == 'add') :
    $actionAttrib = $this->url('locations/add');
    $delete_button = false;
else :
    $entity = $form->getObject();
    $actionAttrib = $this->url('locations/edit', ['id' => $entity->getId()]);
    $form->setAttribute('data-location_name', $entity->getName());
    $delete_button = ! $entity->hasRelatedEntities();
endif;
$form->setAttribute('action', $actionAttrib);
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
        'attributes' => ['value' => 'save','class' => 'btn btn-success btn-lg'],
])->setAttribute('data-redirect_url', $this->url("locations"));
?>
<div class="center-block" style="max-width:750px"><!-- wrapper -->
<h2><?php echo $this->navigation('Zend\Navigation\Admin_Breadcrumbs')->breadcrumbs() ?></h2>
<?php
$form->prepare();
echo $this->form()->openTag($form);?>
<div class="form-group"><?php
$name = $form->get('name');
echo $this->formLabel($name),$this->formText($name),$this->formElementErrors($name);
?>
</div>
<div class="form-group"><?php
$location_type = $form->get('type');
if ($this->type_id) :
    $location_type->setValue($this->type_id);
endif;
echo $this->formLabel($location_type),$this->formSelect($location_type),$this->formElementErrors($location_type);
?>
</div>
<div class="form-group"><?php
$parentLocation = $form->get('parentLocation');
echo $this->formLabel($parentLocation),$this->formSelect($parentLocation),$this->formElementErrors($parentLocation);
?>
</div>
<div class="form-group"><?php
 $active = $form->get('active');
$isActive = $active->getValue();
 echo $this->formLabel($active); ?>
    <br>
    <input type="radio" id="active" name="active" value="1"<?php if ($isActive) :
?> checked="checked"<?php
                                                           endif;?>> yes&nbsp;&nbsp;&nbsp;
    <input id="active_0" type="radio" name="active" value="0"<?php if (! $isActive) :
?> checked="checked"<?php
                                                             endif;?>> no
<?php
 echo $this->formElementErrors($active);
?>
</div>
<div class="form-group"><?php
$comments = $form->get('comments');
echo $this->formLabel($comments),$this->formTextArea($comments),$this->formElementErrors($comments);
?>
</div>
<div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
    <?php
    $csrf = $form->get('csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    echo $this->formElement($form->get('id'));
    echo $this->formSubmit($form->get('submit'));
    if ($delete_button) :
        ?><input id="btn-delete" type="button" class="btn btn-lg btn-warning" title="delete this location from your database" value="delete" id="btn-delete"><?php
    endif;
    ?></div>
</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
