<?php 
/** 
 * module/Admin/view/interpreters-office/admin/locations/form.phtml 
 * view script for displaying locations. work in progress.
 */ 
?>

<h2>locations</h2>

<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) : echo $messenger->render('success',['alert','alert-success',]); endif;
?>
<div class="list-group" style="max-width: 400px">
<p>Choose a type to display</p>
<ul class="list-group">
<?php foreach ($this->locationTypes as $t) : ?>
<li class="list-group-item"><span class="badge"><?php echo $t['total']?></span>
    <a href="<?php echo $this->url('locations/type',['id'=>$t['id']])?>"><?php echo $t['type'] ?></a>
  </li>
<?php endforeach ?>
</ul>

