<?php
/**
 * module/Admin/view/interpreters-office/admin/locations/form.phtml
 * view script for displaying locations. work in progress.
 */
$this->headTitle($this->title);
?>

<h2>locations</h2>

<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
endif;
?>
<div class="list-group" style="max-width: 400px">
<p>Choose a type to display</p>
<ul id="locations-list" class="list-group">
<?php foreach ($this->locationTypes as $t) : ?>
<li class="list-group-item"><span class="badge"><?php echo $t['total']?></span><?php
    $url = $this->url('locations/type', ['id' => $t['id']]);
    ?><a href="<?php echo $url?>"><?php echo $this->escapeHtml($t['type']) ?></a>    
  </li>
<?php endforeach ?>
</ul>
<script type="text/javascript">
$(function(){
    $('#locations-list > li > a ').on("click",function(event){
        event.preventDefault();
        console.log("click");
        var listItem = $(this).closest('li');
        var subList = listItem.children('ul');
        if (subList.length) {
            subList.toggle("slow");
        } else {
            subList = $('<ul>').addClass('list-group subgroup').hide();
            items = [];
            $.getJSON(this.href,function(data){
                if (! data.length) {
                    items[0] = $('<li>').addClass('list-group-item').text('no locations found');
                } else {//*/
                    for (i = 0; i < data.length; i++) {
                        var text = data[i].name;
                        if (data[i].parent) {
                            text += ", "+data[i].parent;
                        }
                        items[i] = $('<li>').text(text).addClass('list-group-item');
                    }
                } 
                subList.append(items);
                listItem.append(subList);
                subList.show("slow");
            });
        }
    })
});

</script>
