<?php
use InterpretersOffice\Admin\Form\View\Helper\LanguageElementCollection;

/**
 *  module/Admin/view/interpreters-office/admin/people/form.phtml
 *  view script for rendering interpreters create|update form
 */
$this->headTitle('admin | interpreters | '.$this->layout()->action);
$this->headLink()
        ->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
$this->headScript()
        ->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'))
        ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
        ->appendFile($this->basePath('js/interpreter-form.js'));
echo $this->errorMessage($this->errorMessage);
if ($this->errorMessage) :
    return;
endif;
$formAction = $this->layout()->action == 'add' ? $this->url('interpreters/add')
    : $this->url('interpreters/edit', ['id' => $this->id ]);

$form = $this->form;
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
    'attributes' => ['value' => 'save','class' => 'btn btn-success btn-lg'],
])->setAttribute('method', 'post')
   ->setAttribute('action', $formAction)
   ->setAttribute('class', 'form-horizontal');
?>
<div class="mx-auto" style="max-width:700px;"><!-- wrapper -->

    <h2 class="mb-3"><h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2></h2>
    <?php
    $form->prepare();
    $fieldset = $form->get('interpreter');
    /** tmp      */
    //$fieldset->get('lastname')->setValue("Boink");
    //$fieldset->get('firstname')->setValue("Doink");
    /** ========*/
    echo $this->form()->openTag($form);?>
    <!-- nav tabs --><!-- -->
    <ul class="nav nav-tabs" id="nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="true">contact</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" id="languages-tab" data-toggle="tab" href="#languages" role="tab" aria-controls="languages" aria-selected="false">languages &amp; notes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="administrative-tab" data-toggle="tab" href="#administrative" role="tab" aria-controls="administrative" aria-selected="false">administrative/security</a>
      </li>
    </ul>
    <!-- /nav tabs  -->
    <!-- tab panes -->
    <div class="tab-content pt-3">
        <div class="tab-pane active" id="contact" role="tabpanel" aria-labelledby="contact-tab"><!-- contact -->
            <?php foreach (['lastname','firstname','middlename','email','office_phone','mobile_phone','home_phone',
                        'address1','address2','city','state', 'zip'  ] as $elementName) :
                            $element = $fieldset->get($elementName);
    ?><div class="form-group form-row">
                        <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
                        <div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element) ?>
                        </div>
                    </div>
            <?php endforeach; ?>
        </div><!-- /contact -->
        <div class="tab-pane" id="languages" style="min-height: 400px" role="tabpanel" aria-labelledby="languages-tab">
              <div class="form-group"><?php // select element for choosing languages //?>
                <div class="col-sm-10 col-sm-offset-2 form-inline"><?php
                        $languageSelect = $fieldset->get('language-select');
                        echo $this->formSelect($languageSelect),$this->formElementErrors($languageSelect) ;
                ?><button id="btn-add-language" class="btn btn-info" title="add this language">
                            <span class="fas fa-plus" aria-hidden="true"></span>
                            <span class="sr-only">add language</span></button><?php
                         /** @todo display fieldset validation errors ? */
                            ?></div>
            </div>
            <div class="form-group form-row" id="languages-div">
            <!--languages-div -->
            <?php
            $collection = $fieldset->get('interpreterLanguages');
            $helper = (new LanguageElementCollection())->setView($this);
            echo $helper();
            $collectionErrors = $this->formElementErrors($collection);
            if (stristr($collectionErrors, 'language is required')) :
                echo $collectionErrors;
            endif;
            ?>
            </div><!-- /languages-div -->
            <?php $element = $fieldset->get('comments');?>
            <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
            <div class="col-sm-9" style="margin-bottom:1em"><?php echo $this->formElement($element), $this->formElementErrors($element)?>
            </div>

        </div><!-- /languages panel -->
        <!-- admin panel ------------->
        <div class="tab-pane" id="administrative" role="tabpanel" aria-labelledby="administrative-tab">
        <?php if ($this->vault_error) :?>
            <div class="alert alert-warning py-2 px-3">
                Your application configuration has the Vault module enabled for securing sensitive interpreter data,
                but this service's health check responded with the message <strong><?php echo $this->vault_error ?></strong>
                This data therefore cannot be read or written. Please contact your site administrator for assistance.
            </div>
            <?php
            $fieldset->get('dob')->setAttribute('disabled', 'disabled');
            $fieldset->get('ssn')->setAttribute('disabled', 'disabled');
        endif;
if ($this->has_related_entities) :
    $fieldset->get('hat')->setAttribute('disabled', 'disabled');
endif;?>
        <?php foreach (['hat','active','fingerprintDate','securityClearanceDate','contractExpirationDate','oathDate',] as $elementName) :
                    $element = $fieldset->get($elementName);
                    $value = $element->getValue();
            if (is_object($value) && $value instanceof \DateTime) :
                $element->setValue($value->format('m/d/Y'));
            endif;
            ?>
                <div class="form-group form-row">
                    <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
                    <div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element)                   ?>
                    </div>
                </div>
        <?php endforeach; ?>
                <!-- They say:
                    "Do not mix form groups or grid column classes directly with input groups.
                    Instead, nest the input group inside of the form group or grid-related element."
                -->
                <?php
                if (! $this->obscure_values) : // regular plain-text elements
                    foreach (['dob','ssn'] as $elementName) :
                        if (! $fieldset->has($elementName)) {
                            continue;
                        }
                        $element = $fieldset->get($elementName);
                        ?>
                <div class="form-group form-row">
                    <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
                    <div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element) ?></div>
                </div><?php
                    endforeach;
                else :  // should be obscured, until they re-authenticate/decrypt
                    foreach (['dob','ssn'] as $elementName) :
                        if (! $fieldset->has($elementName)) :
                            break;
                        endif;
                        $element = $fieldset->get($elementName);?>
                <div class="form-group form-row">
                    <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
                        <?php $encrypted = $element->getValue();
                        if (! $encrypted) : // nothing to obscure
                            ?><div class="col-sm-9"><?php echo $this->formElement($element),$this->formElementErrors($element) ?></div><?php
                        else :  // display text inputs as encrypted/disabled
                            $element->setAttribute('disabled', 'disabled');?>
                    <div class="col-sm-9 encrypted">
                            <?php
                            $element->setValue('**************');
                            ?><div class="input-group"><?php echo $this->formElement($element)?><button data-toggle="modal" data-target="#login-modal" title="re-authenticate to view or edit sensitive data fields" class="btn btn-info" type="button"><span class="fas fa-unlock"></span><span class="sr-only">unlock</span></button>
                            <?php
                            echo $this->formElementErrors($element);
                            $hidden = (new \Zend\Form\Element\Hidden('encrypted.'.$elementName))->setValue($encrypted);
                            echo $this->formHidden($hidden);
                            ?>
                        </div>
                    </div>
                        <?php endif;?>
                </div>
                        <?php
                    endforeach;
                endif; ?>
        </div>
    </div>
    <div style="margin-top:1em" class="pt-2 row border border-right-0 border-left-0 border-bottom-0" >
        <div class="col-sm-9 offset-sm-3">
            <?php
            $csrf = $form->get('csrf');
            echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
            echo $this->formHidden($fieldset->get('id'));
            echo $this->formSubmit($form->get('submit'));
            if ($this->id && ! $this->has_related_entities) :
            ?> <button id="btn-delete" type="button" class="btn btn-warning btn-lg" title="delete this interpreter" name="delete">delete</button><?php
            endif;
            ?>
        </div>
    </div>

    <?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
<?php if ($this->layout()->action == 'edit') :
    echo $this->render('modal-login');
endif;
