<?php /** module/Admin/view/interpreters-office/admin/interpreters/view.phtml */
$i = $this->interpreter;
?>

<div class="card mb-2 mx-auto" style="max-width:1000px">
    <div class="card-header text-center font-weight-bold bg-light">
        <h2>
        <?php echo $this->escapeHtml("{$i->getLastname()}, {$i->getFirstname()} {$i->getMiddleName()}");?>
        </h2>
        <?php echo $i->getHat() ;

            $languages = [];
        foreach ($i->getInterpreterLanguages() as $il) :
            $languages[] = (string)$il->getLanguage();
        endforeach;
            $label = 'language';
        if (count($languages) > 1) :
            $label .= 's';
        endif;

        ?>
    </div>
    <div class="card-body bg-light">
        <div class="row">
            <div class="col-2 text-md-right"><?php echo $label ?></div>
            <div class="col-4" style="font-size:110%;line-height: 120%"><?php echo implode(', ', $languages);?></div>
            <div class="col-6 border border-right-0 border-top-0 border-bottom-0">
                <address style="line-height: 120%">
                <?php echo $this->escapeHtml($i->getAddress1()); ?><br>
                <?php $addr2 = $i->getAddress2();
                if ($addr2) :
                    echo $this->escapeHtml($addr2),'<br>';
                endif;  ?>
                <?php
                 $city = $i->getCity();
                if ($city) :
                    echo $this->escapeHtml($city);
                endif;
                 $state = $i->getState();
                if ($state) :
                    echo $city ? ', ' : '';
                    echo $this->escapeHtml($state);
                endif;
                 $zip = $i->getZip();
                if ($zip) :
                    echo $state ? ' ' : '';
                    echo $this->escapeHtml($zip);
                endif;
                 $country = $i->getCountry();
                if ($country && 'United States' != $country) :
                    echo "<br>$country";
                endif;
                    ?>
                </address>
            </div>
            <div class="col-2 text-md-right">active</div><div class="col-4"><?php echo $i->getActive() ? "yes" : "no"?></div>
        <?php
            $email = $i->getEmail();?>
            <div class="col-2 text-md-right">email <span class="fas fa-envelope mr-2 text-info"></span></div>
            <div class="col-4"><?php echo $email ?: '<span class="text-muted">&mdash;</span>' ?></div><?php
            foreach (['mobile','office','home'] as $phone) :
                $number = $i->{'get'.ucfirst($phone).'Phone'}();
                ?>
            <div class="col-2 text-md-right"><?php echo $phone ?> <span class="fas fa-phone fa-rotate-180 text-info"></span></div>
            <div class="col-4"><?php echo $number ?: '<span class="text-muted">&mdash;</span>' ?></div>
            <?php
            endforeach;
            ?>
            <div class="col-2 text-md-right">fingerprinted on </div>
            <div class="col-4">
                <?php $fingerprinted = $i->getSecurityClearanceDate();
                if ($fingerprinted) :
                    echo $fingerprinted->format('m/d/Y');
                else :
?><span class="text-muted">&mdash;</span><?php
                endif;?>
            </div>
            <div class="col-2 text-md-right">security cleared on</div>
            <div class="col-4">
                <?php $clearance = $i->getSecurityClearanceDate();
                if ($clearance) :
                    echo $clearance->format('m/d/Y');
                else :
?><span class="text-muted">&mdash;</span><?php
                endif;?>
            </div>
            <div class="col-2 text-md-right">oath taken on</div>
            <div class="col-4">
                <?php $oath = $i->getOathDate();
                if ($oath) :
                    echo $oath->format('m/d/Y');
                else :
?><span class="text-muted">&mdash;</span><?php
                endif;?>
            </div>
            <div class="col-2 text-md-right">contract expiration</div>
            <div class="col-4">
                <?php $contract_exp = $i->getContractExpirationDate();
                if ($contract_exp) :
                    echo $contract_exp->format('m/d/Y');
                else :
?><span class="text-muted">&mdash;</span><?php
                endif;?>
            </div>
            <div class="col-2 text-md-right">date of birth
            </div>
            <div class="col-3" id="dob">
                <?php
            /**/
                $encrypted_dob = $i->getDob();
                if (! $encrypted_dob) :
                    ?><span class="text-muted">&mdash;</span><?php
                else :
                    echo $this->formHidden((new \Zend\Form\Element\Hidden('encrypted_dob'))
                            ->setAttributes(['id' => 'encrypted_dob'])
                            ->setValue($encrypted_dob));

                ?><span style="color:gray">**********</span><button data-toggle="modal" data-target="#login-modal" title="re-authenticate to display dob and/or social security number" class="btn btn-info btn-sm float-right mr-3" type="button"><span class="fas fa-unlock"></span><span class="sr-only">unlock</span></button>
                    <?php
                endif;
                ?>

            </div>
            <div class="col-2 text-md-right">social security</div>

            <div class="col-3" id="ssn">
                <?php
            /**/
                $encrypted_ssn = $i->getSsn();
                if (! $encrypted_ssn) :
                    ?><span class="text-muted">&mdash;</span><?php
                else :
                    echo $this->formHidden((new \Zend\Form\Element\Hidden('encrypted_ssn'))
                            ->setAttributes(['id' => 'encrypted_ssn'])
                            ->setValue($encrypted_ssn));

                ?><span style="color:gray">**********</span><button data-toggle="modal" data-target="#login-modal" title="re-authenticate to display dob and/or social security number" class="btn btn-info btn-sm float-right mr-3" type="button"><span class="fas fa-unlock"></span><span class="sr-only">unlock</span></button>
                    <?php
                endif;
                ?>
            </div>
            <div class="w-100"></div>
            <div class="col-3 text-md-right mt-2 pt-2">comments</div>
            <div class="col-8 border mt-2 px-2 py-2" style="line-height: 120%"><?php echo $i->getComments() ?>
            </div>
            <div class="w-100"></div>
            <div class="col-12 text-center pt-2"><a href="<?php echo $this->url('interpreters/edit', ['id' => $i->getId()])?>" class="btn btn-primary">edit</a></div>
        </div>
    </div>
</div>
<?php echo $this->render('modal-login');
