<div class="form-group row">
    <label class="col-form-label col-sm-3" for="start_date">
        start date
    </label>
    <div class="col-sm-9">
        <input class="form-control" type="text" name="datepicker_start_date" id="datepicker_start_date" value="">
        <input class="form-control" type="hidden" name="start_date" id="start_date" value="">
    </div>
</div>
<div class="form-group row">
    <label class="col-form-label col-sm-3" for="autocomplete-members">
        rotation members
    </label>
    <div class="col-sm-9">
        <input class="form-control" type="text" aria-describedby="member-help" placeholder="last name[, first name]" name="members[]" id="autocomplete-members" value="">
        <small id="member-help" class="form-text text-muted">type the name of the person you want to add to the rotation</small>
        <ul id="members" class="list-group"></ul>
        <small id="member-sort-help" class="form-text text-muted" hidden>you can drag and drop names to modify the rotation order</small>
    </div>
</div>
