<div class="form-group row">
    <label class="col-form-label col-sm-3" for="start_date">
        start date
    </label>
    <div class="col-sm-9">
        <input class="form-control" type="text" name="start_date" id="start_date" value="">
    </div>
</div>
<div class="form-group row">
    <label class="col-form-label col-sm-3" for="autocomplete-members">
        rotation members
    </label>
    <div class="col-sm-9">
        <input class="form-control" type="text" aria-describedby="member-help" placeholder="last name[, first name]" name="members[]" id="autocomplete-members" value="">
        <small id="member-help" class="form-text text-muted">type the name of the person you want to add to the rotation</small>
    </div>
</div>
