<?php /** module/Admin/view/interpreters-office/admin/defendants/form.phtml */
$this->headScript()->appendFile($this->basePath('/js/defendant-form.js'));
$action = $this->layout()->action == 'add' ? $this->url('admin-defendants/add')
        : $this->url('admin-defendants/edit', ['id' => $form->getObject()->getId() ]);
$form = $this->form;
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
    'attributes' => ['value' => 'save','id'=> 'btn-submit', 'class' => 'btn btn-success btn-lg mt-2'],
])->setAttribute('method', 'post')->setAttribute('action', $action);
$this->headTitle('admin | defendants');
$form->prepare();
?>
<div class="center-block mx-auto" style="max-width:500px"><!-- wrapper -->
    <h2 class="navigation mb-3 mt-4"><?php echo $this->navigation('adm_breadcrumbs')->breadcrumbs() ?></h2>
<?php
    echo $this->form()->openTag($form);
    ?>
    <p class="duplicate-name duplicate-name-instructions" style="display:none">There already exists an inexact duplicate of this name in your database: <span id="deft-existing-duplicate-name" style="font-weight:bold"></span>. Please choose one of the following:</p>
    <div id="duplicate_resolution" class="form-group duplicate-resolution-radio mb-1" style="display:none" >
        <?php $opts = $form->get('duplicate_resolution')->getValueOptions();
        foreach($opts as $value => $label):
            ?><div class="form-check"><input name="duplicate_resolution" value="<?php echo $value?>" class="form-check-input" type="radio" id="radio-<?php echo $value?>">
            <label for="radio-<?php echo $value?>" name="duplicate_resolution" value="<?php echo $value?>" class="form-check-label"><?php echo $label ?></label></div>
                <?php
        endforeach;?>
    </div>
    <p class="duplicate-name" style="display:none">
    <button id="btn-use-existing" class="btn btn-outline-primary btn-block mb-0 pl-4 text-left">discard my changes and use existing</button>
    <button id="btn-update-existing" class="btn btn-outline-primary btn-block border-top-0 mt-0 pl-4 text-left">apply my changes to existing name</button>
    <button id="btn-cancel" class="btn btn-outline-primary btn-block border-top-0 mt-0 pl-4 text-left" title="close this dialog">never mind, get me out of here</button>
    </p >
    <div class="form-group"><?php
    $surname = $form->get('surnames');
    echo $this->formLabel($surname),$this->formElement($surname), $this->formElementErrors($surname);
    ?>
    </div>
    <div class="form-group"><?php
    $given_name = $form->get('given_names');
    echo $this->formLabel($given_name),$this->formElement($given_name),$this->formElementErrors($given_name);
    ?>
    </div>
    <?php
    if ($this->occurrences):?>
    occurrences <span class="text-muted">-- select the contexts where this update should apply:</span><br>
    <div id="occurrences" class="form-group form-check mb-2">
        <?php
        foreach($this->occurrences as $i => $item):
                $value = json_encode($item);
            ?>
            <input class="form-check-input" type="checkbox" name="occurrences[]" value="<?php echo $this->escapeHtml($value)?>" <?php
                if (in_array($value,$this->checked)):?> checked="checked"<?php endif;
            ?> id="checkbox-<?php echo $i?>">
            <label class="form-check-label" for="checkbox-<?php echo $i?>"><?php
                printf("%s - %s (%d events)",$item['docket']?:"(no docket numer)",$item['judge'],$item['events']);
            ?></label><br>
        <?php endforeach;?>
    </div>

<?php else: echo "daFUQ???";endif;
    $csrf = $form->get('defendant_csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    echo $this->formElement($form->get('id'));
if (! $this->xhr) :
    echo $this->formSubmit($form->get('submit'));
endif;
    echo $this->form()->closeTag() ?>
</div>
