<main style="max-width:600px" class="center-block mx-auto">

<h2 class="navigation mb-3 mt-4"><?php echo $this->navigation('adm_breadcrumbs')->breadcrumbs() ?></h2>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
endif;
echo $messenger->render('error', ['alert', 'alert-dismissible', 'alert-danger']);
?>
<h3>to do</h3>
<p>more</p>
</main>
