<?php
if ($this->paginator):
        $count = $this->paginator->getTotalItemCount();
        $what = 'request';
        if ($count > 1) :
            $what .= 's'; // pluralize
        endif;
    else:
        $count = "no";
        $what = 'requests';
    endif;
?><p><?php printf('You have <span id="requests-scheduled">%s %s</span> scheduled for today or later',$count,$what);?>.<?php
$pages = $this->paginator->count();
if ( $pages > 1) : printf(' Showing page %d of %d',$this->paginator->getCurrentPageNumber(),$pages); endif;
?></p>
<table class="table table-bordered table-sm">
    <thead>
        <tr>
            <th class="text-info font-weight-normal">date</th>
            <th class="text-info font-weight-normal d-md-none d-lg-table-cell">time</th>
            <th class="text-info font-weight-normal">language</th>
            <th class="text-info font-weight-normal">type</th>
            <th class="text-info font-weight-normal d-md-none d-lg-table-cell">location</th>
            <th class="text-info font-weight-normal d-md-none d-lg-table-cell">docket</th>
            <th class="text-info font-weight-normal">judge</th>
            <th class="text-info font-weight-normal" colspan="2">defendants</th>
        </tr>
    </thead>
    <tbody data-csrf="<?php echo $this->csrf?>">
    <?php if ($this->paginator && $this->paginator->getTotalItemCount()):?>
    <?php foreach ($this->paginator as $r) : $r = array_merge($r,$r[0]); unset($r[0])?>
    <tr class="request" data-id="<?php echo $r['id']?>">
        <td><?php echo $r['date']->format('d-M-Y')?></td>
        <td><?php echo $r['time']->format('g:i a')?></td>
        <td class="language"><?php echo $r['language']?></td>
        <td><?php echo $r['type']?></td>
        <td><?php echo $r['location']?></td>
        <td><?php echo $r['judge']?></td>
        <td><?php echo substr($r['docket'],2)?></td>
        <td><?php echo $this->defendants($r['id'])?></td>
        <td><a class="fas fa-search-plus" title="view details" href="<?php echo $this->url('admin-requests/view',['id'=>$r['id']])?>"><span class="sr-only">view details</span></a></td>
    </tr>
    <?php endforeach; endif;?>
    </tbody>
</table>
<?php   echo $this->paginationControl($this->paginator,'sliding', 'partials/pagination_control',
['route' => 'admin-requests/scheduled']);?>
