<?php
if ($this->paginator):
        $count = $this->paginator->getTotalItemCount();
        $what = 'request';
        if ($count > 1) :
            $what .= 's'; // pluralize
        endif;
    else:
        $count = "no";
        $what = 'requests';
    endif;
?><p><?php printf('You have <span id="requests-pending">%s %s</span> scheduled for today or later',$count,$what);?></p>
<table class="table table-bordered">
<thead></thead>
<tbody data-csrf="<?php echo $this->csrf?>">
<?php if ($this->paginator):?>
<?php foreach ($this->paginator as $r) : $r = array_merge($r,$r[0]); unset($r[0])?>
<tr class="request" data-id="<?php echo $r['id']?>">
    <td><?php echo $r['date']->format('d-M-Y')?></td>
    <td><?php echo $r['time']->format('g:i a')?></td>
    <td class="language"><?php echo $r['language']?></td>
    <td><?php echo $r['type']?></td>
    <td><?php echo $r['location']?></td>
    <td><?php echo $r['judge']?></td>
    <td><?php echo substr($r['docket'],2)?></td>
    <td><?php echo $this->defendants($r['id'])?></td>
    <td class="dropdown dropleft"><a style="color:gray" id="request-dropdown-<?php echo $r['id']?>" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="sr-only">actions</span><span class="fas fa-bars"></span></a>
      <div class="dropdown-menu" aria-labelledby="request-dropdown-<?php echo $r['id']?>">
        <!-- <a title="add this request to the schedule" class="dropdown-item request-add text-primary" href="<?php echo "#"?>">add to schedule</a> -->
        <!-- <div class="dropdown-divider"></div>  -->
        <a title="view details of this request" class="dropdown-item text-primary" href="/admin/requests/view/<?php echo $r['id']?>">view details</a>
      </div>
    </td>
</tr>
<?php endforeach; endif;?>
</tbody>
</table>
</div>
