<?php
/**
 *  module/Admin/view/interpreters-office/admin/people/form.phtml
 *  view script for rendering people create|update form
 */
$this->headTitle($this->title);
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;
$formAction = strstr($this->title, 'add') ? $this->url('judges/add')
    : $this->url('judges/edit', ['id' => $this->id ]);
$form = $this->form;
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
    'attributes' => ['value' => 'submit'],
])->setAttribute('method', 'post')->setAttribute('action', $formAction)->setAttribute('class', 'form-horizontal')    ;
?>
<div class="center-block" style="max-width:750px"><!-- wrapper -->
<h2><?php echo $this->title ?></h2>
<?php
$form->prepare();
$fieldset = $form->get('judge');
echo $this->form()->openTag($form);?>
<?php
$flavor = $fieldset->get('flavor');?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $flavor->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formSelect($flavor),$this->formElementErrors($flavor) ?>
    </div>
</div>

<?php // text inputs
$elements = ['lastname','middlename','firstname','email','officePhone',];
?>

<?php
foreach ($elements as $elementName) :
    $element = $fieldset->get($elementName);?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>            
    </div>
</div>
<?php
endforeach;
$courthouse = $fieldset->get('courthouse');
$courtroom = $fieldset->get('courtroom');?>
<div class="form-group">
    <label class="control-label col-sm-3">default location</label>
    <div class="col-sm-9">
        <div class="form-group row">
            <label class="control-label col-sm-2"><?php echo $courthouse->getLabel()?></label>
            <div class="col-sm-10"><?php echo $this->formSelect($courthouse),$this->formElementErrors($courthouse) ?>
            </div>
        </div>
        <div class="form-group row">
            <label class="control-label col-sm-2">courtroom</label>
             <div class="col-sm-10"><?php echo $this->formSelect($courtroom),$this->formElementErrors($courtroom) ?>
                <?php echo $this->formHidden($fieldset->get('defaultLocation')) ?>                 
             </div>
             <div class="col-sm-offset-2 col-sm-10" style="margin-top: 4px">    
                 <button type="button" data-toggle="modal" data-target="#add-location" title="add a new location" id="btn-add-location" class="btn btn-info btn-sm">
                      <span aria-hidden="true" class="icon glyphicon glyphicon-plus"></span> new location 
                </button>
            </div>                
        </div>
    </div>
</div>

<?php if (false) : // this is simpler. maybe we'll change our mind back to this.
    $defaultLocation = $fieldset->get('defaultLocation'); ?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $defaultLocation->getLabel()?></label>
    <div class="col-sm-9">
        <div class="input-group">
            <?php echo $this->formSelect($defaultLocation) ?>    
            <span class="input-group-btn">
                <button type="button" data-toggle="modal" data-target="#add-location" title="add a new location" id="btn-add-location" class="btn btn-info btn-sm">
                  <span aria-hidden="true" class="icon glyphicon glyphicon-plus"></span>  
                </button>   
            </span>
            <?php echo $this->formElementErrors($defaultLocation) ?>
        </div>
    </div>
</div>
<?php endif ?>
<?php
$active = $fieldset->get('active');?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $active->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formCheckbox($active),$this->formElementErrors($active) ?>            
    </div>
</div>
<div class="form-group">
<?php
$hat_id = $form->getObject()->getHat()->getId();
$element = $fieldset->get('hat')->setValue($hat_id);
?>
    <div class="col-sm-offset-3 col-sm-9">
    <?php
        echo $this->formHidden($fieldset->get('hat'));
        echo $this->formHidden($fieldset->get('id'));
        $csrf = $form->get('csrf');
        echo $this->formHidden($csrf), $this->formElementErrors($csrf);
        echo $this->formSubmit($form->get('submit'));
        ?>
    </div>
</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->

<!-- Modal -->
<div class="modal fade" id="add-location" tabindex="-1" role="dialog" aria-labelledby="label-add-location">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="label-add-location">add a courtroom/courthouse</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">cancel</button>
        <button id="btn-add-location-submit" type="button" class="btn btn-primary">add location</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    /** @todo move this to its own file(s) */
    $(document).ready(function(){
        $('#add-location').on('show.bs.modal',function(event){
            console.log("show event fired");
            // event.relatedTarget is the button they clicked
            $('#add-location > div > div > div.modal-body').load(
                '/admin/locations/add?form_context=judges form',
                function(){
                    $('.modal-header .modal-title').text("add a courthouse/courtroom")
                    // use the modal's buttons instead
                    $('#add-location input[name="submit"]').remove();
            });
        });
        $('#courthouse, #courtroom').on('change',function(event){
            var defaultLocation = $('#defaultLocation');
            var selectElement = $(event.target);
            // if the courtroom changed
            if ('courtroom' === selectElement.attr("id")) {
                defaultLocation.val(selectElement.val());
            } else {
                // the courthouse is what changed. if there is no courtroom,
                // the courthouse value becomes the default location value
                if (! $('#courtroom').val()) {
                    defaultLocation.val(selectElement.val());
                }
            }
            console.debug("set defaultLocation value to: "+defaultLocation.val());
        });
        $('#add-location').on("click",'#btn-add-location-submit', function(){
            
            $.post('/admin/locations/add?form_context=judges',$('#add-location form').serialize(),
            function(response){
                console.log("valid? " + response.valid);
                if (! response.valid) {
                   return displayValidationErrors(response.validationErrors);
                }
                $('#add-location').modal("hide");
                $("<option>")
                        .attr({label: response.entity.name, value: response.entity.id})
                        .text(response.entity.name)
                        .appendTo($("#defaultLocation"));
                $("#defaultLocation").val(response.entity.id);
            });
        });
    });
    // borrowed from ourself
    displayValidationErrors = function(validationErrors) {
    $('.validation-error').empty();
    for (var field in validationErrors) {
        //console.log("examining field "+field);
        for (var key in validationErrors[field]) {
            // console.log("examining key "+key);
            var message = validationErrors[field][key];
            var element = $('#' +field);
            var errorDiv = $('#error_'+field);
            if (! errorDiv.length) { errorDiv = null;}
            if (! element.length) { console.log("is there no element #"+field+ " ?");
                // look for an existing div by id
                if ($('#error_'+field).length) {
                    $('#error_'+field).html(message);
                } else {
                    console.warn("no element with id "+field + ", and nowhere to put message "+message);
                }
            } else {
                errorDiv = errorDiv || element.next('.validation-error');
                if (! errorDiv.length) {
                    errorDiv = $('<div/>')
                            .addClass('alert alert-warning validation-error')
                            .attr({id:'error_'+field})
                    .insertAfter(element);
                }
                errorDiv.html(message).show();
            }
            break;
        }
    } 
};
</script>
