<?php
/** 
 *  module/Admin/view/interpreters-office/admin/people/form.phtml 
 *  view script for rendering people create|update form
 */ 
$this->headTitle($this->title);
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
<?php
return;
endif;
$formAction = strstr($this->title,'add') ? $this->url('judges/add') 
	:  $this->url('judges/edit',['id' => $this->id ]);
$form = $this->form;
$form->add([
	'name'=>'submit',
	'type'=>'Zend\Form\Element\Submit',
	'attributes' => ['value'=>'submit'],
])->setAttribute('method', 'post')->setAttribute('action', $formAction)->setAttribute('class', 'form-horizontal')    ;
?>
<div class="center-block" style="max-width:750px"><!-- wrapper -->
<h2><?php echo $this->title ?></h2>
<?php
$form->prepare();
$fieldset = $form->get('judge');
echo $this->form()->openTag($form);?>
<div class="form-group">
<?php
$flavor = $fieldset->get('flavor');?>
    <div class="form-group">
        <label class="control-label col-sm-3"><?php echo $flavor->getLabel()?></label>
        <div class="col-sm-9"><?php echo $this->formSelect($flavor),$this->formElementErrors($flavor) ?>            
        </div>
    </div>
<?php // text inputs
$elements = ['lastname','middlename','firstname','email','officePhone',];
?>
</div>
<div class="form-group">
<?php 
foreach ($elements as $elementName):
$element = $fieldset->get($elementName);?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $element->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>            
    </div>
</div>
<?php
endforeach;
$defaultLocation = $fieldset->get('defaultLocation'); ?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $defaultLocation->getLabel()?></label>
    <div class="col-sm-9">
    <div class="input-group">
        <?php echo $this->formSelect($defaultLocation) ?>    
        <span class="input-group-btn">
            <button title="add a new location" id="btn-add-location" class="btn btn-primary">
              <span aria-hidden="true" class="icon glyphicon glyphicon-plus"></span>  
            </button>   
        </span>
        <?php echo $this->formElementErrors($defaultLocation) ?>
    </div>
</div>
</div>
<?php
$active =  $fieldset->get('active');?>
<div class="form-group">
    <label class="control-label col-sm-3"><?php echo $active->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formCheckbox($active),$this->formElementErrors($active) ?>            
    </div>
</div>
<div class="form-group">
<?php 
$hat_id = $form->getObject()->getHat()->getId(); 
$element = $fieldset->get('hat'); 
$element->setValue($hat_id);
?>
<div class="col-sm-offset-3 col-sm-9">
<?php 
    echo $this->formHidden($fieldset->get('hat'));
    echo $this->formHidden($fieldset->get('id'));
    $csrf = $form->get('csrf'); 
    echo $this->formHidden($csrf), $this->formElementErrors($csrf);
    echo $this->formSubmit($form->get('submit'));?>
</div>
</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->

