<?php
/**
 * module/Admin/view/interpreters-office/admin/judges/index.phtml
 * view script for judges admin main page
 */
$this->headTitle($this->title);?>
<div class="center-block mx-auto" style="max-width:500px"><!-- wrapper -->
<h2 class="navigation mb-3 mt-4"><?php echo $this->navigation('default')->breadcrumbs() ?></h2>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
endif;

if (! $this->judges): ?>
    <div class="alert alert-warning">There are no judges in your database. Go to <a href="/admin/judges/add">add</a> to start adding them.</div>
</div><!-- /wrapper -->
<?php
return;
endif;
?>
<div id="accordion">
<?php
$flavors = array_keys($this->judges);
foreach ($flavors as $flavor):
?>
    <div class="card">
        <div class="card-header" id="heading-<?php echo $flavor ?>">
            <a role="button" class="btn btn-link" data-toggle="collapse" data-target="#<?php echo $flavor ?>" aria-expanded="<?php echo $flavor == $flavors[0] ? "true":"false"?>" aria-controls="<?php echo $flavor ?>">
                <h2>
                <?php echo $flavor ?>
                </h2>
            </a>
        </div>
        <div id="<?php echo $flavor ?>" class="collapse<?php if ($flavor == $flavors[0]): ?> show<?php endif;?>" aria-labelledby="heading-<?php echo $flavor ?>" data-parent="#accordion">
            <div class="card-body">
            <table class="table" style="max-width:400px">
                <?php
                foreach($this->judges[$flavor] as $judge):?>
                <tr>
                    <td class="align-self-center"><?php
                    $name = sprintf("%s, %s %s<br>",$judge['lastname'],$judge['firstname'],$judge['middlename']);
                    printf('<a data-toggle="tooltip" title="edit this database record" href="%s">%s</a>',$this->url('judges/edit',['id'=>$judge['id']]),$name);
                    ?></td><td class="text-md-right">
                        <span style="opacity:.75" class="align-self-center fas fa-<?php echo $judge['active'] ? "check text-success" : "times text-danger"?>"></span>
                    </td>
                    <td class="px-0"><a data-toggle="tooltip" title="edit this database record" href="<?php echo $this->url('judges/edit',['id'=>$judge['id']])?>"><span style="opacity:.75" class="align-self-center fas fa-cog"></span></a></td>
                </tr>
            <?php endforeach;?>
            </table>
        </div>
        </div>
    </div>
<?php
endforeach;
?>
</div><!-- /accordion -->
<a href="<?php echo $this->url('judges/add') ?>" role="button" title="add a new judge" id="btn-add-judge" class="btn btn-info mt-2">
<span aria-hidden="true" class="fas fa-plus"></span> new judge
</a>
</div><!-- /wrapper -->
