<?php 
/** 
 * module/Admin/view/interpreters-office/admin/languages/index.phtml 
 * view script for languages admin main page
 */   
?>
<h2>judges</h2>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) : echo $messenger->render('success',['alert','alert-success',]); endif;

if (! $this->judges): 

?><div class="alert alert-warning">There are no judges in your database. Go to <a href="/admin/judges/add">add</a> to start adding them.</div><?php
return;
endif;