<?php /** bootstrap 4 layout view script */
echo $this->doctype(); $BS_VERSION = 'bootstrap-4.0.0-beta.2';?>
<html lang="en">
  <head>
    <meta charset="utf-8">
     <?php echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, shrink-to-fit=no');?>    
    <meta name="description" content="SDNY Interpreters Office court interpreter management system">
    <meta name="author" content="David Mintz">
    <?php echo $this->headTitle('Court Interpreters Office')->setSeparator(' | ')->setAutoEscape(false) ?>
<?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico']);
  ?>
    <!-- Bootstrap core CSS -->
    <link href="/css/<?php echo $BS_VERSION ?>/bootstrap.min.css" rel="stylesheet"><?php
 $this->headLink()->appendStylesheet($this->basePath('css/style.css'));
                //->prependStylesheet($this->basePath('css/bootstrap/bootstrap-theme.min.css'));
         //->prependStylesheet($this->basePath('css/bootstrap/bootstrap.min.css'))
 echo $this->headStyle();?>
<style type="text/css">
.navbar-custom {
	/* background-image: -webkit-linear-gradient(top,#fff 0,#f8f8f8 100%); */
	/* background-image: -o-linear-gradient(top,#fff 0,#f8f8f8 100%); */
	/* background-image: -webkit-gradient(linear,left top,left bottom,from(#fff),to(#f8f8f8)); */
	background-image: linear-gradient(to bottom,#fff 0,#f8f8f8 100%) !important;
	/* filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff', endColorstr='#fff8f8f8', GradientType=0); */
	filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
	background-repeat: repeat-x;
	border-radius: 4px;
	-webkit-box-shadow: inset 0 1px 0 rgba(255,255,255,.15),0 1px 5px rgba(0,0,0,.075);
	box-shadow: inset 0 1px 0 rgba(255,255,255,.15),0 1px 5px rgba(0,0,0,.075);
    border: 1px solid #e7e7e7 !important;
    /*padding: .5rem 1rem;*/
    padding : .25rem 1rem ;
    background-color: #f8f8f8;    
}
label { text-align:right;}
.navbar-custom a.navbar-brand { color : #777 !important; }
.navbar-custom li > a { color : #555 !important; }
.navbar li.active { background-color: #fff !important; border-radius: 4px; border: 1px solid #9fcdff !important;  }
</style>
  </head>
  <body>
    <div class="container">
    <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3 navbar-custom">
      <a class="navbar-brand" href="#">InterpretersOffice</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar-collapse">
       <?php  echo $this->navigation('default')->menu()->setPartial('partials/navbar_bs4.phtml')?>
        <?php if ($this->layout()->user): // is navbar-right still a thing?  ?>
        <div class="navbar-right" style="padding: 15px 10px;"><?php echo "current user: {$this->layout()->user->username}"?></div>
        <?php endif; ?>        
      </div>
    </nav>
        <?php echo $this->content; ?>
    </div>
<div class="container">
    <footer style="margin-top: 2em; border-top: 1px orange dotted">
        <p>[layout: footer]</p>
    </footer>
</div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <!-- <script>window.jQuery || document.wite('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script> -->
    <!-- <script src="../../../../assets/js/vendor/popper.min.js"></script> -->
    <script src="/js/lib/<?php echo $BS_VERSION ?>/bootstrap.bundle.js"></script>
    <?php echo $this->inlineScript() ?>
    <script>
            basePath = '<?php echo $this->basePath() ?>';
            $(document).ready(function () {
               $('a[href="' + this.location.pathname + '"]').parent().addClass('active');
            });
     </script>
  </body>
</html>
