<?php /** bootstrap 4 layout view script */
echo $this->doctype(); $BS_VERSION = 'bootstrap-4.0.0-beta.2';?>
<html lang="en">
  <head>
    <meta charset="utf-8">
     <?php echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, shrink-to-fit=no');?>    
    <meta name="description" content="SDNY Interpreters Office court interpreter management system">
    <meta name="author" content="David Mintz">
    <?php echo $this->headTitle('Court Interpreters Office')->setSeparator(' | ')->setAutoEscape(false) ?>
<?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico']);
  ?>
    <!-- Bootstrap core CSS -->
    <link href="/css/<?php echo $BS_VERSION ?>/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template <link href="navbar-top.css" rel="stylesheet"> -->
    
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4"><!-- mb-* refers to margin-bottom -->
      <a class="navbar-brand" href="#">Top navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">disabled</a>
          </li>
        </ul>
        <!--  <form class="form-inline mt-2 mt-md-0"> mt-* refers to margin-top
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
              <div class="navbar-right" style="padding: 15px 10px;"><?php if ($this->layout()->user): echo "current user: {$this->layout()->user->username}"; endif;?></div>
      </div>

    </nav>
    <main role="main" class="container">
      <div class="jumbotron">
        <h1>Navbar example</h1>
        <p><?php echo $this->content ?></p>
        <p class="lead">This example is a quick exercise to illustrate how the top-aligned navbar works. As you scroll, this navbar remains in its original position and moves with the rest of the page.</p>      
      </div>
    </main>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <!-- <script>window.jQuery || document.wite('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script> -->
    <!-- <script src="../../../../assets/js/vendor/popper.min.js"></script> -->
    <script src="/js/lib/<?php echo $BS_VERSION ?>/bootstrap.bundle.js"></script>
  </body>
</html>
