<?php
/** layout view script. a work in progress. */
echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Court Interpreters Office')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', ['conditional' => 'lt IE 9',])
        ; ?>

    </head>
    <body>
        <div class="container">
            <div class="row">
            <nav class="navbar navbar-default" role="navigation"><!-- // navbar-fixed-top ? -->
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-main">
                      <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span>
                      <span class="icon-bar"></span><span class="icon-bar"></span>
                  </button>
                <a class="navbar-brand" href="#">InterpretersOffice</a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-main">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home')?>">home</a></li>
                        <li><a href="#">something</a></li>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">admin <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url('languages')?>">languages</a></li>
                            <li><a href="<?php echo $this->url('judges')?>">judges</a></li>
                            <li><a href="<?php echo $this->url('event-types')?>">event-types</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                          </ul>
                        </li>
                      </ul>
                </div>
            </nav>
        </div>
            <?php echo $this->content; ?>
           
            <footer style="margin-top: 2em; border-top: 1px orange dotted">
                <p>[layout: footer]</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <script>
            $(document).ready(function() {
                $('a[href="' + this.location.pathname + '"]').parent().addClass('active');
          });
        </script>
    </body>
</html>
