<?php /** bootstrap 4 layout view script */
echo $this->doctype();
?><html lang="en">
<head>
    <meta charset="utf-8">
        <?php echo $this->headMeta()
         ->appendName('viewport', 'width=device-width, initial-scale=1.0, shrink-to-fit=no');?>
    <meta name="description" content="SDNY Interpreters Office court interpreter management system">
    <meta name="author" content="David Mintz, Interpreters Office, US District Court, Southern District of` New York">
    <?php echo $this->headTitle('Court Interpreters Office')->setSeparator(' | ')->setAutoEscape(false) ?>
    <link href="<?php echo $this->basePath('css/bootstrap/bootstrap.min.css')?>" rel="stylesheet">
<?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->appendStylesheet($this->basePath('css/style.css'))
        ->appendStylesheet($this->basePath('css/jquery-ui.min.css'))
        ->appendStylesheet($this->basePath('css/font-awesome/css/fontawesome-all.min.css'));
echo $this->headStyle();?>
</head>
<body><?php if ($this->layout()->notes_enabled):?>
    <?php echo $this->partial('notes/partials/notes.phtml',
    ['config'=>$this->layout()->note_settings,
    'motd'=>$this->motd,'motw'=>$this->motw,
    'display_notes'=> $this->layout()->display_notes === false ? false:true]
    ) ?>
<?php endif ?>
    <div class="container" style="min-height:400px">
        <nav class="navbar navbar-expand-lg  navbar-light bg-light rounded mb-3 py-1 shadow-sm">
                <a class="navbar-brand" href="<?php echo $this->url('home')?>">InterpretersOffice</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse" id="navbar-collapse">
            <?php if ($this->layout()->navigation_menu):
                echo $this->navigation($this->layout()->navigation_menu)->menu()->setPartial('partials/navbar.phtml'); endif;?>
            <?php $user = $this->layout()->user ?: false; if ($user) :?>
                <div class="dropdown">
                    <a class="btn btn-link dropdown-toggle" role="button" id="btn-user-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="fa fa-user"></span><span class="sr-only">my account</span> <span class="d-none d-xl-inline">
                         welcome <?php echo $this->escapeHtml($user->username != $user->email ? $user->username : "$user->firstname $user->lastname")?></span></a>
                    <div class="dropdown-menu" aria-labelledby="btn-user-menu">
                        <a class="dropdown-item" href="<?php echo $this->url('account/edit-profile')?>">profile</a>
                        <a class="dropdown-item" href="<?php echo $this->url('logout')?>">log out</a>
                    </div>
                </div>
           <?php endif; ?>
          </div>
      </nav>
    <?php  echo $this->content; ?>
    </div>
    <!-- <pre><?php print_r($this->layout()->note_settings)?></pre> -->
    <div class="container">
        <footer class="border-top border-bottom mt-4 text-center text-muted"><?php
            echo
                $this->layout()->organization_name," &bull; ",
                $this->layout()->organization_locality," &bull; ",
                $this->layout()->telephone," &bull; ", $this->layout()->email;
        ?></footer>
    </div>
        <script src="<?php echo $this->basePath('js/lib/jquery/dist/jquery.min.js')?>"></script>
        <script src="<?php echo $this->basePath('js/lib/bootstrap/bootstrap.bundle.js')?>"></script>
        <script src="<?php echo $this->basePath('js/lib/jquery-ui/jquery-ui.js')?>"></script>
        <script src="<?php echo $this->basePath('js/common.js')?>"></script>
        <script src="<?php echo $this->basePath('js/form-utilities.js')?>"></script>
        <script src="<?php echo $this->basePath('js/nav.js')?>"></script>

        <?php
        if ($this->layout()->notes_enabled) :?>
        <script src="<?php echo $this->basePath('js/admin/notes.js')?>"></script>

        <?php  endif; ?>
        <?php echo $this->headScript()?>
        <?php echo $this->inlineScript() ?>
        <script>basePath = '<?php echo $this->basePath() ?>';</script>
  </body>
</html>
