<?php
/** module/Admin/view/interpreters-office/admin/event-types/form.phtml */
$this->headTitle($this->title);
$this->headScript()->appendFile($this->basePath('/js/event-types-form.js'));
$form = $this->form;
$action = $this->layout()->action;
if ($action == 'add') :
    $actionAttrib = $this->url('event-types/add');
else :
    $entity = $form->getObject();
    $actionAttrib = $this->url('event-types/edit', ['id' => $entity->getId()]);
    $form->setAttribute('data-event-type_name', $entity->getName());
endif;
$form->setAttribute('action', $actionAttrib)
    ->setAttribute('data-redirect_url', $this->url('event-types'));
?>
<div class="center-block mx-auto" style="max-width:600px"><!-- wrapper -->
    <h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs() ?></h2>

<?php
echo $this->errorMessage($this->errorMessage);
if ($this->errorMessage): ?></div><?php return; endif;

if ($action == 'add') : ?>
    <p>Use this form to add a new event type. Please be careful
      to avoid adding a type that is a subtype of, or partially redundant with,
      one that already exists.</p>
<?php endif;
$form->add([
    'name' => 'submit',
    'type' => 'Laminas\Form\Element\Submit',
        'attributes' => ['value' => 'save','class' => 'btn btn-success btn-lg'],
])->setAttribute('method', 'post')->setAttribute('action', $actionAttrib);

$form->prepare();
echo $this->form()->openTag($form);?>
<div class="form-group"><?php
$name = $form->get('name');
echo $this->formLabel($name),$this->formElement($name),$this->formElementErrors($name);
?>
</div>
<div class="form-group"><?php
$category = $form->get('category');
echo $this->formLabel($category),$this->formSelect($category),$this->formElementErrors($category);
?>
</div>
<div class="form-group"><?php
$comments = $form->get('comments');
echo $this->formLabel($comments),$this->formElement($comments), $this->formElementErrors($comments);
?>
</div>
<div class="form-group"><?php
echo $this->formSubmit($form->get('submit'));
echo $this->formElement($form->get('id'));
if ($this->has_related_entities === false) :
    ?><input id="btn-delete" type="button" class="btn btn-lg btn-warning" title="delete this event-type from your database" value="delete" id="btn-delete"><?php
endif;
$csrf = $form->get('csrf');
echo $this->formElement($csrf),$this->formElementErrors($csrf);
echo $this->form()->closeTag();
?>
</div>
</div><!-- /wrapper -->
