<?php /** module/Admin/view/interpreters-office/admin/index/index.phtml */
$this->headTitle($this->title);
$this->headScript()->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'));
$this->headStyle()->captureStart();?>
/*.multi-input label, .multi-input div { border : 1px dotted gray; }*/
form { max-width: 900px;}
.multi-input div:first-of-type { padding-right: 0px; }
.multi-input div:last-of-type { padding-left: 0px; }
.multi-input label:last-of-type { text-align:right ; padding-right: 1em; padding-left: 0; }
<?php $this->headStyle()->captureEnd();

//$user = $this->identity() ?>

<div style="max-width:900px" class="mx-auto">
    <h2>administration</h2>
    <div class="row mt-3">
        <div class="col list-group">
            <div class="list-group-item">
                <a href="<?= $this->url('events')?>">scheduling</a><br>
                schedule of court interpreter events
            </div>
            <div class="list-group-item">
                <a href="<?= $this->url('interpreters')?>">interpreters</a><br>
                roster of interpreters
            </div>
            <div class="list-group-item">
                <a href="<?= $this->url('judges')?>">judges</a><br>
                roster of judges
            </div>
            <div class="list-group-item">
                <a href="<?= $this->url('users')?>">users</a><br>
                user account management
            </div>
            <div class="list-group-item">
                <a href="<?= $this->url('people')?>">people</a><br>
                contact information for people in general
            </div>
            <div class="list-group-item">
                <a href="<?= $this->url('languages')?>">languages</a><br>
                languages required in your court
            </div>
        </div>
        <div class="col list-group">

            <div class="list-group-item">
                <a href="<?= $this->url('court-closings')?>">court closings</a><br>
                list of court holidays and ad-hoc closings
            </div>
            <div class="list-group-item">
                <a href="<?= $this->url('locations')?>">locations</a><br>
                locations where interpreting services are rendered
            </div>
            <div class="list-group-item">
                <a href="<?= $this->url('admin-defendants')?>">defendant/etc names</a><br>
                names of non-English-speaking consumers of interpreting services
            </div>
            <div class="list-group-item">
                <a href="<?= $this->url('event-types')?>">event-types</a><br>
                types of court proceedings and ancillary events that involve interpreters
            </div>
        </div>
        <div class="col list-group">
            <div class="list-group-item">
            <a href="<?=$this->url('configuration/requests') ?>"><?=$this->url('configuration/requests') ?></a> here?
            </div>
            <div class="list-group-item">
                thing two
            </div>
            <div class="list-group-item">
                thing three
            </div>
        </div>
    </div>
</div>





<div hidden>
    <p>Note to self:  <a href="https://neilime.github.io/zf-assets-bundle/">neilime.github.io/zf-assets-bundle</a> is worth a look.</p>
<!-- doodle -->
<h3>scratch</h3>
<div class="row">
    <div class="col-6 border"><!-- left side -->
        <form>
            <div class="form-group form-row">
                <label class="col-form-label col-4 border" for="time">time</label>
                <div class="col-3 border"><input class="form-control" type="time" name="time" id="time"></div>
                <label class="col-2 col-form-label border text-center" for="end_time">to</label>
                <div class="col-3 border"><input class="form-control" name="end_time" type="time" id="end_time"></div>
            </div>
            <div class="form-group form-row">
                <label class="col-form-label col-4" for="other-1">some shit</label>
                <div class="col-8">
                    <input class="form-control" name="other-1" id="other-1">
                </div>
            </div>
            </div>
            <div class="col-6 border"><!-- right side -->
            <div class="form-group form-row">
                    <label class="col-form-label col-4" for="other">other input</label>
                     <div class="col-8">
                         <input class="form-control" name="other" id="other">
                     </div>
            </div>
            <div class="form-group form-row">
                    <label class="col-form-label col-4" for="another">yet another</label>
                     <div class="col-8">
                        <input class="form-control" name="another" id="another">
                    </div>
            </div>
        </div>
    </form>
</div>

<div class="row border">
    <div class="col-6 border">shit</div>
    <div class="col-6 border">shit</div>
</div>
<div class="clearfix" style="clear:both" id='debug'></div>
</div>
