<?php /** module/Admin/view/interpreters-office/admin/index/index.phtml */
$this->headTitle($this->title);
$this->headScript()->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'));
$this->headStyle()->captureStart();?>
/*.multi-input label, .multi-input div { border : 1px dotted gray; }*/
form { max-width: 900px;}
.multi-input div:first-of-type { padding-right: 0px; }
.multi-input div:last-of-type { padding-left: 0px; }
.multi-input label:last-of-type { text-align:right ; padding-right: 1em; padding-left: 0; }
<?php $this->headStyle()->captureEnd();
//echo $this->headStyle() ;
$user = $this->identity() ?>
<h2>admin</h2>
<p>hello user <?php echo $user->username ?> in role <?php echo $user->role ?></p>
<p>This is the admin overview page.</p>
<p>Note to self:  <a href="https://neilime.github.io/zf-assets-bundle/">neilime.github.io/zf-assets-bundle</a> is worth a look.</p>
<div style="display:none">
<!-- doodle -->
<h3>scratch</h3>
<div class="row">
    <div class="col-6 border"><!-- left side -->
        <form>
            <div class="form-group form-row">
                <label class="col-form-label col-4 border" for="time">time</label>
                <div class="col-3 border"><input class="form-control" type="time" name="time" id="time"></div>
                <label class="col-2 col-form-label border text-center" for="end_time">to</label>
                <div class="col-3 border"><input class="form-control" name="end_time" type="time" id="end_time"></div>
            </div>
            <div class="form-group form-row">
                <label class="col-form-label col-4" for="other-1">some shit</label>
                <div class="col-8">
                    <input class="form-control" name="other-1" id="other-1">
                </div>
            </div>
            </div>
            <div class="col-6 border"><!-- right side -->
            <div class="form-group form-row">
                    <label class="col-form-label col-4" for="other">other input</label>
                     <div class="col-8">
                         <input class="form-control" name="other" id="other">
                     </div>
            </div>
            <div class="form-group form-row">
                    <label class="col-form-label col-4" for="another">yet another</label>
                     <div class="col-8">
                        <input class="form-control" name="another" id="another">
                    </div>
            </div>
        </div>
    </form>
</div>

<div class="row border">
    <div class="col-6 border">shit</div>
    <div class="col-6 border">shit</div>
</div>
<div class="clearfix" style="clear:both" id='debug'></div>
</div>
