<?php /** module/Admin/view/interpreters-office/admin/index/index.phtml */
$this->headTitle('admin');
$this->headScript()->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'));
$this->headStyle()->captureStart();?>
<?php $this->headStyle()->captureEnd();

//$user = $this->identity() ?>

<div style="max-width:900px" class="mx-auto">
    <h2>administration</h2>
<?php if (false):?>
    <pre>
<?php
    /** @var \InterpretersOffice\Admin\Service\Acl $acl */
    $acl = $this->acl;
    //print_r(get_class_methods($acl));
    $roles = $acl->getRoles();
    $resources = $acl->getResources();
    // print_r($roles);
    // print_r($resources);
    ?>
    </pre>
    <table class="table">
        <tr>
            <th>resource</th>
            <?php foreach (['submitter','staff','manager','administrator'] as $role) { ?><th><?=$role?></th>
    <?php }
    ?></tr><?php
    foreach($resources as $resource) {
        ?><tr>
            <td><?=str_replace('InterpretersOffice\\','IO\\',$resource)?></td>
            <?php foreach (['submitter','staff','manager','administrator'] as $role) { ?>
                <td><?php
                $access = $acl->isAllowed($role,$resource,'index') ? "allowed":"denied";
                $color = $access == 'allowed' ? 'green' : 'red';
                printf('<span style="color:%s">%s</span>',$color,$access);
                ?></td>
            <?php  }?>
        </tr><?php
    }

    ?></table>
<?php endif; ?>
    <div class="row mt-3">
        <div class="col">
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('events')?>">scheduling</a>
                schedule of court interpreter events
            </p>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('interpreters')?>">interpreters</a>
                interpreter contact data, working languages, etc
            </p>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('judges')?>">judges</a>
                roster of judges sitting in your Court
            </p>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('users')?>">users</a>
                user account management
            </p>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('people')?>">people</a>
                contact information for people in general
            </p>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('languages')?>">languages</a>
                languages required in your Court
            </p>
        </div>
        <div class="col">
            <?php if (in_array('InterpretersOffice\Requests',$this->modules)):?>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('admin-requests')?>">requests</a>
                manage requests that have been submitted online
            </p>
            <?php endif ?>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('court-closings')?>">court closings</a>
                official Court holidays and ad-hoc closings
            </p>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('locations')?>">locations</a>
                locations where interpreting services are rendered
            </p>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('admin-defendants')?>">defendant/etc names</a>
                names of non-English-speaking consumers of interpreting services
            </p>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?= $this->url('event-types')?>">event-types</a>
                types of proceedings and ancillary events involving interpreters
            </p>
        </div>
        <div class="col">
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?=$this->url('search') ?>">search</a>
                search your database for past and future interpreter-events based on various criteria
            </p>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?=$this->url('reports') ?>">reports</a>
                generate interpreter activity reports
            </p>
            <?php if (in_array('InterpretersOffice\Admin\Notes', $this->modules)):?>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?=$this->url('notes') ?>">MOTD/MOTW</a>
                notes relevant to a particular day (MOTD) or week (MOTW)
            </p>
            <?php endif ?>
            <p>
                <a class="btn btn-block btn-outline-primary" role="button" href="<?=$this->url('admin/docket-annotations')?>">docket annotations</a>
                notes relevant to a particular case
            </p>           
            <p class="mb-0">
                <a class="btn btn-block btn-outline-primary" role="button" href="<?=$this->url('configuration') ?>">configuration</a>
                configuration settings for
            </p>
            <ul class="mt-1">
                <?php if (in_array('InterpretersOffice\Requests', $this->modules)):?>
                <li>
                    <a href="<?=$this->url('configuration/requests') ?>">Requests module</a>
                </li>
                <?php endif ?>
                <li>
                    <a href="<?=$this->url('configuration/forms') ?>">form/data fields</a>
                </li>
            </ul>
        </div>
    </div>
    <!-- <pre><?php print_r(preg_grep('/InterpretersOffice/',$this->modules))?></pre> -->
</div>

