<?php
/** partial for displaying event details in an email */
?>
<table>
    <tbody>

    <?php foreach (array_keys($this->entity) as $field):
        // need to figure out what to do with this...
        if ($field == 'extraData') : continue; endif;
        if ($field == 'eventType') : $label = 'event type';
        else :
            $label = $field;
        endif;
    ?>
    <tr>
        <td style="border-bottom:1px dotted gray"><?php echo $label ?></td>
        <td style="border-bottom:1px dotted gray"><?php
            echo $this->escaped ? $this->entity[$field] :
            $this->escapeHtml($this->entity[$field]) //echo $this->diff($field)
            ?></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
