<?php
/** partial for displaying event details in an email */
?>
<table style="margin-bottom:1em">
    <tbody>
    <?php $entity = $this->entity; foreach (array_keys($entity) as $field):
        // need to figure out what to do with this...
        if ($field == 'extraData') : continue; endif;
        if ($field == 'eventType' or $field == 'event_type') :
            $label = 'event type';
        else :
            $label = $field;
        endif;
    ?>
    <tr>
        <td style="border-bottom:1px dotted gray"><?php echo $label ?></td>
        <td style="border-bottom:1px dotted gray"><?php
        // the "escaped" flag means it is string data/finished HTML
            echo $this->escaped ? $this->entity[$field] : $this->diff($field)
            ?></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
