<?php
/** partial for displaying event details in an email
 * @todo refactor InterpretersOffice\View\Helper\Diff because there is
 * not supposed to be any before/after involved here unless it's already
 * rendered as HTML, in which case it's already taken care of.
 */
use InterpretersOffice\View\Helper\Diff;
$fields = [
    'date',
    'time',
    'language',
    'eventType',
    'location',
    'docket',
    'judge',
    'defendants',
     'comments',
];
?>
<br>
<table style="margin-bottom:1em">
    <tbody>
    <?php $entity = $this->entity; foreach ($fields as $field):
        /** @todo  need to figure out what to do with this 'extraData'... */
        // if ($field == 'extraData') : continue; endif;
        // if ($field == 'end_time'): continue; endif;
        if ($field == 'comments' && !$this->with_comments) : continue; endif;
        if ($field == 'eventType' or $field == 'event_type') :
            $label = 'event type';
            if (!key_exists($field,$this->entity)) :
                $field = 'type';
            endif;
        else :
            $label = $field;
        endif;
    ?>
    <tr>
        <td style="border-bottom:1px dotted gray; vertical-align:top"><?php echo $label ?></td>
        <td style="border-bottom:1px dotted gray"><?php
           // the "escaped" flag means it is already string data/finished HTML
            if ($this->escaped): echo $this->entity[$field];
            elseif (is_string($this->entity[$field])):
                echo $this->escapeHtml($this->entity[$field]);
            else:
                $helper = new Diff();
                $data = $this->entity[$field];
                if ('defendants' == $field):
                    echo $helper->renderDefendants($data);
                elseif ('interpreters' == $field) :
                    echo $helper->renderInterpreters($data);
                elseif ($data instanceof \DateTime) :
                    echo $helper->renderDateTime($field, $data);
                else : throw new \RuntimeException(
                    sprintf("viewscript event-details cannot render entity field $field (type: %s)",
                    gettype($data)));
                endif;
            endif;
            ?></td>
    </tr>
<?php endforeach; ?>
    </tbody>
</table>
