<?php /* module/Admin/view/interpreters-office/admin/schedule/index.phtml */

$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
elseif ($messenger->hasErrorMessages()) :
    echo $messenger->render('danger', ['alert','alert-danger',], false);
endif;?>
<div class="row mb-0 mt-3 py-2">
    <div class="col-2 align-self-center pl-0 ml-0 text-left">
    <a role="button" class="btn btn-lg btn-primary py-1 fas fa-arrow-left" style="font-size:1.2rem;background-color:#74b4fb" href="<?php
        echo $this->url('events').$this->prev
    ?>"><span class="sr-only">previous</span></a>
    </div>
    <div class="col-8  text-center">
    <h2 class="navigation pt-1"><a href="/admin">admin</a> | schedule <small class="text-muted"><?php echo $this->date->format('D d M Y')?></small></h2>
    <!-- shit underneath -->
    </div>
    <div class="col-2 align-self-center pr-0 mr-0 text-right">
    <a role="button" class="btn btn-lg btn-primary py-1 fas fa-arrow-right" style="font-size:1.2rem;background-color:#74b4fb" href="<?php
        echo $this->url('events').$this->next
    ?>"><span class="sr-only">previous</span></a>
    </div>
    <?php if ($this->data) : ?>
<table class="table table-hover table-bordered table-sm rounded mt-2">
    <thead>
        <tr>
            <th>time</th>
            <th>type</th>
            <th>judge</th>
            <th>language</th>
            <th>docket</th>
            <th>defendants</th>
            <th>notes</th>
            <th>interpreters</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->data['events'] as $e):  // $e['location_type'] contains e.g., "jail"
        ?>
        <tr data-id="<?php echo $e['id']?>" class="event-category-<?php echo str_replace(' ','-',$e['category']) ?>">
            <td class="text-right text-nowrap"><?php echo $e['time']->format('g:i a')?></td>
            <td style="line-height:1.2em" title="event id <?php echo $e['id']?>" class="py-2"><a href="<?php
                echo $this->url('events/edit',['id'=>$e['id']])
            ?>"><?php echo $e['type']; ?></a><?php if ($e['location_type']=='jail'):
                    ?><br><span class="text-muted"><?php echo $e['location'];?></span><?php
                    endif;
            ?></td>
            <td class="text-nowrap"><?php echo $e['judge'];
                    if (($e['category']=="in" or 'magistrate'==$e['judge']) && $e['location']):
                    ?><br><span class="text-muted"><?php echo $e['location'];?></span><?php
                    endif;
            ?></td>
            <td><?php echo $e['language']?></td>
            <td class="text-nowrap"><?php echo substr($e['docket'],2)?></td>
            <td class="defendants text-nowrap"><?php echo $this->defendants($e['id'])?></td>
            <td style="line-height: 1.2em; font-size: 95%"><?php echo $e['comments']?></td>
            <td class="interpreters-assigned text-nowrap"><?php echo $this->interpreters($e['id'])?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot></tfoot>
</table>
    <?php
endif;
