<?php /* module/Admin/view/interpreters-office/admin/schedule/index.phtml */
$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
$this->headScript()->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'))
    ->appendFile($this->basePath('js/schedule.js'));
$this->headTitle($this->date->format('D d M Y'));
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
elseif ($messenger->hasErrorMessages()) :
    echo $messenger->render('danger', ['alert','alert-danger',], false);
endif;?>
<div class="row mb-0 mt-3 py-2">
    <div class="col-2 align-self-center text-left">
    <a role="button" title="go back one day" data-toggle="tooltip" class="btn btn-lg btn-primary py-1 fas fa-arrow-left" style="font-size:1.2rem;background-color:#74b4fb" href="<?php
        echo $this->url('events').$this->prev
    ?>"><span class="sr-only">previous</span></a>
    </div>
    <div class="col-8 text-center border rounded">
    <h2 class="navigation pt-1"><a href="/admin">admin</a> | schedule <small class="text-muted"><?php echo $this->date->format('D d M Y')?></small>
    </h2>
    </div>
    <div class="col-2 align-self-center text-right">
    <a role="button" title="go forward one day" data-toggle="tooltip" class="btn btn-lg btn-primary py-1 fas fa-arrow-right" style="font-size:1.2rem;background-color:#74b4fb" href="<?php
        echo $this->url('events').$this->next
    ?>"><span class="sr-only">previous</span></a>
    </div>
</div><!-- /row   -->
<!-- <div class="row"> -->
    <div class="offset-md-2 col-8 d-flex">
        <div class="form-inline mx-auto">
            <label for="language-select" class="text-md-right px-1">language</label>
            <select class="form-control form-control-sm custom-select" id="language-select" name="language">
                <option label="all" value="all">all</option>
                <option label="Spanish" <?php if ($this->language == 'spanish') :
?>selected="selected" <?php
                                        endif;?>value="spanish">Spanish</option>
                <option label="not Spanish" <?php if ($this->language == 'not-spanish') :
?>selected="selected" <?php
                                            endif;?>value="not-spanish">not Spanish</option>
            </select>
            <label for="date-input" class="text-md-right pl-2 pr-1">date</label>
            <input type="text" name="date" id="date-input" class="form-control  form-control-sm" style="max-width:125px">
        </div>
    </div>
<!-- </div> -->
<table id="schedule-table" class="table table-hover table-bordered table-sm rounded mt-2">
    <thead>
        <tr>
            <th>time</th>
            <th>type</th>
            <th>judge</th>
            <th>language</th>
            <th>docket</th>
            <th>defendants</th>
            <th>notes</th>
            <th>interpreters</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($this->data) :
            foreach ($this->data['events'] as $e) :
                $view_url = $this->url('events/view', ['id' => $e['id']]);
                if (stristr($e['judge'], 'magistrate') !== false && ! $e['location']) :
                    $magistrate_default = $e['aj_default_location'];
                endif;
        ?>
        <tr data-id="<?php echo $e['id']?>" class="event-category-<?php echo str_replace(' ', '-', $e['category']) ?><?php
        if ($e['cancellation']) :
            echo " event-cancelled" ;
        endif;?>">
            <td class="text-right text-nowrap"><?php echo $e['time']->format('g:i a')?></td>
            <td style="line-height:1.2em" class="py-2"><a href="<?php echo $view_url ?>"><span class="float-right align-self-top fas fa-cog text-primary"></span>
                <?php echo $e['type']; ?><?php
                if ($e['location_type'] == 'jail') :
                    ?><br><span class="text-muted"><?php echo $e['location'];?></span><?php
                endif;
            ?></a></td>
            <td class="text-nowrap"><?php echo $e['judge'];
            if (($e['category'] == "in" or 'magistrate' == $e['judge'])) :
            ?><br><span class="text-muted"><?php echo $e['location'] ?: $e['aj_default_location'];?></span><?php
            endif;
            ?></td>
            <td><?php echo $e['language']?></td>
            <td class="text-nowrap"><?php echo substr($e['docket'], 2)?></td>
            <td class="defendants text-nowrap"><?php echo $this->defendants($e['id'])?></td>
            <td style="line-height: 1.2em; font-size: 95%"><?php echo $e['comments']?></td>
            <td class="interpreters-assigned text-nowrap"><?php echo $this->interpreters($e['id'])?></td>
        </tr>
            <?php endforeach;
        else :
    ?><tr><td colspan="8" class="text-center py-4 px-4 no-events">
        <div class="alert alert-info mx-auto">no events scheduled for this date and language.</div>
    </td></tr><?php
        endif;?>
    </tbody>
    <tfoot></tfoot>
</table>
