<?php /* module/Admin/view/interpreters-office/admin/schedule/index.phtml */

$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) : 
    echo $messenger->render('success', ['alert','alert-success',], false); 
elseif ($messenger->hasErrorMessages()) : 
    echo $messenger->render('danger', ['alert','alert-danger',], false); 
endif;?>
<h2 class="navigation mb-3 mt-4"><?php echo $this->navigation('default')->breadcrumbs() ?></h2>
<pre><?php print_r($this->defts) ?></pre>
<?php
if ($this->data) :    
    ?>
<table class="table table-hover table-bordered table-sm">
    <thead>
        <tr>
            <th>time</th>
            <th>type</th>
            <th>judge</th>
            <th>language</th>
            <th>docket</th>
            <th>defendants</th>
            <th>notes</th>
            <th>interpreters</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->data as $e): 
           if ($e['category'] == 'not applicable') : 
               $e['category'] = 'not-applicable';
            endif;
        ?>
        <tr class="type-<?php echo $e['category'] ?>">
            <td><?php echo $e['time']->format('h:i a')?></td>
            <td><?php echo $e['type']?></td>
            <td><?php echo $e['judge']?></td>
            <td><?php echo $e['language']?></td>
            <td><?php echo substr($e['docket'],2)?></td>
            <td class="defendants">...</td>
            <td><?php echo $e['comments']?></td>
            <td class="interpreters-assigned">...</td>
        </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot></tfoot>
</table>
    <?php    
endif;