<?php /** module/Admin/view/interpreters-office/admin/schedule/view.phtml  */
/**
 *
 * @var \InterpretersOffice\Entity\Event $event
 */
$event = $this->event;
$this->headTitle('event details');
// figure out location
$IN_COURT =  $event['category'] == 'in';
if ($event['location']):
// etc <?php echo $event['default_courtroom']
endif;
?>
<h2 class="navigation pt-1 mx-auto my-4 text-center"><a href="/admin">admin</a> | <a href="/admin/schedule">schedule</a> <small class="text-muted">event details</small></h2>

<div class="row border mx-auto no-gutters py-2 pl-1" style="max-width:820px">
    <div class="col-2 text-right text-muted pr-2">
        date
    </div>
    <div class="col-4">
        <?php echo $event['date']->format('D d-M-Y'); ?>
        <!-- echo $event['time'] ? $event['time']->format('h:i a'): '<em>none set</em>'-->
    </div>
    <div class="col-2 text-right text-muted pr-2">
        type
    </div>
    <div class="col-4">
        <?php echo $event['type'] ?>
    </div>
    <div class="col-2 text-right text-muted pr-2">
        time
    </div>
    <div class="col-4">
        <?php echo $event['time'] ? $event['time']->format('h:i a'): '<em>?</em>' ?>
    </div>
    <div class="col-2 text-right text-muted pr-2">
        language
    </div>
    <div class="col-4">
        <?php echo $event['language']?>
    </div>
    <div class="col-2 text-right text-muted pr-2">
        judge
    </div>
    <div class="col-4">
        <?php echo $event['judge'] ?>
    </div>
    <div class="col-2 text-right text-muted pr-2">
        location
    </div>
    <div class="col-4">
        <?php echo "boink" ?>
    </div><?php echo $event['default_courtroom'] ?>
    <div class="col-2 text-right text-muted pr-2">
        defendants
    </div>
    <div class="col-4"><?php
        foreach($event['defendants'] as $d) :
            echo "$d[surnames], $d[given_names]<br>";
        endforeach;?>
    </div>
    <div class="col-2 text-right text-muted pr-2">
        docket
    </div>
    <div class="col-4">
        <?php echo $event['docket']?>
    </div>

</div>
