<?php /** module/Admin/view/interpreters-office/admin/schedule/view.phtml  */
/**
 *
 * @var \InterpretersOffice\Entity\Event $event
 */
$event = $this->event;
$this->headTitle('event details');
// figure out location
if ($event['location']):
    $IS_DEFAULT_LOCATION = false;
    $location = $event['location'];
    if ($event['parent_location']) :
        $location .= ', '.$event['parent_location'];
    endif;

elseif ($event['category'] == 'in' && $event['default_courtroom']):
    // fall back on judge default
    $IS_DEFAULT_LOCATION = true;
    $location = $event['default_courtroom'];
    if ($event['default_courthouse']):
        $location .= ', '.$event['default_courthouse'];
    endif;
    $location .= ' <span class="text-muted text-md-right">*</span>';
else:
    $location = '';
endif;
?>
<h2 class="navigation pt-1 mx-auto my-4 text-center"><a href="/admin">admin</a> | <a href="/admin/schedule">schedule</a> <small class="text-muted text-md-right">event details</small></h2>

<div class="row border event-details mx-auto" style="max-width:850px">
    <div class="col-sm-2 text-muted text-md-right">
        date
    </div>
    <div class="col-sm-4">
        <?php echo $event['date']->format('D d-M-Y'); ?>
    </div>
    <div class="col-sm-2 text-muted text-md-right">
        time
    </div>
    <div class="col-sm-4">
        <?php echo $event['time'] ? $event['time']->format('g:i a'): '<em>?</em>' ?>
    </div>
    <div class="col-sm-2 text-muted text-md-right">
        type
    </div>
    <div class="col-sm-4">
        <?php echo $event['type'] ?>
    </div>
    <div class="col-sm-2 text-muted text-md-right">
        language
    </div>
    <div class="col-sm-4">
        <?php echo $event['language']?>
    </div>
    <div class="col-sm-2 text-muted text-md-right">
        judge
    </div>
    <div class="col-sm-4">
        <?php echo $event['judge'];
        if ($event['aj_default_location']):
            ?> <span class="text-muted"><?php echo $event['aj_default_location']?></span><?php
        endif; ?>
    </div>
    <div class="col-sm-2  text-muted text-md-right">
        location
    </div>
    <div class="col-sm-4">
        <?php echo $location ?>
    </div>
    <div class="col-sm-2 text-muted text-md-right">
        defendants
    </div>
    <div class="col-sm-4"><?php
    foreach($event['defendants'] as $d) :
        echo "$d[surnames], $d[given_names]<br>";
    endforeach;?>
    </div>
    <div class="col-sm-2  text-muted text-md-right">
        docket
    </div>
    <div class="col-sm-4">
        <?php echo $event['docket']?>
    </div>
    <div class="col-sm-2  text-muted text-md-right">
        interpreters
    </div>
    <div class="col-sm-4"><?php
    foreach ($event['interpreters'] as $i):
        echo "$i[lastname], $i[firstname]<br>";
    endforeach;
    ?>
    </div>
    <div class="col-sm-2  text-muted text-md-right">
        cancellation
    </div>
    <div class="col-sm-4">
        <?php echo $event['reason_for_cancellation'] ?: '<span class="text-muted">n/a</span>'?>
    </div>
        <div class="col-sm-2  text-muted text-md-right">
        submitted by
    </div>
    <div class="col-sm-4"><span class="avoidwrap">
        <?php echo $event['submitter'] ;
        ?><?php
        if ($event['submitter_hat']):?>,</span> <span class="avoidwrap"><?php
            echo "{$event['submitter_hat']}";
        endif;?></span>
    </div>
    <div class="col-sm-2 text-muted text-md-right">
        submitted on
    </div>
    <div class="col-sm-4">
    <?php echo $event['submission_date']->format('d-M-Y');
        if ($event['submission_time']):
            echo $event['submission_time']->format(' g:i a');
        endif;
    ?>
    </div>
    <div class="col-sm-2 text-muted text-md-right">
        created
    </div>
    <div class="col-sm-4">
        <?php echo $event['created']->format('d-M-Y g:i a'), " ({$event['created_by']})"; ?>
    </div>
    <div class="col-sm-2 text-muted text-md-right">
        last updated
    </div>
    <div class="col-sm-4">
        <?php echo $event['created']==$event['last_updated'] ? '<span class="text-muted">n/a</span>' :
            $event['last_updated']->format('d-M-Y g:i a'), " ({$event['last_updated_by']})";
        ?>
    </div>
    <div class="col-sm-2 text-muted text-md-right">
        comments (public)
    </div>
    <div class="col-sm-10">
        <?php echo $this->escapeHtml($event['comments']) ?>
    </div>
    <div class="col-sm-2 text-muted text-md-right">
        comments (internal)
    </div>
    <div class="col-sm-10">
        <?php echo $this->escapeHtml($event['admin_comments']) ?>
    </div>
    <div class="col-12 d-flex">
        <div class="btn-group mx-auto" role="group" aria-label="available actions">
          <button type="button" class="btn btn-info">edit</button>
          <button type="button" class="btn btn-info">repeat</button>
          <button type="button" class="btn btn-info">delete</button>
        </div>
    </div>
</div>
<!-- -->

<!-- -->
<pre><?php //print_r(array_keys($event))?></pre>
