<?php if ($this->data !== false):
    $what = 'annotation';
    $count = count($this->data);
    if (! $count) :
        echo "no ${$what}s found";
    else:
        if ($count > 1 ): $what .= 's'; endif;
        echo "$count $what found";
    endif;
else: $count = false; $this->data = []; endif?>
<table class="table" <?php if (!$count):?>hidden<?php endif?>>
    <thead class="text-info">
        <th class="font-weight-normal">priority</th>
        <th class="font-weight-normal">comment</th>
        <th class="font-weight-normal">meta</th>
        <th></th>
    </thead>
    <tbody>
        <?php foreach($this->data as $note): $obj = $note[0]?>
            <tr>
                <td><?= $obj->getPriority()?></td>
                <td><?= $obj->getComment()?></td>
                <td><?= "created {$obj->getCreated()->format('d-M-Y g:ia')} by {$note['created_by']}"?><?php
                    if ($note['modified_by']):
                    ?><br><?= "updated {$obj->getModified()->format('d-M-Y g:ia')} by {$note['modified_by']}"?><?php
                    endif;
                ?></td>
                <td class="avoidwrap"><a title= "update this annotation" href="<?=$this->url('admin/docket-annotations/edit',['docket'=>$this->docket,'action'=>'edit','id'=>$obj->getId()])?>">
                        <span class="fas fa-edit"></span><span class="sr-only">edit</span>
                    </a>
                    <a title="delete this annotation" href="<?=$this->url('admin/docket-annotations/edit',['docket'=>$this->docket,'action'=>'delete','id'=>$obj->getId()])?>">
                        <span class="fas fa-trash text-muted"></span><span class="sr-only">delete</span>
                    </a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
