<?php /** module/Admin/config/template_map.php */
return [
    'interpreters-office/admin/schedule/schedule' => __DIR__ . '/../view/schedule/schedule.phtml',
    'interpreters-office/admin/schedule/view' => __DIR__ . '/../view/schedule/view.phtml',
    'interpreters-office/admin/schedule/partials/table' => __DIR__ . '/../view/schedule/partials/table.phtml',
    'interpreters-office/admin/people/index' => __DIR__ . '/../view/people/index.phtml',
    // 'interpreters-office/admin/people/index' => __DIR__ . '/../view/people/vue.phtml',
    'interpreters-office/admin/people/edit' => __DIR__ . '/../view/people/form.phtml',
    'interpreters-office/admin/people/add' => __DIR__ . '/../view/people/form.phtml',
    'interpreters-office/admin/people/view' => __DIR__ . '/../view/people/view.phtml',
    'interpreters-office/admin/languages/index' => __DIR__ . '/../view/languages/index.phtml',
    'interpreters-office/admin/languages/add' => __DIR__ . '/../view/languages/form.phtml',
    'interpreters-office/admin/languages/edit' => __DIR__ . '/../view/languages/form.phtml',
    'interpreters-office/admin/interpreters/index' => __DIR__ . '/../view/interpreters/index.phtml',
    'modal-login' => __DIR__ . '/../view/interpreters/modal-login.phtml',
    'interpreters-office/admin/interpreters-write/add' => __DIR__ . '/../view/interpreters/form.phtml',
    'interpreters-office/admin/interpreters-write/edit' => __DIR__ . '/../view/interpreters/form.phtml',
    'interpreters-office/admin/interpreters/view' => __DIR__ . '/../view/interpreters/view.phtml',
    'interpreters-office/admin/index/index' => __DIR__ . '/../view/index/index.phtml',
    'interpreters-office/admin/interpreters/availability-list'=>  __DIR__ . '/../view/interpreters/availability-list.phtml',
    'interpreters-office/admin/court-closings/test' => __DIR__ . '/../view/court-closings/test.phtml',
    'interpreters-office/admin/court-closings/index' => __DIR__ . '/../view/court-closings/index.phtml',
    //'interpreters-office/admin/court-closings/would-be.form' => __DIR__ . '/../view/court-closings/would-be.form.phtml',
    'interpreters-office/admin/court-closings/add' => __DIR__ . '/../view/court-closings/form.phtml',
    'interpreters-office/admin/court-closings/edit' => __DIR__ . '/../view/court-closings/form.phtml',
    'interpreters-office/admin/users/index' => __DIR__ . '/../view/users/index.phtml',
    'interpreters-office/admin/users/form' => __DIR__ . '/../view/users/form.phtml',
    'interpreters-office/admin/users/add' => __DIR__ . '/../view/users/form.phtml',
    'interpreters-office/admin/users/edit' => __DIR__ . '/../view/users/form.phtml',
    'interpreters-office/admin/users/view' => __DIR__ . '/../view/users/view.phtml',
    'interpreters-office/admin/locations/index' => __DIR__ . '/../view/locations/index.phtml',
    'interpreters-office/admin/locations/add' => __DIR__ . '/../view/locations/form.phtml',
    'interpreters-office/admin/locations/edit' => __DIR__ . '/../view/locations/form.phtml',
    'interpreters-office/admin/judges/index' => __DIR__ . '/../view/judges/index.phtml',
    'interpreters-office/admin/judges/add' => __DIR__ . '/../view/judges/form.phtml',
    'interpreters-office/admin/judges/edit' => __DIR__ . '/../view/judges/form.phtml',
    'interpreters-office/admin/judges/view' => __DIR__ . '/../view/judges/view.phtml',
    'interpreters-office/admin/defendants/index' => __DIR__ . '/../view/defendants/index.phtml',
    'interpreters-office/admin/defendants/edit' => __DIR__ . '/../view/defendants/form.phtml',
    'interpreters-office/admin/defendants/add' => __DIR__ . '/../view/defendants/form.phtml',
    'interpreters-office/admin/events/index' => __DIR__ . '/../view/events/index.phtml',
    'interpreters-office/admin/events/edit' => __DIR__ . '/../view/events/form.phtml',
    'interpreters-office/admin/events/add' => __DIR__ . '/../view/events/form.phtml',
    'interpreters-office/admin/event-types/index' => __DIR__ . '/../view/event-types/index.phtml',
    'interpreters-office/admin/event-types/add' => __DIR__ . '/../view/event-types/form.phtml',
    'interpreters-office/admin/event-types/edit' => __DIR__ . '/../view/event-types/form.phtml',
    'interpreters-office/admin/normalization/index' => __DIR__ . '/../view/normalization/index.phtml',
    'interpreters-office/admin/search/search' => __DIR__ . '/../view/search/search.phtml',
    'interpreters-office/admin/search/docket-search' => __DIR__ . '/../view/search/docket-search.phtml',
    'interpreters-office/admin/email/index' => __DIR__ . '/../view/email/index.phtml',
    'interpreters-office/admin/email/form' => __DIR__ . '/../view/email/form.phtml',
    // this one's a bit weird...
    'interpreters-office/admin/email/templates' => __DIR__ . '/../../InterpretersOffice/view/interpreters-office/email/templates.phtml',

    'interpreters-office/admin/config/index' => __DIR__ . '/../view/configuration/index.phtml',
    'interpreters-office/admin/config/forms' => __DIR__ . '/../view/configuration/forms.phtml',

    'interpreters-office/admin/docket-annotations/index' => __DIR__ . '/../view/docket-annotations/index.phtml',
    'interpreters-office/admin/docket-annotations/add' => __DIR__ . '/../view/docket-annotations/form.phtml',
    'interpreters-office/admin/docket-annotations/edit' => __DIR__ . '/../view/docket-annotations/form.phtml',
    'interpreters-office/admin/index/support' => __DIR__ . '/../view/support/index.phtml',
    'interpreters-office/admin/reports/index' => __DIR__ . '/../view/reports/index.phtml',

   


];
