<?php
return [
'interpreters-office/admin/schedule/schedule' => __DIR__ . '/../view/schedule/schedule.phtml',
'interpreters-office/admin/schedule/view' => __DIR__ . '/../view/schedule/view.phtml',
'interpreters-office/admin/schedule/partials/table' => __DIR__ . '/../view/schedule/partials/table.phtml',
'interpreters-office/admin/people/vue' => __DIR__ . '/../view/people/vue.phtml',
'interpreters-office/admin/people/index' => __DIR__ . '/../view/people/index.phtml',
'interpreters-office/admin/people/form' => __DIR__ . '/../view/people/form.phtml',
'interpreters-office/admin/languages/index' => __DIR__ . '/../view/languages/index.phtml',
'interpreters-office/admin/languages/form' => __DIR__ . '/../view/languages/form.phtml',
'interpreters-office/admin/interpreters/index' => __DIR__ . '/../view/interpreters/index.phtml',
//'interpreters-office/admin/interpreters/modal-login' => __DIR__ . '/../view/interpreters/modal-login.phtml',
'modal-login' => __DIR__ . '/../view/interpreters/modal-login.phtml',
'interpreters-office/admin/interpreters-write/add' => __DIR__ . '/../view/interpreters/form.phtml',
'interpreters-office/admin/interpreters-write/edit' => __DIR__ . '/../view/interpreters/form.phtml',
'interpreters-office/admin/interpreters/view' => __DIR__ . '/../view/interpreters/view.phtml',
'interpreters-office/admin/index/index' => __DIR__ . '/../view/index/index.phtml',
'interpreters-office/admin/court-closings/test' => __DIR__ . '/../view/court-closings/test.phtml',
'interpreters-office/admin/court-closings/index' => __DIR__ . '/../view/court-closings/index.phtml',
'interpreters-office/admin/court-closings/would-be.form' => __DIR__ . '/../view/court-closings/would-be.form.phtml',
'interpreters-office/admin/court-closings/form' => __DIR__ . '/../view/court-closings/form.phtml',
'interpreters-office/admin/users/index' => __DIR__ . '/../view/users/index.phtml',
'interpreters-office/admin/users/form' => __DIR__ . '/../view/users/form.phtml',
'interpreters-office/admin/locations/index' => __DIR__ . '/../view/locations/index.phtml',
'interpreters-office/admin/locations/form' => __DIR__ . '/../view/locations/form.phtml',
'interpreters-office/admin/judges/index' => __DIR__ . '/../view/judges/index.phtml',
'interpreters-office/admin/judges/add' => __DIR__ . '/../view/judges/form.phtml',
'interpreters-office/admin/judges/edit' => __DIR__ . '/../view/judges/form.phtml',
'interpreters-office/admin/defendants/index' => __DIR__ . '/../view/defendants/index.phtml',
'interpreters-office/admin/defendants/form' => __DIR__ . '/../view/defendants/form.phtml',
'interpreters-office/admin/events/index' => __DIR__ . '/../view/events/index.phtml',
'interpreters-office/admin/events/form' => __DIR__ . '/../view/events/form.phtml',
'interpreters-office/admin/event-types/index' => __DIR__ . '/../view/event-types/index.phtml',
'interpreters-office/admin/event-types/form' => __DIR__ . '/../view/event-types/form.phtml',
];
