<?php
/**
 * module/Admin/view/interpreters-office/admin/languages/index.phtml
 * view script for languages admin main page
 */
$this->headTitle($this->title);
?>
<h2>languages</h2>
<?php
$messenger = $this->flashMessenger();
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success',], false);
endif;

if (! $this->languages) :
?><div class="alert alert-warning">There are no languages in your database. 
    Go to <a href="/admin/languages/add">add</a> to start adding them.</div><?php
    return;
endif;

echo $this->paginationControl($this->languages, null, 'partials/pagination_head');
?>

<table class="table table-hover table-bordered" style="max-width:700px">
    <!-- <tr><th></th></tr> -->
    <tbody>
        <?php
        foreach ($this->languages as $language) :
            ?><tr><td><?php echo $this->escapeHtml($language[0]) ?> 
       (<?php printf('%d interpreters, %d events',$language['interpreters'],$language['events']); ?>)</td></tr>
       <?php endforeach;
       ?>
    </tbody>
</table>

<?php echo $this->paginationControl(
    $this->languages,
    'sliding',
    'partials/pagination_control',
    ['route' => 'languages']
);?>
<a href="<?php echo $this->url('languages/add') ?>" role="button" title="add a new language" id="btn-add-language" class="btn btn-info">
<span aria-hidden="true" class="icon glyphicon glyphicon-plus"></span> new language 
</a>
