<?php
/**
 * module/Admin/view/interpreters-office/admin/languages/index.phtml
 * view script for languages admin main page
 */
$this->headTitle($this->title);
?>
<div class="center-block mx-auto" style="max-width: 500px">
<h2 class="navigation mb-3 mt-4"><?php echo $this->navigation('Zend\Navigation\Admin_Breadcrumbs')->breadcrumbs() ?></h2>
<?php
$messenger = $this->flashMessenger();
foreach (['success','warning'] as $ns) :
    $method = 'has'.ucfirst($ns).'Messages';
    if ($messenger->$method()) :
        echo $messenger->render($ns, ['alert',"alert-$ns",], false);
    endif;
endforeach;


if (! $this->languages) :
?><div class="alert alert-warning">There are no languages in your database.
    Go to <a href="/admin/languages/add">add</a> to start adding them.</div><?php
    return;
endif;
echo $this->paginationControl($this->languages, null, 'partials/pagination_head');
?>
<table class="table table-hover table-bordered table-sm">
    <thead>
    <tr><th class="col-sm-8">language</th><th class="col-sm-2">interpreters</th><th class="col-sm-2 text-center">events</th></tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->languages as $language) :
            $entity = $language[0];
            ?><tr>
                <td><a href="<?php echo $this->url('languages/edit', ['id' => $entity->getId()]) ?>"><?php echo $this->escapeHtml($entity) ?></a>
                </td>
                <td class="text-right"><?php echo $language['interpreters'] ?></td>
                <td class="text-right"><?php echo $language['events'] ?></td>
            </tr>
        <?php endforeach;
        ?>
    </tbody>
</table>

<?php echo $this->paginationControl(
    $this->languages,
    'sliding',
    'partials/pagination_control',
    ['route' => 'languages']
);?>
<a href="<?php echo $this->url('languages/add') ?>" role="button" title="add a new language" id="btn-add-language" class="btn btn-info mt-1">
<span aria-hidden="true" class="fas fa-plus"></span> new language
</a>
</div>
