<?php
    $this->headTitle('requests | '.$this->layout()->action);
    $this->headLink()
            ->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
    $this->headScript()
            ->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.js'))
            ->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
            ->appendFile($this->basePath('js/form-utilities.js'))
            ->appendFile($this->basePath('js/requests/form.js'));

    $messenger = $this->flashMessenger();
    if ($messenger->hasErrorMessages()) :
        echo $messenger->render('error', ['alert','alert-warning',], false);
    endif;

    if ($this->errorMessage) : ?>
    <div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
    <?php
    return;
    endif;

    $form = $this->form;
    $action = $this->basePath('requests/'.$this->layout()->action);
    if ($this->id) {  $action .= "/$id"; }
    $form->setAttribute('action',$action);
    $form->prepare();
    $fieldset = $this->form->get('request');
    //<div class="d-flex justify-content-center">
    ?>
    <div class="center-block mx-auto" style="max-width:800px">
    <h2 class="navigation mb-3"><?php echo $this->navigation('Zend\Navigation\RequestsBreadcrumbs')->breadcrumbs() ?></h2>
<?php  echo  $this->form()->openTag($form);  ?>
<div class="form-group form-row">
    <label for="date" class="col-form-label col-sm-3 pr-1">date</label>
    <div class="col-sm-3"><?php echo $this->formElement($fieldset->get('date')),
        $this->formElementErrors($fieldset->get('date'));?>
    </div>
    <label for="time" class="col-form-label col-sm-1">time</label>
    <div class="col-sm-3"><?php echo $this->formElement($fieldset->get('time')),
        $this->formElementErrors($fieldset->get('time'));?>
    </div>
</div>
<?php
    foreach (['language','judge','eventType','location','docket'] as $name) :
        $element = $fieldset->get($name);
?>
<div class="form-group form-row">
    <label for="<?php echo $element->getAttribute('id')?>" class="col-sm-3 col-form-label pr-1">
        <?php echo $element->getLabel()?></label>
    <div class="col-sm-7"><?php echo $this->formElement($element),
        $this->formElementErrors($element);?></div>
</div>
<?php endforeach ?>
<div class="form-group form-row">
    <label for="defendant-search" class="col-form-label col-sm-3 pr-1">defendant(s)</label>
    <div class="col-sm-7">
        <div class="input-group">
            <div class="input-group-prepend">
                <span title="get help" class="input-group-text fas fa-question pt-2 text-warning bg-info"></span>
            </div>
            <?php echo $this->formElement($fieldset->get('defendant-search'))?>
            <div class="input-group-append">
                <span title="add name" class="input-group-text fas fa-plus pt-2 bg-primary text-white"></span>
            </div>
        </div>
        <ul id="defendants" class="list-group mt-2"></ul>
    </div>
</div>
<div class="form-group form-row">
    <label for="comments" class="col-form-label col-sm-3 pr-1">notes</label>
    <div class="col-sm-7"><?php echo $this->formElement($fieldset->get('comments')),
        $this->formElementErrors($fieldset->get('comments'));?>
    </div>
</div>
<div class="form-group form-row">
    <div class="col-sm-7 offset-sm-3">
        <?php echo $this->formElement($fieldset->get('id')),
         $this->formElement($form->get('csrf')),
          $this->formElementErrors($form->get('csrf'))?>
        <button type="submit" class="btn btn-success">save</button>
    </div>
</div>
    </form>

        <pre class=border><?php //var_dump($this->debug_data)?></pre>

</div>
<!--
    <pre><?php //print_r(get_class_methods($fieldset))
        foreach ($fieldset->getElements() as $e) {
            //printf("%s<br>",gettype($e));//->getName());
            if (is_object($e)) {
                printf("%s<br>",$e->getName());
            } else {
                //print_r(array_keys($e));
                //printf("%s<br>",$e['name']);
            }
        }

        //echo $_SERVER['REQUEST_URI']
    ?></pre>
-->
