<?php     $this->headTitle('requests | '.$this->layout()->action);
$r = $this->data;
?>
<h2 class="text-center py-2 navigation"><?php echo $this->navigation('Zend\Navigation\RequestsBreadcrumbs')->breadcrumbs() ?></h2>

    <div class="row mx-auto" style="max-width:825px">
    <div class="col-md-2 text-muted text-md-right pr-1">date</div><div class="col-md-4"><?php echo $r['date']->format('D d-M-Y') ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">time</div><div class="col-md-4"><?php echo $r['date']->format('g:i a') ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">judge</div><div class="col-md-4"><?php if ($r['judge_lastname']):
        echo "{$r['judge_firstname']} {$r['judge_middlename']} {$r['judge_lastname']}, {$r['judge_flavor']}"; endif; ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">place</div><div class="col-md-4"><?php echo $r['location'] ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">type</div><div class="col-md-4"><?php echo $r['type'] ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">language</div><div class="col-md-4"><?php echo $r['language'] ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">defendants</div><div class="col-md-4"><?php
        if ($r['defendants']):
            foreach ($r['defendants']  as $d):
                echo $this->escapeHtml("{$d['surnames']}, {$d['given_names']}"),'<br>';
            endforeach;
        endif;
    ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">docket</div><div class="col-md-4"><?php echo $r['docket'] ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">comments</div><div class="col-md-10"><?php echo $r['comments'] ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">submitted</div><div class="col-md-10"><?php
        echo "{$r['created']->format('d-M-Y g:i a')}  by {$r['submitter_firstname']} {$r['submitter_lastname']}, {$r['submitter_hat']}";
    ?></div>
    <div class="col-md-2 text-muted text-md-right pr-1">updated</div><div class="col-md-10"><?php
        if ($r['created'] != $r['modified']):
            echo "{$r['modified']->format('d-M-Y g:i a')}  by {$r['modified_by_firstname']} {$r['modified_by_lastname']}, {$r['modified_by_hat']}";
        else: ?>(n/a)<?php
        endif;
    ?></div>
</div>
<?php
/*

    [location] =>
    [parent_location] =>
    [event_id] => 115056
    [pending] =>
    [event_date] => DateTime Object
        (
            [date] => 2018-12-19 00:00:00.000000
            [timezone_type] => 3
            [timezone] => America/New_York
        )

    [event_time] => DateTime Object
        (
            [date] => 1970-01-01 13:00:00.000000
            [timezone_type] => 3
            [timezone] => America/New_York
        )

    [defendants] => Array
        (
            [0] => Array
                (
                    [surnames] => López Guerzon
                    [given_names] => Erick Gastón
                )

        )
 */
?>
<script>
if (document.referrer.indexOf("/requests/list") !== -1) {
    document.querySelector("h2.navigation a").href = document.referrer;
}
</script>
