<?php
/**
 *  module/Admin/view/interpreters-office/admin/people/form.phtml
 *  view script for rendering people create|update form
 */
$this->headTitle($this->title);
$this->headScript()->appendFile($this->basePath('/js/people-form.js'));
if ($this->errorMessage) : ?>
<div class="alert alert-danger"><?php echo $this->errorMessage ?></div>
    <?php
    return;
endif;
$formAction = $this->layout()->action == 'add' ? $this->url('people/add')
    : $this->url('people/edit', ['id' => $this->id ]);
$form = $this->form;
$form->add([
    'name' => 'submit',
    'type' => 'Zend\Form\Element\Submit',
     'attributes' => ['value' => 'save','class' => 'btn btn-success btn-lg'],
])->setAttribute('method', 'post')->setAttribute('action', $formAction)
    ->setAttribute('class', 'form-horizontal')    ;
?>
<div class="center-block" style="max-width:750px"><!-- wrapper -->
<h2 class="text-center"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
<?php if ($this->layout()->action == 'add'):?>
<div class="row">
    <p class="col-sm-9 offset-sm-3 form-text">
        This form is for managing "generic" people who contact your office. For interpreters and for judges, please use the respective <a href="<?php echo $this->url('interpreters') ?>">interpreter</a>
        or <a href="<?php echo $this->url('judges') ?>">judge</a> management pages, and <a href="<?php echo $this->url('users') ?>">user administration</a> for managing user accounts.
    </p>
</div>
<?php
endif;
$form->prepare();
$fieldset = $form->get('person');
echo $this->form()->openTag($form);?>
<div class="form-group">
<?php
$hat = $fieldset->get('hat');
if ($this->has_related_entities) :
    $hat->setAttribute("disabled", "disabled");
endif;
?>
    <div class="form-group form-row">
        <label class="col-form-label col-sm-3"><?php echo $hat->getLabel()?></label>
        <div class="col-sm-9"><?php echo $this->formSelect($hat),$this->formElementErrors($hat) ?>
        </div>
    </div>
</div>
<?php
 // text inputs
foreach (['lastname','middlename','firstname','email','office_phone','mobile_phone'] as $elementName) :
    $element = $fieldset->get($elementName);?>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3"><?php echo $element->getLabel()?></label>
    <div class="col-sm-9"><?php echo $this->formText($element),$this->formElementErrors($element) ?>
    </div>
</div>
    <?php
endforeach;
$active = $fieldset->get('active');?>
<div class="form-group form-row">
    <label class="col-form-label col-sm-3"><?php echo $active->getLabel()?></label>
    <div class="col-sm-9" style="padding-top:.25em"><?php echo $this->formCheckbox($active),$this->formElementErrors($active) ?>
    </div>
 </div>
<div class="form-group form-row">
    <div class="offset-sm-3 col-sm-9">
    <?php
    $csrf = $form->get('csrf');
    echo $this->formHidden($csrf),$this->formElementErrors($csrf) ;
    echo $this->formHidden($fieldset->get('id'));
    echo $this->formSubmit($form->get('submit'));
    if ($this->has_related_entities == '0') :
        ?><input id="btn-delete" type="button" class="btn btn-lg btn-warning" title="delete this person from your database" value="delete" id="btn-delete"><?php
    endif;
    ?></div>
</div>
<?php echo $this->form()->closeTag(); ?>
</div><!-- /wrapper -->
