<?php
/** module/Admin/views/interpreters-office/admin/people/index.phtml
 *  viewscript for main people-administration page
 */
use Laminas\Form\Element;
if ($this->defaults):
    $defaults = array_merge([
        'active' => '','hat' => '', 'name' => '',
        'id' => '',],$this->defaults);
else:
    $defaults = [
        'active' => '',
        'hat' => '',
        'name' => '',
        'id' => '',
    ];
endif;

$hat_element = (new Element\Select(
    'hat',
    ['value_options' => $this->options,
            'empty_option' => ' -- select hat --',]
))->setAttributes(['class' => 'custom-select','id' => 'hat'])
    ->setValue($defaults['hat']);
$status_element = (new Element\Select(
    'active',
    ['value_options' => [1 => 'active',0 => 'inactive',],
    'empty_option' => ' any status ',]
))->setAttributes(['class' => 'custom-select','id' => 'active'])
->setValue($defaults['active']);
$this->headScript()
    //->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.js'))
    ->appendFile($this->basePath('js/people-index.js'));
    //$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui.min.css'));
$this->headTitle($this->title);
?>
<h2 class="text-center"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
<?php
$messenger = $this->flashMessenger()->setAutoEscape(false);
if ($messenger->hasSuccessMessages()) :
    echo $messenger->render('success', ['alert','alert-success','flash-message']);
endif;
?>
<form id="search-form" class="form-inline shadow-sm border rounded pl-3 py-3 mx-auto mt-4" style="max-width:850px">
    <label class="my-1 mr-2" for="hat">hat</label>
    <?php echo $this->formElement($hat_element); ?>
    <label class="my-1 mx-2" for="status">status</label>
    <?php echo $this->formElement($status_element); ?>
    <label class="my-1 mx-2" for="name">name</label>
    <input type="text" id="name" name="name" class="form-control" value="<?php echo $this->escapeHtml($defaults['name'])?>" placeholder="last name[, first ]">
    <button type="submit" id="btn-search" class="btn btn-primary my-1 ml-1 "><span class="icon fa fa-search"></span> search</button>
</form>
<div id="results" class="mx-auto results" style="max-width:650px">
    <?php if ($this->paginator): echo $this->render('people/results'); endif;?>
</div>
