<?php /** module/Admin/view/people/view.phtml */ ?>
<div class="mx-auto px-2 pt-2" style="max-width:800px">
<h2><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
<?php if (!$this->entity): ?>
    <div class="alert alert-warning">
        No person with id <?php echo $this->id ?> found in the database.
    </div>
</div>
<?php return; endif;
    $person = $this->entity;
?>
    <div class="card mt-4">
        <div class="card-body">
            <h3 class="card-title">
            <?php
                echo $this->escapeHtml($person->getFullname().', '. $person->getHat());
            ?>
            </h3>
            <div class="row">
                <div class="col-sm-2 text-md-right">
                    phone
                </div>
                <div class="col-sm-9">
                    <?php echo $person->getOfficePhone()?: '-'?>
                </div>
                <div class="col-sm-2 text-md-right">
                    email
                </div>
                <div class="col-sm-9">
                    <?php echo $person->getEmail()?: '-'?>
                </div>
                <div class="col-sm-2 text-md-right">
                    active
                </div>
                <div class="col-sm-9">
                    <?php echo $person->getActive() ? 'yes' : 'no' ?>
                </div>
                <div class="offset-sm-2 pt-2">
                    <a role="button" class="btn btn-primary btn-sm" href="<?php
                    echo $this->url('people/edit',['id'=>$person->getId()])
                    ?>">edit</a>
                </div>
        </div>
    </div>
</div>
