<?php
/**
* just a view script for testing and experimenting with shit
* this one is intended for use with InterpretersOffice\Controller\IndexController::testAction()
*/
?>
<h1>another test</h1>
<p>a temporary view script for testing shit.</p>

<?php

$form->prepare();


$form->setAttribute('action', $this->url('application', ['action' => 'other-test']));
$form->add([
    'name' => 'submit',
    'type' => 'Laminas\Form\Element\Submit',
    'attributes' => ['value' => 'submit'],
]);

//$form->setAttribute('method', 'post');

$fieldset = $form->get('person-fieldset');
// Render the opening tag
echo $this->form()->openTag($form);
?><div class="form-group"><?php
echo $this->formLabel($fieldset->get('lastname'));
echo $this->formElement($fieldset->get('lastname'));
?></div> 
<div class="form-group">
<?php
echo $this->formLabel($fieldset->get('firstname'));
echo $this->formElement($fieldset->get('firstname'));

?>      
</div>
<?php
//echo $this->formRow($fieldset->get('middlename')),"<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
shit?