<?php 
$this->headTitle('schedule');
$this->headScript()->appendFile($this->basePath('js/lib/jquery-ui/jquery-ui.min.js'))
->appendFile($this->basePath('js/lib/moment/min/moment.min.js'))
->appendFile($this->basePath('js/schedule.js'))
?>
<h3 class="text-center border rounded shadow-sm py-3"><?= $this->escapeHtml($this->layout()->organization_name) ?> <span class="text-muted d-none d-sm-inline">|</span> <?= $this->date->format('l F j, Y') ?></h3>
<div class="row">
<div class="col-2 align-self-center text-left">
        <a role="button" title="go back one day" data-toggle="tooltip" class="btn btn-lg btn-primary py-1 fas fa-arrow-left" 
        style="font-size:1.2rem;background-color:#74b4fb" href="<?= $this->url('schedule').$this->data['prev'] ?>"><span class="sr-only">previous</span></a>
        </div>
    <div class="col d-flex"><div class="form-inline mx-auto">
            <label for="language-select" class="text-md-right px-1">display</label>
            <select class="form-control form-control-sm custom-select" id="language-select" name="language">
                <option label="all" value="all">all languages</option>
                <option label="Spanish" <?php if ($this->language == 'spanish') :
                    ?>selected="selected" <?php
                    endif;?>value="spanish">Spanish</option>
                <option label="not Spanish" <?php if ($this->language == 'non-spanish') :
                    ?>selected="selected" <?php
                    endif;?>value="non-spanish">not Spanish</option>
            </select>
            <label for="date-input" class="text-md-right pl-2 pr-1">for</label>
            <input data-date="<?=$this->date->format('Y-m-d')?>"  type="text" name="date" placeholder="date to display" id="date-input" class="form-control  form-control-sm" style="max-width:125px">
            <?php $today = date('Y/m/d'); if ($this->date->format('Y/m/d') != $today): ?><a title="today's schedule" class="btn btn-sm btn-outline-primary" role="button" href="<?php
                 echo $this->url('schedule').(new DateTime())->format('/Y/m/d')?>">today</a><?php endif ?>            
    </div></div>
    <div class="col-sm-2">
        <div class="float-right"><a role="button" data-toggle="tooltip" class="btn btn-lg btn-primary py-1 fas fa-arrow-right" 
            style="font-size:1.2rem;background-color:#74b4fb" href="<?= $this->url('schedule').$this->data['next'] ?>"  title="go forward one day"><span class="sr-only">next</span></a>
        </div>        
    </div>
</div>

<p></p>
<p>
</p>
<div id="schedule">
    <?php echo $this->partial('partials/schedule-table',['data'=>$this->data]) ;?>
</div>


