<?php 
/** 
* just a view script for testing and experimenting with shit 
* this one is intended for use with InterpretersOffice\Controller\IndexController::testAction()
*/
?>
<h1>add a language</h1>
<p>a temporary view script for testing shit.</p>

<?php 
$form->prepare();


$form->setAttribute('action', $this->url('application',['action'=>'test']));
$form->add([
	'name'=>'submit',
	'type'=>'Zend\Form\Element\Submit',
	'attributes' => ['value'=>'submit'],
]);

$form->setAttribute('method', 'post');

//$fieldset = $form->get('person');
// Render the opening tag
echo $this->form()->openTag($form);
echo $this->formRow($form->get('lastname')),"<br>";
echo $this->formRow($form->get('firstname')),"<br>";
echo $this->formRow($form->get('middlename')),"<br>";
echo $this->formRow($form->get('hat')),"<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>