<?php 
/** 
* just a view script for testing and experimenting with shit 
* this one is intended for use with Application\Controller\IndexController::testAction()
*/
?>
<h1>add a language</h1>
<p>a temporary view script for testing shit.</p>

<?php 
$form->prepare();


$form->setAttribute('action', $this->url('application',['action'=>'test']));
$form->add([
	'name'=>'submit',
	'type'=>'Zend\Form\Element\Submit',
	'attributes' => ['value'=>'submit'],
]);

$form->setAttribute('method', 'post');

// Render the opening tag
echo $this->form()->openTag($form);
echo $this->formRow($form->get('name')),"<br>";
echo $this->formRow($form->get('comments')),"<br>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>