<?php $this->headScript()
    ->appendFile($this->basePath("js/lib/moment/min/moment.min.js"))
    ->appendFile($this->basePath("js/lib/tui.chart/dist/tui-chart-all.min.js"))
    ->appendFile($this->basePath("js/admin/reports.js"));
$this->headStyle()->appendStyle($this->basePath("js/lib/tui.chart/dist/tui-chart.min.css"));
$this->headTitle('admin | reports');
$this->headStyle()->captureStart()?>
#table table th { font-weight: normal; color : #17a2b8; }
<?php 
$this->headStyle()->captureEnd()

?>
<div style="max-width:800px" class="mx-auto">
    <h2 class="text-center"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
    <p class="alert alert-warning rounded border border-warning shadow-sm py-2 px-5 mx-auto mt-3">This is still in development.</p>
    <form action="<?php echo $this->url('reports') ?>">
    <div class="form-row mb-2">
        <label class="col-md-2 col-form-label float-sm-left" for="report">report</label><div class="col-md-7"><select name="report" id="report" class="custom-select form-control">
            <?php $default_report = $this->defaults['report']??"YTD"; 
            foreach ($this->reports as $i =>$option): ?>
                <option value="<?=$i?>"<?php if ($i == $default_report):?> selected="selected"<?php endif ?>><?=$option?></option>
            <?php endforeach;?>            
        </select>
    </div>
    </div>
    <div class="form-row mb-2">
        <label class="col-md-2 col-form-label" for="dates">date range</label><div class="col-md-7"><select name="date-range" id="date-range" class="custom-select form-control">
            <?php $default_date_range  = $this->defaults['date-range'] ?? 1;
            foreach ($this->date_ranges as $i =>$option): ?>
                <option value="<?=$i?>"<?php if ($i == $default_date_range):?> selected="selected"<?php endif ?>><?=$option?></option>
            <?php endforeach;?>
        </select></div>
    </div>
    <div class="form-row mb-2">
    <label class="col-md-2 col-form-label" for="date-from">from</label>
    <div class="col-md-2"><input value="<?= $this->defaults['date-from']??''?>"name="date-from" id="date-from" class="form-control date" type="text"<?php 
    if (isset($this->defaults['date-from']) && $default_date_range != 'CUSTOM'):?> readonly<?php endif;?>></div>
    <label for="date-to" class="col-form-label col-auto">to</label>
    <div class="col-md-2"><input value="<?= $this->defaults['date-to']??''?>" name="date-to" id="date-to" class="form-control date" type="text" <?php 
    if (isset($this->defaults['date-from']) && $default_date_range != 'CUSTOM'):?> readonly<?php endif;?>></div><div class="col-md-2"><button id="btn-run" class="btn btn-success">run</button>
    </div>
    </div>
    </form>    
</div>
<div class="mx-auto" id="result">
    <!-- style="max-width:1000px"  -->
    <ul class="nav nav-tabs" id="tabs" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link active" id="table-tab" data-toggle="tab" href="#table" role="tab" aria-controls="table" aria-selected="true">table</a>
  </li>
  <li class="nav-item" role="chart">
    <a class="nav-link" id="chart-tab" data-toggle="tab" href="#chart" role="tab" aria-controls="chart" aria-selected="false">chart</a>
  </li>
  
</ul>
<div class="tab-content" id="tab-content">
  <div class="tab-pane show active" id="table" role="tabpanel" aria-labelledby="table-tab">
      <table class="table table-sm border mt-1" style="max-width:600px">
          <thead></thead>
          <tbody></tbody>
      </table>
  </div>
  <div class="tab-pane" id="chart" role="tabpanel" aria-labelledby="chart-tab">
      <!-- <div style="max-width:50px" class="bg-primary mx-auto text-center"><span class="fa fa-cog fa-spin text-white" style="font-size:1.2em"></div></p> -->
  </div>  
</div>
</di