<?php $this->headScript()
    ->appendFile($this->basePath("js/lib/moment/min/moment.min.js"))
    ->appendFile($this->basePath("js/lib/tui-chart/tui.chart-3.11.2/dist/tui-chart-all.min.js"))
    ->appendFile($this->basePath("js/admin/reports.js"));
$this->headStyle()->appendStyle($this->basePath("js/lib/tui-chart/tui.chart-3.11.2/dist/tui-chart.min.css"));
$this->headTitle('admin | reports')?>
<div style="max-width:800px" class="mx-auto">
    <h2 class="text-center"><?php echo $this->navigation('admin-breadcrumbs')->breadcrumbs()?></h2>
    <p class="alert alert-warning rounded border border-warning shadow-sm py-2 px-5 mx-auto mt-3">This is still in development.</p>
    <form action="<?php echo $this->url('reports') ?>">
    <div class="form-row mb-2">
        <label class="col-md-2 col-form-label float-sm-left" for="report">report</label><div class="col-md-7"><select name="report" id="report" class="custom-select form-control">
            <?php $default_report = $this->defaults['report']??"YTD"; 
            foreach ($this->reports as $i =>$option): ?>
                <option value="<?=$i?>"<?php if ($i == $default_report):?> selected="selected"<?php endif ?>><?=$option?></option>
            <?php endforeach;?>            
        </select>
    </div>
    </div>
    <div class="form-row mb-2">
        <label class="col-md-2 col-form-label" for="dates">date range</label><div class="col-md-7"><select name="date-range" id="date-range" class="custom-select form-control">
            <?php $default_date_range  = $this->defaults['date-range'] ?? 1;
            foreach ($this->date_ranges as $i =>$option): ?>
                <option value="<?=$i?>"<?php if ($i == $default_date_range):?> selected="selected"<?php endif ?>><?=$option?></option>
            <?php endforeach;?>
        </select></div>
    </div>
    <div class="form-row mb-2">
    <label class="col-md-2 col-form-label" for="date-from">from</label>
    <div class="col-md-2"><input value="<?= $this->defaults['date-from']??''?>"name="date-from" id="date-from" class="form-control date" type="text"<?php 
    if (isset($this->defaults['date-from']) && $default_date_range != 'CUSTOM'):?> readonly<?php endif;?>></div>
    <label for="date-to" class="col-form-label col-auto">to</label>
    <div class="col-md-2"><input value="<?= $this->defaults['date-to']??''?>" name="date-to" id="date-to" class="form-control date" type="text" <?php 
    if (isset($this->defaults['date-from']) && $default_date_range != 'CUSTOM'):?> readonly<?php endif;?>></div><div class="col-md-2"><button id="btn-run" class="btn btn-success">run</button>
    </div>
    </div>
    </form>    
</div>
<div style="max-width:1000px" class="mx-auto" id="result">
    
</div>